///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserTrackersPostModalData {
/*
{
  "isSaved": true
} 
*/

  bool? isSaved;

  UserTrackersPostModalData({
    this.isSaved,
  });
  UserTrackersPostModalData.fromJson(Map<String, dynamic> json) {
    isSaved = json['isSaved'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isSaved'] = isSaved;
    return data;
  }
}

class UserTrackersPostModal {
/*
{
  "success": true,
  "error": null,
  "data": {
    "isSaved": true
  }
} 
*/

  bool? success;
  String? error;
  UserTrackersPostModalData? data;

  UserTrackersPostModal({
    this.success,
    this.error,
    this.data,
  });
  UserTrackersPostModal.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    error = json['error']?.toString();
    data = (json['data'] != null) ? UserTrackersPostModalData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['error'] = error;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
