// ///
// /// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
// ///


// class Tracker {
// /*
// {
//   "tracker": "MOOD_TRACKER",
//   "displayText": "Mood Tracker",
//   "image": "assets/images/nutrition/moodtracker.png"
// } 
// */

//   String? tracker;
//   String? displayText;
//   String? image;

//   Tracker({
//     this.tracker,
//     this.displayText,
//     this.image,
//   });
//   Tracker.fromJson(Map<String, dynamic> json) {
//     tracker = json['tracker']?.toString();
//     displayText = json['displayText']?.toString();
//     image = json['image']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['tracker'] = tracker;
//     data['displayText'] = displayText;
//     data['image'] = image;
//     return data;
//   }
// }

// class UserTrackers {
// /*
// {
//   "trackerList": [
//     {
//       "tracker": "MOOD_TRACKER",
//       "displayText": "Mood Tracker",
//       "image": "assets/images/nutrition/moodtracker.png"
//     }
//   ],
//   "activeTrackers": [
//     {
//       "tracker": "WEIGHT_TRACKER",
//       "displayText": "Weight Tracker",
//       "image": "assets/images/nutrition/weighttracker.png"
//     }
//   ]
// } 
// */

//   List<Tracker?>? trackerList;
//   List<Tracker?>? activeTrackers;

//   UserTrackers({
//     this.trackerList,
//     this.activeTrackers,
//   });
//   UserTrackers.fromJson(Map<String, dynamic> json) {
//   if (json['trackerList'] != null) {
//   final v = json['trackerList'];
//   final arr0 = <Tracker>[];
//   v.forEach((v) {
//   arr0.add(Tracker.fromJson(v));
//   });
//     trackerList = arr0;
//     }
//   if (json['activeTrackers'] != null) {
//   final v = json['activeTrackers'];
//   final arr0 = <Tracker>[];
//   v.forEach((v) {
//   arr0.add(Tracker.fromJson(v));
//   });
//     activeTrackers = arr0;
//     }
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     if (trackerList != null) {
//       final v = trackerList;
//       final arr0 = [];
//   v!.forEach((v) {
//   arr0.add(v!.toJson());
//   });
//       data['trackerList'] = arr0;
//     }
//     if (activeTrackers != null) {
//       final v = activeTrackers;
//       final arr0 = [];
//   v!.forEach((v) {
//   arr0.add(v!.toJson());
//   });
//       data['activeTrackers'] = arr0;
//     }
//     return data;
//   }
// }
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///


class UserTrackersDataActiveTrackers {
/*
{
  "trackerId": "9ce1daa0-fb0c-11ed-b192-f30aa03c5e3c",
  "tracker": "MOOD_TRACKER",
  "displayText": "Mood Tracker",
  "icon": "",
  "image": ""
} 
*/

  String? trackerId;
  String? tracker;
  String? displayText;
  String? icon;
  String? image;

  UserTrackersDataActiveTrackers({
    this.trackerId,
    this.tracker,
    this.displayText,
    this.icon,
    this.image,
  });
  UserTrackersDataActiveTrackers.fromJson(Map<String, dynamic> json) {
    trackerId = json['trackerId']?.toString();
    tracker = json['tracker']?.toString();
    displayText = json['displayText']?.toString();
    icon = json['icon']?.toString();
    image = json['image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['trackerId'] = trackerId;
    data['tracker'] = tracker;
    data['displayText'] = displayText;
    data['icon'] = icon;
    data['image'] = image;
    return data;
  }
}

class UserTrackersData {
/*
{
  "activeTrackers": [
    {
      "trackerId": "9ce1daa0-fb0c-11ed-b192-f30aa03c5e3c",
      "tracker": "MOOD_TRACKER",
      "displayText": "Mood Tracker",
      "icon": "",
      "image": ""
    }
  ],
  "trackerList": [
    {
      "trackerId": "d4730340-fb0c-11ed-89b2-cbb54895fa4e",
      "tracker": "SLEEP_TRACKER",
      "displayText": "Sleep Tracker",
      "icon": "",
      "image": ""
    }
  ]
} 
*/

  List<UserTrackersDataActiveTrackers?>? activeTrackers;
  List<UserTrackersDataActiveTrackers?>? trackerList;

  UserTrackersData({
    this.activeTrackers,
    this.trackerList,
  });
  UserTrackersData.fromJson(Map<String, dynamic> json) {
  if (json['activeTrackers'] != null) {
  final v = json['activeTrackers'];
  final arr0 = <UserTrackersDataActiveTrackers>[];
  v.forEach((v) {
  arr0.add(UserTrackersDataActiveTrackers.fromJson(v));
  });
    activeTrackers = arr0;
    }
  if (json['trackerList'] != null) {
  final v = json['trackerList'];
  final arr0 = <UserTrackersDataActiveTrackers>[];
  v.forEach((v) {
  arr0.add(UserTrackersDataActiveTrackers.fromJson(v));
  });
    trackerList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (activeTrackers != null) {
      final v = activeTrackers;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['activeTrackers'] = arr0;
    }
    if (trackerList != null) {
      final v = trackerList;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['trackerList'] = arr0;
    }
    return data;
  }
}

class UserTrackers {
/*
{
  "success": true,
  "error": null,
  "data": {
    "activeTrackers": [
      {
        "trackerId": "9ce1daa0-fb0c-11ed-b192-f30aa03c5e3c",
        "tracker": "MOOD_TRACKER",
        "displayText": "Mood Tracker",
        "icon": "",
        "image": ""
      }
    ],
    "trackerList": [
      {
        "trackerId": "d4730340-fb0c-11ed-89b2-cbb54895fa4e",
        "tracker": "SLEEP_TRACKER",
        "displayText": "Sleep Tracker",
        "icon": "",
        "image": ""
      }
    ]
  }
} 
*/

  bool? success;
  String? error;
  UserTrackersData? data;

  UserTrackers({
    this.success,
    this.error,
    this.data,
  });
  UserTrackers.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    error = json['error']?.toString();
    data = (json['data'] != null) ? UserTrackersData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['error'] = error;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

