///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CoachJoinSessionModelAgoraDetails {
/*
{
  "token": "0062ae0887f11d64ca7b775782488589042IADdCJiYhoMTq7V4R7zdYGBgvZibuscxkmQYPlMjLmnj6gsCMpMAAAAAIgBB+B2kcpv9YwQAAQAIavxjAgAIavxjAwAIavxjBAAIavxj",
  "secondsRemaining": 6414
} 
*/

  String? token;
  int? secondsRemaining;

  CoachJoinSessionModelAgoraDetails({
    this.token,
    this.secondsRemaining,
  });
  CoachJoinSessionModelAgoraDetails.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
    secondsRemaining = json['secondsRemaining']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['token'] = token;
    data['secondsRemaining'] = secondsRemaining;
    return data;
  }
}

class CoachJoinSessionModelSession {
/*
{
  "sessionId": "6e6231e1-b663-11ed-a6c6-03f59283dab5",
  "consultType": "ADD-ON",
  "bookType": "PAID",
  "fromTime": 1677483000000,
  "toTime": 1677484800000
} 
*/

  String? sessionId;
  String? consultType;
  String? bookType;
  int? fromTime;
  int? toTime;

  CoachJoinSessionModelSession({
    this.sessionId,
    this.consultType,
    this.bookType,
    this.fromTime,
    this.toTime,
  });
  CoachJoinSessionModelSession.fromJson(Map<String, dynamic> json) {
    sessionId = json['sessionId']?.toString();
    consultType = json['consultType']?.toString();
    bookType = json['bookType']?.toString();
    fromTime = json['fromTime']?.toInt();
    toTime = json['toTime']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['sessionId'] = sessionId;
    data['consultType'] = consultType;
    data['bookType'] = bookType;
    data['fromTime'] = fromTime;
    data['toTime'] = toTime;
    return data;
  }
}

class CoachJoinSessionModelCoach {
/*
{
  "coachId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
  "coachName": "Aayu Expert",
  "profilePic": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1673427209776.jpg"
} 
*/

  String? coachId;
  String? coachName;
  String? profilePic;

  CoachJoinSessionModelCoach({
    this.coachId,
    this.coachName,
    this.profilePic,
  });
  CoachJoinSessionModelCoach.fromJson(Map<String, dynamic> json) {
    coachId = json['coachId']?.toString();
    coachName = json['coachName']?.toString();
    profilePic = json['profilePic']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['coachId'] = coachId;
    data['coachName'] = coachName;
    data['profilePic'] = profilePic;
    return data;
  }
}

class CoachJoinSessionModel {
/*
{
  "coach": {
    "coachId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
    "coachName": "Aayu Expert",
    "profilePic": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1673427209776.jpg"
  },
  "session": {
    "sessionId": "6e6231e1-b663-11ed-a6c6-03f59283dab5",
    "consultType": "ADD-ON",
    "bookType": "PAID",
    "fromTime": 1677483000000,
    "toTime": 1677484800000
  },
  "agoraDetails": {
    "token": "0062ae0887f11d64ca7b775782488589042IADdCJiYhoMTq7V4R7zdYGBgvZibuscxkmQYPlMjLmnj6gsCMpMAAAAAIgBB+B2kcpv9YwQAAQAIavxjAgAIavxjAwAIavxjBAAIavxj",
    "secondsRemaining": 6414
  }
} 
*/

  CoachJoinSessionModelCoach? coach;
  CoachJoinSessionModelSession? session;
  CoachJoinSessionModelAgoraDetails? agoraDetails;

  CoachJoinSessionModel({
    this.coach,
    this.session,
    this.agoraDetails,
  });
  CoachJoinSessionModel.fromJson(Map<String, dynamic> json) {
    coach = (json['coach'] != null)
        ? CoachJoinSessionModelCoach.fromJson(json['coach'])
        : null;
    session = (json['session'] != null)
        ? CoachJoinSessionModelSession.fromJson(json['session'])
        : null;
    agoraDetails = (json['agoraDetails'] != null)
        ? CoachJoinSessionModelAgoraDetails.fromJson(json['agoraDetails'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (coach != null) {
      data['coach'] = coach!.toJson();
    }
    if (session != null) {
      data['session'] = session!.toJson();
    }
    if (agoraDetails != null) {
      data['agoraDetails'] = agoraDetails!.toJson();
    }
    return data;
  }
}
