///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CoachSessionSummaryModelSessionSummaryCoach {
/*
{
  "coachId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
  "coachName": "Dr. Aayu Expert",
  "profilePic": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1673427209776.jpg"
} 
*/

  String? coachId;
  String? coachName;
  String? profilePic;

  CoachSessionSummaryModelSessionSummaryCoach({
    this.coachId,
    this.coachName,
    this.profilePic,
  });
  CoachSessionSummaryModelSessionSummaryCoach.fromJson(Map<String, dynamic> json) {
    coachId = json['coachId']?.toString();
    coachName = json['coachName']?.toString();
    profilePic = json['profilePic']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['coachId'] = coachId;
    data['coachName'] = coachName;
    data['profilePic'] = profilePic;
    return data;
  }
}

class CoachSessionSummaryModelSessionSummary {
/*
{
  "coach": {
    "coachId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
    "coachName": "Dr. Aayu Expert",
    "profilePic": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1673427209776.jpg"
  },
  "sessionId":"",
  "bookType": "PAID",
  "status": "MISSED",
  "fromTime": 1677042000000,
  "toTime": 1677043800000
} 
*/

  CoachSessionSummaryModelSessionSummaryCoach? coach;
  String? sessionId;
  String? bookType;
  String? status;
  int? fromTime;
  int? toTime;
  int? nextSchedule;
  bool? allowReschedule;

  CoachSessionSummaryModelSessionSummary({
    this.coach,
    this.bookType,
    this.status,
    this.fromTime,
    this.toTime,
    this.nextSchedule,
    this.allowReschedule,
  });
  CoachSessionSummaryModelSessionSummary.fromJson(Map<String, dynamic> json) {
    coach = (json['coach'] != null) ? CoachSessionSummaryModelSessionSummaryCoach.fromJson(json['coach']) : null;
    sessionId = json['sessionId']?.toString();
    bookType = json['bookType']?.toString();
    status = json['status']?.toString();
    fromTime = json['fromTime']?.toInt();
    toTime = json['toTime']?.toInt();
    nextSchedule = json['nextSchedule']?.toInt();
    allowReschedule = json['allowReschedule'] ?? false;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (coach != null) {
      data['coach'] = coach!.toJson();
    }
    data['sessionId'] = sessionId;
    data['bookType'] = bookType;
    data['status'] = status;
    data['fromTime'] = fromTime;
    data['toTime'] = toTime;
    data['nextSchedule'] = nextSchedule;
    data['allowReschedule'] = allowReschedule ?? false;
    return data;
  }
}

class CoachSessionSummaryModel {
/*
{
  "sessionSummary": [
    {
      "coach": {
        "coachId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
        "coachName": "Dr. Aayu Expert",
        "profilePic": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1673427209776.jpg"
      },
      "sessionId":"",
      "bookType": "PAID",
      "status": "MISSED",
      "fromTime": 1677042000000,
      "toTime": 1677043800000
    }
  ]
} 
*/

  List<CoachSessionSummaryModelSessionSummary?>? sessionSummary;

  CoachSessionSummaryModel({
    this.sessionSummary,
  });
  CoachSessionSummaryModel.fromJson(Map<String, dynamic> json) {
  if (json['sessionSummary'] != null) {
  final v = json['sessionSummary'];
  final arr0 = <CoachSessionSummaryModelSessionSummary>[];
  v.forEach((v) {
  arr0.add(CoachSessionSummaryModelSessionSummary.fromJson(v));
  });
    sessionSummary = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (sessionSummary != null) {
      final v = sessionSummary;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['sessionSummary'] = arr0;
    }
    return data;
  }
}
