///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CoachPastSessionsModelPastSessionsCoach {
/*
{
  "coachId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
  "coachName": "Dr. Aayu Expert",
  "profilePic": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1673427209776.jpg"
} 
*/

  String? coachId;
  String? coachName;
  String? profilePic;

  CoachPastSessionsModelPastSessionsCoach({
    this.coachId,
    this.coachName,
    this.profilePic,
  });
  CoachPastSessionsModelPastSessionsCoach.fromJson(Map<String, dynamic> json) {
    coachId = json['coachId']?.toString();
    coachName = json['coachName']?.toString();
    profilePic = json['profilePic']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['coachId'] = coachId;
    data['coachName'] = coachName;
    data['profilePic'] = profilePic;
    return data;
  }
}

class CoachPastSessionsModelPastSessions {
/*
{
  "coach": {
    "coachId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
    "coachName": "Dr. Aayu Expert",
    "profilePic": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1673427209776.jpg"
  },
  "bookType": "PAID",
  "status": "MISSED",
  "fromTime": 1677042000000,
  "toTime": 1677043800000
} 
*/

  CoachPastSessionsModelPastSessionsCoach? coach;
  String? bookType;
  String? status;
  int? fromTime;
  int? toTime;

  CoachPastSessionsModelPastSessions({
    this.coach,
    this.bookType,
    this.status,
    this.fromTime,
    this.toTime,
  });
  CoachPastSessionsModelPastSessions.fromJson(Map<String, dynamic> json) {
    coach = (json['coach'] != null) ? CoachPastSessionsModelPastSessionsCoach.fromJson(json['coach']) : null;
    bookType = json['bookType']?.toString();
    status = json['status']?.toString();
    fromTime = json['fromTime']?.toInt();
    toTime = json['toTime']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (coach != null) {
      data['coach'] = coach!.toJson();
    }
    data['bookType'] = bookType;
    data['status'] = status;
    data['fromTime'] = fromTime;
    data['toTime'] = toTime;
    return data;
  }
}

class CoachPastSessionsModel {
/*
{
  "pastSessions": [
    {
      "coach": {
        "coachId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
        "coachName": "Dr. Aayu Expert",
        "profilePic": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1673427209776.jpg"
      },
      "bookType": "PAID",
      "status": "MISSED",
      "fromTime": 1677042000000,
      "toTime": 1677043800000
    }
  ]
} 
*/

  List<CoachPastSessionsModelPastSessions?>? pastSessions;

  CoachPastSessionsModel({
    this.pastSessions,
  });
  CoachPastSessionsModel.fromJson(Map<String, dynamic> json) {
  if (json['pastSessions'] != null) {
  final v = json['pastSessions'];
  final arr0 = <CoachPastSessionsModelPastSessions>[];
  v.forEach((v) {
  arr0.add(CoachPastSessionsModelPastSessions.fromJson(v));
  });
    pastSessions = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pastSessions != null) {
      final v = pastSessions;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['pastSessions'] = arr0;
    }
    return data;
  }
}
