///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CoachAvailableSlotsModelAvailableSlots {
/*
{
  "sessionId": "b3778dc1-b2a8-11ed-a6c6-03f59283dab5",
  "timeZone": "Asia/Calcutta",
  "fromTime": 1677166200000,
  "toTime": 1677168000000,
  "selected": false
} 
*/

  String? sessionId;
  String? timeZone;
  int? fromTime;
  int? toTime;
  bool? selected;

  CoachAvailableSlotsModelAvailableSlots({
    this.sessionId,
    this.timeZone,
    this.fromTime,
    this.toTime,
    this.selected,
  });
  CoachAvailableSlotsModelAvailableSlots.fromJson(Map<String, dynamic> json) {
    sessionId = json['sessionId']?.toString();
    timeZone = json['timeZone']?.toString();
    fromTime = json['fromTime']?.toInt();
    toTime = json['toTime']?.toInt();
    selected = json['selected'] ?? false;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['sessionId'] = sessionId;
    data['timeZone'] = timeZone;
    data['fromTime'] = fromTime;
    data['toTime'] = toTime;
    data['selected'] = selected ?? false;
    return data;
  }
}

class CoachAvailableSlotsModel {
/*
{
  "availableSlots": [
    {
      "sessionId": "b3778dc1-b2a8-11ed-a6c6-03f59283dab5",
      "timeZone": "Asia/Calcutta",
      "fromTime": 1677166200000,
      "toTime": 1677168000000,
      "selected": false
    }
  ]
} 
*/

  List<CoachAvailableSlotsModelAvailableSlots?>? availableSlots;

  CoachAvailableSlotsModel({
    this.availableSlots,
  });
  CoachAvailableSlotsModel.fromJson(Map<String, dynamic> json) {
  if (json['availableSlots'] != null) {
  final v = json['availableSlots'];
  final arr0 = <CoachAvailableSlotsModelAvailableSlots>[];
  v.forEach((v) {
  arr0.add(CoachAvailableSlotsModelAvailableSlots.fromJson(v));
  });
    availableSlots = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (availableSlots != null) {
      final v = availableSlots;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['availableSlots'] = arr0;
    }
    return data;
  }
}
