///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CoachRecentlyConsultedModelRecentlyConsultedCoach {
/*
{
  "coachId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
  "coachName": "Dr. Aayu Expert",
  "profilePic": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1673427209776.jpg"
} 
*/

  String? coachId;
  String? coachName;
  String? profilePic;

  CoachRecentlyConsultedModelRecentlyConsultedCoach({
    this.coachId,
    this.coachName,
    this.profilePic,
  });
  CoachRecentlyConsultedModelRecentlyConsultedCoach.fromJson(Map<String, dynamic> json) {
    coachId = json['coachId']?.toString();
    coachName = json['coachName']?.toString();
    profilePic = json['profilePic']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['coachId'] = coachId;
    data['coachName'] = coachName;
    data['profilePic'] = profilePic;
    return data;
  }
}

class CoachRecentlyConsultedModelRecentlyConsulted {
/*
{
  "coach": {
    "coachId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
    "coachName": "Dr. Aayu Expert",
    "profilePic": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1673427209776.jpg"
  },
  "consultType": "PAID",
  "bookType": "PAID",
  "status": "MISSED",
  "fromTime": 1677042000000,
  "toTime": 1677043800000
} 
*/

  CoachRecentlyConsultedModelRecentlyConsultedCoach? coach;
  String? consultType;
  String? bookType;
  String? status;
  int? fromTime;
  int? toTime;

  CoachRecentlyConsultedModelRecentlyConsulted({
    this.coach,
    this.consultType,
    this.bookType,
    this.status,
    this.fromTime,
    this.toTime,
  });
  CoachRecentlyConsultedModelRecentlyConsulted.fromJson(Map<String, dynamic> json) {
    coach = (json['coach'] != null) ? CoachRecentlyConsultedModelRecentlyConsultedCoach.fromJson(json['coach']) : null;
    consultType = json['consultType']?.toString();
    bookType = json['bookType']?.toString();
    status = json['status']?.toString();
    fromTime = json['fromTime']?.toInt();
    toTime = json['toTime']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (coach != null) {
      data['coach'] = coach!.toJson();
    }
    data['consultType'] = consultType;
    data['bookType'] = bookType;
    data['status'] = status;
    data['fromTime'] = fromTime;
    data['toTime'] = toTime;
    return data;
  }
}

class CoachRecentlyConsultedModel {
/*
{
  "recentlyConsulted": [
    {
      "coach": {
        "coachId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
        "coachName": "Dr. Aayu Expert",
        "profilePic": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1673427209776.jpg"
      },
      "consultType": "PAID",
      "bookType": "PAID",
      "status": "MISSED",
      "fromTime": 1677042000000,
      "toTime": 1677043800000
    }
  ]
} 
*/

  List<CoachRecentlyConsultedModelRecentlyConsulted?>? recentlyConsulted;

  CoachRecentlyConsultedModel({
    this.recentlyConsulted,
  });
  CoachRecentlyConsultedModel.fromJson(Map<String, dynamic> json) {
  if (json['recentlyConsulted'] != null) {
  final v = json['recentlyConsulted'];
  final arr0 = <CoachRecentlyConsultedModelRecentlyConsulted>[];
  v.forEach((v) {
  arr0.add(CoachRecentlyConsultedModelRecentlyConsulted.fromJson(v));
  });
    recentlyConsulted = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (recentlyConsulted != null) {
      final v = recentlyConsulted;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['recentlyConsulted'] = arr0;
    }
    return data;
  }
}
