///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LiveEventDetailsModelEventDetailsAttendee {
/*
{
  "totalAttendees": 0,
  "isAttending": false
} 
*/

  int? totalAttendees;
  bool? isAttending;

  LiveEventDetailsModelEventDetailsAttendee({
    this.totalAttendees,
    this.isAttending,
  });
  LiveEventDetailsModelEventDetailsAttendee.fromJson(
      Map<String, dynamic> json) {
    totalAttendees = json['totalAttendees']?.toInt();
    isAttending = json['isAttending'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['totalAttendees'] = totalAttendees;
    data['isAttending'] = isAttending;
    return data;
  }
}

class LiveEventDetailsModelEventDetailsTrainer {
/*
{
  "trainerId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
  "name": "Dr. Aayu Expert",
  "gender": "Male",
  "photo": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1668583618873.jpg"
} 
*/

  String? trainerId;
  String? name;
  String? gender;
  String? photo;

  LiveEventDetailsModelEventDetailsTrainer({
    this.trainerId,
    this.name,
    this.gender,
    this.photo,
  });
  LiveEventDetailsModelEventDetailsTrainer.fromJson(Map<String, dynamic> json) {
    trainerId = json['trainerId']?.toString();
    name = json['name']?.toString();
    gender = json['gender']?.toString();
    photo = json['photo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['trainerId'] = trainerId;
    data['name'] = name;
    data['gender'] = gender;
    data['photo'] = photo;
    return data;
  }
}

class LiveEventDetailsModelEventDetailsMetaDataTags {
/*
{
  "displayTag": "test",
  "tagId": "1"
} 
*/

  String? displayTag;
  String? tagId;

  LiveEventDetailsModelEventDetailsMetaDataTags({
    this.displayTag,
    this.tagId,
  });
  LiveEventDetailsModelEventDetailsMetaDataTags.fromJson(
      Map<String, dynamic> json) {
    displayTag = json['displayTag']?.toString();
    tagId = json['tagId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['displayTag'] = displayTag;
    data['tagId'] = tagId;
    return data;
  }
}

class LiveEventDetailsModelEventDetailsMetaData {
/*
{
  "language": "English",
  "isPremium": false,
  "tags": [
    {
      "displayTag": "test",
      "tagId": "1"
    }
  ]
} 
*/

  String? language;
  bool? isPremium;
  List<LiveEventDetailsModelEventDetailsMetaDataTags?>? tags;

  LiveEventDetailsModelEventDetailsMetaData({
    this.language,
    this.isPremium,
    this.tags,
  });
  LiveEventDetailsModelEventDetailsMetaData.fromJson(
      Map<String, dynamic> json) {
    language = json['language']?.toString();
    isPremium = json['isPremium'];
    if (json['tags'] != null) {
      final v = json['tags'];
      final arr0 = <LiveEventDetailsModelEventDetailsMetaDataTags>[];
      v.forEach((v) {
        arr0.add(LiveEventDetailsModelEventDetailsMetaDataTags.fromJson(v));
      });
      tags = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['language'] = language;
    data['isPremium'] = isPremium;
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['tags'] = arr0;
    }
    return data;
  }
}

class LiveEventDetailsModelEventDetailsScheduleEpochTime {
/*
{
  "scheduleDate": 1669798800000,
  "startTime": 1669836600000,
  "endTime": 1669838400000,
  "timeZone": "US/Alaska"
} 
*/

  int? scheduleDate;
  int? startTime;
  int? endTime;
  String? timeZone;

  LiveEventDetailsModelEventDetailsScheduleEpochTime({
    this.scheduleDate,
    this.startTime,
    this.endTime,
    this.timeZone,
  });
  LiveEventDetailsModelEventDetailsScheduleEpochTime.fromJson(
      Map<String, dynamic> json) {
    scheduleDate = json['scheduleDate']?.toInt();
    startTime = json['startTime']?.toInt();
    endTime = json['endTime']?.toInt();
    timeZone = json['timeZone']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['scheduleDate'] = scheduleDate;
    data['startTime'] = startTime;
    data['endTime'] = endTime;
    data['timeZone'] = timeZone;
    return data;
  }
}

class LiveEventDetailsModelEventDetailsSchedule {
/*
{
  "scheduleDate": "2022-11-30",
  "startTime": "2022-11-30T19:30:00.000Z",
  "endTime": "2022-11-30T20:00:00.000Z",
  "secondsRemaining": 34910,
  "duration": "30 Minutes",
  "epochTime": {
    "scheduleDate": 1669798800000,
    "startTime": 1669836600000,
    "endTime": 1669838400000,
    "timeZone": "US/Alaska"
  }
} 
*/

  String? scheduleDate;
  String? startTime;
  String? endTime;
  int? secondsRemaining;
  String? duration;
  LiveEventDetailsModelEventDetailsScheduleEpochTime? epochTime;

  LiveEventDetailsModelEventDetailsSchedule({
    this.scheduleDate,
    this.startTime,
    this.endTime,
    this.secondsRemaining,
    this.duration,
    this.epochTime,
  });
  LiveEventDetailsModelEventDetailsSchedule.fromJson(
      Map<String, dynamic> json) {
    scheduleDate = json['scheduleDate']?.toString();
    startTime = json['startTime']?.toString();
    endTime = json['endTime']?.toString();
    secondsRemaining = json['secondsRemaining']?.toInt();
    duration = json['duration']?.toString();
    epochTime = (json['epochTime'] != null)
        ? LiveEventDetailsModelEventDetailsScheduleEpochTime.fromJson(
            json['epochTime'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['scheduleDate'] = scheduleDate;
    data['startTime'] = startTime;
    data['endTime'] = endTime;
    data['secondsRemaining'] = secondsRemaining;
    data['duration'] = duration;
    if (epochTime != null) {
      data['epochTime'] = epochTime!.toJson();
    }
    return data;
  }
}

class LiveEventDetailsModelEventDetailsEventImages {
/*
{
  "portrait": "https://content.aayu.live/aayu/app/event/thumb211022/04specificyoga.jpg",
  "landscape": "https://content.aayu.live/aayu/app/event/thumb211022/04specificyoga.jpg",
  "preview": "https://content.aayu.live/aayu/app/event/thumb211022/04specificyoga.jpg"
} 
*/

  String? portrait;
  String? landscape;
  String? preview;

  LiveEventDetailsModelEventDetailsEventImages({
    this.portrait,
    this.landscape,
    this.preview,
  });
  LiveEventDetailsModelEventDetailsEventImages.fromJson(
      Map<String, dynamic> json) {
    portrait = json['portrait']?.toString();
    landscape = json['landscape']?.toString();
    preview = json['preview']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['portrait'] = portrait;
    data['landscape'] = landscape;
    data['preview'] = preview;
    return data;
  }
}

class LiveEventDetailsModelEventDetails {
/*
{
  "eventTitle": "Test US Time",
  "eventType": "SPECIFIC YOGA",
  "description": "Worries of the future & regrets of the past cancel out your present. Unpack your suitcases; transform the scars of your past to wisdom, and the fear of the future to intuition.",
  "trainerId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
  "status": "ACTIVE",
  "eventImages": {
    "portrait": "https://content.aayu.live/aayu/app/event/thumb211022/04specificyoga.jpg",
    "landscape": "https://content.aayu.live/aayu/app/event/thumb211022/04specificyoga.jpg",
    "preview": "https://content.aayu.live/aayu/app/event/thumb211022/04specificyoga.jpg"
  },
  "schedule": {
    "scheduleDate": "2022-11-30",
    "startTime": "2022-11-30T19:30:00.000Z",
    "endTime": "2022-11-30T20:00:00.000Z",
    "secondsRemaining": 34910,
    "duration": "30 Minutes",
    "epochTime": {
      "scheduleDate": 1669798800000,
      "startTime": 1669836600000,
      "endTime": 1669838400000,
      "timeZone": "US/Alaska"
    }
  },
  "metaData": {
    "language": "English",
    "isPremium": false,
    "tags": [
      {
        "displayTag": "test",
        "tagId": "1"
      }
    ]
  },
  "liveEventId": "2222c8f0-706b-11ed-8a44-c3b9b695bfef",
  "trainer": {
    "trainerId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
    "name": "Dr. Aayu Expert",
    "gender": "Male",
    "photo": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1668583618873.jpg"
  },
  "attendee": {
    "totalAttendees": 0,
    "isAttending": false
  }
} 
*/

  String? eventTitle;
  String? eventType;
  String? description;
  String? trainerId;
  String? status;
  LiveEventDetailsModelEventDetailsEventImages? eventImages;
  LiveEventDetailsModelEventDetailsSchedule? schedule;
  LiveEventDetailsModelEventDetailsMetaData? metaData;
  String? liveEventId;
  LiveEventDetailsModelEventDetailsTrainer? trainer;
  LiveEventDetailsModelEventDetailsAttendee? attendee;

  LiveEventDetailsModelEventDetails({
    this.eventTitle,
    this.eventType,
    this.description,
    this.trainerId,
    this.status,
    this.eventImages,
    this.schedule,
    this.metaData,
    this.liveEventId,
    this.trainer,
    this.attendee,
  });
  LiveEventDetailsModelEventDetails.fromJson(Map<String, dynamic> json) {
    eventTitle = json['eventTitle']?.toString();
    eventType = json['eventType']?.toString();
    description = json['description']?.toString();
    trainerId = json['trainerId']?.toString();
    status = json['status']?.toString();
    eventImages = (json['eventImages'] != null)
        ? LiveEventDetailsModelEventDetailsEventImages.fromJson(
            json['eventImages'])
        : null;
    schedule = (json['schedule'] != null)
        ? LiveEventDetailsModelEventDetailsSchedule.fromJson(json['schedule'])
        : null;
    metaData = (json['metaData'] != null)
        ? LiveEventDetailsModelEventDetailsMetaData.fromJson(json['metaData'])
        : null;
    liveEventId = json['liveEventId']?.toString();
    trainer = (json['trainer'] != null)
        ? LiveEventDetailsModelEventDetailsTrainer.fromJson(json['trainer'])
        : null;
    attendee = (json['attendee'] != null)
        ? LiveEventDetailsModelEventDetailsAttendee.fromJson(json['attendee'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['eventTitle'] = eventTitle;
    data['eventType'] = eventType;
    data['description'] = description;
    data['trainerId'] = trainerId;
    data['status'] = status;
    if (eventImages != null) {
      data['eventImages'] = eventImages!.toJson();
    }
    if (schedule != null) {
      data['schedule'] = schedule!.toJson();
    }
    if (metaData != null) {
      data['metaData'] = metaData!.toJson();
    }
    data['liveEventId'] = liveEventId;
    if (trainer != null) {
      data['trainer'] = trainer!.toJson();
    }
    if (attendee != null) {
      data['attendee'] = attendee!.toJson();
    }
    return data;
  }
}

class LiveEventDetailsModel {
/*
{
  "eventDetails": {
    "eventTitle": "Test US Time",
    "eventType": "SPECIFIC YOGA",
    "description": "Worries of the future & regrets of the past cancel out your present. Unpack your suitcases; transform the scars of your past to wisdom, and the fear of the future to intuition.",
    "trainerId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
    "status": "ACTIVE",
    "eventImages": {
      "portrait": "https://content.aayu.live/aayu/app/event/thumb211022/04specificyoga.jpg",
      "landscape": "https://content.aayu.live/aayu/app/event/thumb211022/04specificyoga.jpg",
      "preview": "https://content.aayu.live/aayu/app/event/thumb211022/04specificyoga.jpg"
    },
    "schedule": {
      "scheduleDate": "2022-11-30",
      "startTime": "2022-11-30T19:30:00.000Z",
      "endTime": "2022-11-30T20:00:00.000Z",
      "secondsRemaining": 34910,
      "duration": "30 Minutes",
      "epochTime": {
        "scheduleDate": 1669798800000,
        "startTime": 1669836600000,
        "endTime": 1669838400000,
        "timeZone": "US/Alaska"
      }
    },
    "metaData": {
      "language": "English",
      "isPremium": false,
      "tags": [
        {
          "displayTag": "test",
          "tagId": "1"
        }
      ]
    },
    "liveEventId": "2222c8f0-706b-11ed-8a44-c3b9b695bfef",
    "trainer": {
      "trainerId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
      "name": "Dr. Aayu Expert",
      "gender": "Male",
      "photo": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1668583618873.jpg"
    },
    "attendee": {
      "totalAttendees": 0,
      "isAttending": false
    }
  }
} 
*/

  LiveEventDetailsModelEventDetails? eventDetails;

  LiveEventDetailsModel({
    this.eventDetails,
  });
  LiveEventDetailsModel.fromJson(Map<String, dynamic> json) {
    eventDetails = (json['eventDetails'] != null)
        ? LiveEventDetailsModelEventDetails.fromJson(json['eventDetails'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (eventDetails != null) {
      data['eventDetails'] = eventDetails!.toJson();
    }
    return data;
  }
}
