///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MoodListModelMoodsFeelings {
/*
{
  "feelingId": "0f7d766c-fb92-11ec-b939-0242ac120002",
  "feeling": "Stressed"
} 
*/

  String? feelingId;
  String? feeling;
  bool? isSelected;

  MoodListModelMoodsFeelings({
    this.feelingId,
    this.feeling,
    this.isSelected,
  });
  MoodListModelMoodsFeelings.fromJson(Map<String, dynamic> json) {
    feelingId = json['feelingId']?.toString();
    feeling = json['feeling']?.toString();
    isSelected = json['isSelected'] ?? false;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['feelingId'] = feelingId;
    data['feeling'] = feeling;
    data['isSelected'] = isSelected;

    return data;
  }
}

class MoodListModelMoods {
/*
{
  "isActive": true,
  "moodId": "253a08da-fc50-11ec-b939-0242ac120002",
  "mood": "Amazing",
  "icon": "assets/images/mood-tracker/amazing-icon.png",
  "feelings": [
    {
      "feelingId": "0f7d766c-fb92-11ec-b939-0242ac120002",
      "feeling": "Stressed"
    }
  ]
} 
*/

  bool? isActive;
  String? moodId;
  String? mood;
  String? icon;
  bool? isSelected;
  List<MoodListModelMoodsFeelings?>? feelings;

  MoodListModelMoods({
    this.isActive,
    this.moodId,
    this.mood,
    this.icon,
    this.feelings,
    this.isSelected,
  });
  MoodListModelMoods.fromJson(Map<String, dynamic> json) {
    isActive = json['isActive'];
    moodId = json['moodId']?.toString();
    mood = json['mood']?.toString();
    icon = json['icon']?.toString();
    isSelected = json['isSelected'] ?? false;
    if (json['feelings'] != null) {
      final v = json['feelings'];
      final arr0 = <MoodListModelMoodsFeelings>[];
      v.forEach((v) {
        arr0.add(MoodListModelMoodsFeelings.fromJson(v));
      });
      feelings = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isActive'] = isActive;
    data['moodId'] = moodId;
    data['mood'] = mood;
    data['icon'] = icon;
    data['isSelected'] = isSelected;
    if (feelings != null) {
      final v = feelings;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['feelings'] = arr0;
    }
    return data;
  }
}

class MoodListModel {
/*
{
  "moods": [
    {
      "isActive": true,
      "moodId": "253a08da-fc50-11ec-b939-0242ac120002",
      "mood": "Amazing",
      "icon": "assets/images/mood-tracker/amazing-icon.png",
      "feelings": [
        {
          "feelingId": "0f7d766c-fb92-11ec-b939-0242ac120002",
          "feeling": "Stressed"
        }
      ]
    }
  ]
} 
*/

  List<MoodListModelMoods?>? moods;

  MoodListModel({
    this.moods,
  });
  MoodListModel.fromJson(Map<String, dynamic> json) {
    if (json['moods'] != null) {
      final v = json['moods'];
      final arr0 = <MoodListModelMoods>[];
      v.forEach((v) {
        arr0.add(MoodListModelMoods.fromJson(v));
      });
      moods = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (moods != null) {
      final v = moods;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['moods'] = arr0;
    }
    return data;
  }
}
