///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MoodForDayModelList {
/*
{
  "time": "2022-03-11T20:26:15.634966",
  "mood": "Amazing",
  "you_are": [
    "Guilty"
  ],
  "because_of": [
    "Hobby"
  ],
  "text": "There are many variations of passages of Lorem Ipsum available, but the majority... have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words"
} 
*/

  String? time;
  String? mood;
  List<String?>? youAre;
  List<String?>? becauseOf;
  String? text;

  MoodForDayModelList({
    this.time,
    this.mood,
    this.youAre,
    this.becauseOf,
    this.text,
  });
  MoodForDayModelList.fromJson(Map<String, dynamic> json) {
    time = json['time']?.toString();
    mood = json['mood']?.toString();
    if (json['you_are'] != null) {
      final v = json['you_are'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      youAre = arr0;
    }
    if (json['because_of'] != null) {
      final v = json['because_of'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      becauseOf = arr0;
    }
    text = json['text']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['time'] = time;
    data['mood'] = mood;
    if (youAre != null) {
      final v = youAre;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['you_are'] = arr0;
    }
    if (becauseOf != null) {
      final v = becauseOf;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['because_of'] = arr0;
    }
    data['text'] = text;
    return data;
  }
}

class MoodForDayModel {
/*
{
  "date": "2022-03-11T22:26:15.634966",
  "list": [
    {
      "time": "2022-03-11T20:26:15.634966",
      "mood": "Amazing",
      "you_are": [
        "Guilty"
      ],
      "because_of": [
        "Hobby"
      ],
      "text": "There are many variations of passages of Lorem Ipsum available, but the majority... have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words"
    }
  ]
} 
*/

  String? date;
  List<MoodForDayModelList?>? list;

  MoodForDayModel({
    this.date,
    this.list,
  });
  MoodForDayModel.fromJson(Map<String, dynamic> json) {
    date = json['date']?.toString();
    if (json['list'] != null) {
      final v = json['list'];
      final arr0 = <MoodForDayModelList>[];
      v.forEach((v) {
        arr0.add(MoodForDayModelList.fromJson(v));
      });
      list = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['date'] = date;
    if (list != null) {
      final v = list;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['list'] = arr0;
    }
    return data;
  }
}
