import 'mood.check.in.model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class WeeklyMoodCheckInModelInsightMoodOfDuration {
/*
{
  "moodId": "253a08da-fc50-11ec-b939-0242ac120002",
  "mood": "Amazing",
  "icon": "assets/images/mood-tracker/amazing-icon.png"
} 
*/

  String? moodId;
  String? mood;
  String? icon;

  WeeklyMoodCheckInModelInsightMoodOfDuration({
    this.moodId,
    this.mood,
    this.icon,
  });
  WeeklyMoodCheckInModelInsightMoodOfDuration.fromJson(
      Map<String, dynamic> json) {
    moodId = json['moodId']?.toString();
    mood = json['mood']?.toString();
    icon = json['icon']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['moodId'] = moodId;
    data['mood'] = mood;
    data['icon'] = icon;
    return data;
  }
}

class WeeklyMoodCheckInModelInsight {
/*
{
  "moodOfDuration": {
    "moodId": "253a08da-fc50-11ec-b939-0242ac120002",
    "mood": "Amazing",
    "icon": "assets/images/mood-tracker/amazing-icon.png"
  },
  "youMostlyFelt": [
    {
      "feelingId": "0f7d781a-fb92-11ec-b939-0242ac120002",
      "feeling": "Lonely"
    }
  ],
  "becauseOf": [
    {
      "identificationId": "f811467c-fc2a-11ec-b939-0242ac120002",
      "identification": "Physical health"
    }
  ]
} 
*/

  WeeklyMoodCheckInModelInsightMoodOfDuration? moodOfDuration;
  List<MoodCheckInModelFeelings?>? youMostlyFelt;
  List<MoodCheckInModelIdentifications?>? becauseOf;

  WeeklyMoodCheckInModelInsight({
    this.moodOfDuration,
    this.youMostlyFelt,
    this.becauseOf,
  });
  WeeklyMoodCheckInModelInsight.fromJson(Map<String, dynamic> json) {
    moodOfDuration = (json['moodOfDuration'] != null)
        ? WeeklyMoodCheckInModelInsightMoodOfDuration.fromJson(
            json['moodOfDuration'])
        : null;
    if (json['youMostlyFelt'] != null) {
      final v = json['youMostlyFelt'];
      final arr0 = <MoodCheckInModelFeelings>[];
      v.forEach((v) {
        arr0.add(MoodCheckInModelFeelings.fromJson(v));
      });
      youMostlyFelt = arr0;
    }
    if (json['becauseOf'] != null) {
      final v = json['becauseOf'];
      final arr0 = <MoodCheckInModelIdentifications>[];
      v.forEach((v) {
        arr0.add(MoodCheckInModelIdentifications.fromJson(v));
      });
      becauseOf = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (moodOfDuration != null) {
      data['moodOfDuration'] = moodOfDuration!.toJson();
    }
    if (youMostlyFelt != null) {
      final v = youMostlyFelt;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['youMostlyFelt'] = arr0;
    }
    if (becauseOf != null) {
      final v = becauseOf;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['becauseOf'] = arr0;
    }
    return data;
  }
}

class WeeklyMoodCheckInModelDayWiseCheckInsMoods {
/*
{
  "moodId": "253a08da-fc50-11ec-b939-0242ac120002",
  "mood": "Amazing",
  "icon": "assets/images/mood-tracker/amazing-icon.png",
  "checkIns": 4
} 
*/

  String? moodId;
  String? mood;
  String? icon;
  int? checkIns;

  WeeklyMoodCheckInModelDayWiseCheckInsMoods({
    this.moodId,
    this.mood,
    this.icon,
    this.checkIns,
  });
  WeeklyMoodCheckInModelDayWiseCheckInsMoods.fromJson(
      Map<String, dynamic> json) {
    moodId = json['moodId']?.toString();
    mood = json['mood']?.toString();
    icon = json['icon']?.toString();
    checkIns = json['checkIns']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['moodId'] = moodId;
    data['mood'] = mood;
    data['icon'] = icon;
    data['checkIns'] = checkIns;
    return data;
  }
}

class WeeklyMoodCheckInModelDayWiseCheckIns {
/*
{
  "checkInDate": 1681689600000,
  "moods": [
    {
      "moodId": "253a08da-fc50-11ec-b939-0242ac120002",
      "mood": "Amazing",
      "icon": "assets/images/mood-tracker/amazing-icon.png",
      "checkIns": 4
    }
  ]
} 
*/

  DateTime? checkInDate;
  List<WeeklyMoodCheckInModelDayWiseCheckInsMoods?>? moods;

  WeeklyMoodCheckInModelDayWiseCheckIns({
    this.checkInDate,
    this.moods,
  });
  WeeklyMoodCheckInModelDayWiseCheckIns.fromJson(Map<String, dynamic> json) {
    checkInDate =
        DateTime.fromMillisecondsSinceEpoch(json['checkInDate']?.toInt());
    if (json['moods'] != null) {
      final v = json['moods'];
      final arr0 = <WeeklyMoodCheckInModelDayWiseCheckInsMoods>[];
      v.forEach((v) {
        arr0.add(WeeklyMoodCheckInModelDayWiseCheckInsMoods.fromJson(v));
      });
      moods = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['checkInDate'] = checkInDate!.millisecondsSinceEpoch;
    if (moods != null) {
      final v = moods;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['moods'] = arr0;
    }
    return data;
  }
}

class WeeklyMoodCheckInModel {
/*
{
  "dayWiseCheckIns": [
    {
      "checkInDate": 1681689600000,
      "moods": [
        {
          "moodId": "253a08da-fc50-11ec-b939-0242ac120002",
          "mood": "Amazing",
          "icon": "assets/images/mood-tracker/amazing-icon.png",
          "checkIns": 4
        }
      ]
    }
  ],
  "insight": {
    "moodOfDuration": {
      "moodId": "253a08da-fc50-11ec-b939-0242ac120002",
      "mood": "Amazing",
      "icon": "assets/images/mood-tracker/amazing-icon.png"
    },
    "youMostlyFelt": [
      {
        "feelingId": "0f7d781a-fb92-11ec-b939-0242ac120002",
        "feeling": "Lonely"
      }
    ],
    "becauseOf": [
      {
        "identificationId": "f811467c-fc2a-11ec-b939-0242ac120002",
        "identification": "Physical health"
      }
    ]
  }
} 
*/

  List<WeeklyMoodCheckInModelDayWiseCheckIns?>? dayWiseCheckIns;
  WeeklyMoodCheckInModelInsight? insight;

  WeeklyMoodCheckInModel({
    this.dayWiseCheckIns,
    this.insight,
  });
  WeeklyMoodCheckInModel.fromJson(Map<String, dynamic> json) {
    if (json['dayWiseCheckIns'] != null) {
      final v = json['dayWiseCheckIns'];
      final arr0 = <WeeklyMoodCheckInModelDayWiseCheckIns>[];
      v.forEach((v) {
        arr0.add(WeeklyMoodCheckInModelDayWiseCheckIns.fromJson(v));
      });
      dayWiseCheckIns = arr0;
    }
    insight = (json['insight'] != null)
        ? WeeklyMoodCheckInModelInsight.fromJson(json['insight'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (dayWiseCheckIns != null) {
      final v = dayWiseCheckIns;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['dayWiseCheckIns'] = arr0;
    }
    if (insight != null) {
      data['insight'] = insight!.toJson();
    }
    return data;
  }
}
