///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoyaltyUserCouponListModelUserCouponsUsageDetails {
/*
{
  "orderId": "",
  "usedOn": 1682603149000
} 
*/

  String? orderId;
  int? usedOn;

  LoyaltyUserCouponListModelUserCouponsUsageDetails({
    this.orderId,
    this.usedOn,
  });
  LoyaltyUserCouponListModelUserCouponsUsageDetails.fromJson(Map<String, dynamic> json) {
    orderId = json['orderId']?.toString();
    usedOn = int.tryParse(json['usedOn']?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['orderId'] = orderId;
    data['usedOn'] = usedOn;
    return data;
  }
}

class LoyaltyUserCouponListModelUserCoupons {
/*
{
  "appUserCouponId": "428eff90-da75-11ed-970c-5789ce673f90",
  "redeemSource": "IN-APP",
  "appRedeemId": "220ad270-c973-11ed-b43c-f52c3ce5cbed",
  "referenceId": "23532cc0-c97a-11ed-a043-0553271c628a",
  "redeemOn": "SUBSCRIPTION",
  "displayText": "Monthly Aayu Subscription",
  "description": "Monthly Aayu Subscription @ 10% discount",
  "theme": "#75C8E1",
  "vPoints": 5,
  "mPoints": 0,
  "expiresOn": 1682307268000,
  "status": "ACTIVE",
  "usageDetails": {
    "orderId": "",
    "usedOn": 1682603149000
  }
} 
*/

  String? appUserCouponId;
  String? redeemSource;
  String? appRedeemId;
  String? referenceId;
  String? redeemOn;
  String? displayText;
  String? description;
  String? theme;
  int? vPoints;
  int? mPoints;
  int? expiresOn;
  String? status;
  LoyaltyUserCouponListModelUserCouponsUsageDetails? usageDetails;

  LoyaltyUserCouponListModelUserCoupons({
    this.appUserCouponId,
    this.redeemSource,
    this.appRedeemId,
    this.referenceId,
    this.redeemOn,
    this.displayText,
    this.description,
    this.theme,
    this.vPoints,
    this.mPoints,
    this.expiresOn,
    this.status,
    this.usageDetails,
  });
  LoyaltyUserCouponListModelUserCoupons.fromJson(Map<String, dynamic> json) {
    appUserCouponId = json['appUserCouponId']?.toString();
    redeemSource = json['redeemSource']?.toString();
    appRedeemId = json['appRedeemId']?.toString();
    referenceId = json['referenceId']?.toString();
    redeemOn = json['redeemOn']?.toString();
    displayText = json['displayText']?.toString();
    description = json['description']?.toString();
    theme = json['theme']?.toString();
    vPoints = int.tryParse(json['vPoints']?.toString() ?? '');
    mPoints = int.tryParse(json['mPoints']?.toString() ?? '');
    expiresOn = int.tryParse(json['expiresOn']?.toString() ?? '');
    status = json['status']?.toString();
    usageDetails = (json['usageDetails'] != null && (json['usageDetails'] is Map)) ? LoyaltyUserCouponListModelUserCouponsUsageDetails.fromJson(json['usageDetails']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['appUserCouponId'] = appUserCouponId;
    data['redeemSource'] = redeemSource;
    data['appRedeemId'] = appRedeemId;
    data['referenceId'] = referenceId;
    data['redeemOn'] = redeemOn;
    data['displayText'] = displayText;
    data['description'] = description;
    data['theme'] = theme;
    data['vPoints'] = vPoints;
    data['mPoints'] = mPoints;
    data['expiresOn'] = expiresOn;
    data['status'] = status;
    if (usageDetails != null) {
      data['usageDetails'] = usageDetails!.toJson();
    }
    return data;
  }
}

class LoyaltyUserCouponListModel {
/*
{
  "userCoupons": [
    {
      "appUserCouponId": "428eff90-da75-11ed-970c-5789ce673f90",
      "redeemSource": "IN-APP",
      "appRedeemId": "220ad270-c973-11ed-b43c-f52c3ce5cbed",
      "referenceId": "23532cc0-c97a-11ed-a043-0553271c628a",
      "redeemOn": "SUBSCRIPTION",
      "displayText": "Monthly Aayu Subscription",
      "description": "Monthly Aayu Subscription @ 10% discount",
      "theme": "#75C8E1",
      "vPoints": 5,
      "mPoints": 0,
      "expiresOn": 1682307268000,
      "status": "ACTIVE",
      "usageDetails": {
        "orderId": "",
        "usedOn": 1682603149000
      }
    }
  ]
} 
*/

  List<LoyaltyUserCouponListModelUserCoupons?>? userCoupons;

  LoyaltyUserCouponListModel({
    this.userCoupons,
  });
  LoyaltyUserCouponListModel.fromJson(Map<String, dynamic> json) {
  if (json['userCoupons'] != null && (json['userCoupons'] is List)) {
  final v = json['userCoupons'];
  final arr0 = <LoyaltyUserCouponListModelUserCoupons>[];
  v.forEach((v) {
  arr0.add(LoyaltyUserCouponListModelUserCoupons.fromJson(v));
  });
    userCoupons = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (userCoupons != null) {
      final v = userCoupons;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['userCoupons'] = arr0;
    }
    return data;
  }
}
