///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoyaltyRedeemListModelRedeemList {
/*
{
  "appRedeemId": "220ad270-c973-11ed-b43c-f52c3ce5cbed",
  "redeemName": "MONTHLY_AAYU_SUBSCRIPTION",
  "redeemOn": "SUBSCRIPTION",
  "displayText": "Monthly Aayu Subscription",
  "description": "Monthly Aayu Subscription @ 10% discount",
  "theme": "#75C8E1",
  "vPoints": 5,
  "mPoints": 0,
  "redeemSource": "IN-APP",
  "referenceId": "23532cc0-c97a-11ed-a043-0553271c628a",
  "allowRedeem": true
} 
*/

  String? appRedeemId;
  String? redeemName;
  String? redeemOn;
  String? displayText;
  String? description;
  String? theme;
  int? vPoints;
  int? mPoints;
  String? redeemSource;
  String? referenceId;
  bool? allowRedeem;

  LoyaltyRedeemListModelRedeemList({
    this.appRedeemId,
    this.redeemName,
    this.redeemOn,
    this.displayText,
    this.description,
    this.theme,
    this.vPoints,
    this.mPoints,
    this.redeemSource,
    this.referenceId,
    this.allowRedeem,
  });
  LoyaltyRedeemListModelRedeemList.fromJson(Map<String, dynamic> json) {
    appRedeemId = json['appRedeemId']?.toString();
    redeemName = json['redeemName']?.toString();
    redeemOn = json['redeemOn']?.toString();
    displayText = json['displayText']?.toString();
    description = json['description']?.toString();
    theme = json['theme']?.toString();
    vPoints = int.tryParse(json['vPoints']?.toString() ?? '');
    mPoints = int.tryParse(json['mPoints']?.toString() ?? '');
    redeemSource = json['redeemSource']?.toString();
    referenceId = json['referenceId']?.toString();
    allowRedeem = json['allowRedeem'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['appRedeemId'] = appRedeemId;
    data['redeemName'] = redeemName;
    data['redeemOn'] = redeemOn;
    data['displayText'] = displayText;
    data['description'] = description;
    data['theme'] = theme;
    data['vPoints'] = vPoints;
    data['mPoints'] = mPoints;
    data['redeemSource'] = redeemSource;
    data['referenceId'] = referenceId;
    data['allowRedeem'] = allowRedeem;
    return data;
  }
}

class LoyaltyRedeemListModel {
/*
{
  "redeemList": [
    {
      "appRedeemId": "220ad270-c973-11ed-b43c-f52c3ce5cbed",
      "redeemName": "MONTHLY_AAYU_SUBSCRIPTION",
      "redeemOn": "SUBSCRIPTION",
      "displayText": "Monthly Aayu Subscription",
      "description": "Monthly Aayu Subscription @ 10% discount",
      "theme": "#75C8E1",
      "vPoints": 5,
      "mPoints": 0,
      "redeemSource": "IN-APP",
      "referenceId": "23532cc0-c97a-11ed-a043-0553271c628a",
      "allowRedeem": true
    }
  ]
} 
*/

  List<LoyaltyRedeemListModelRedeemList?>? redeemList;

  LoyaltyRedeemListModel({
    this.redeemList,
  });
  LoyaltyRedeemListModel.fromJson(Map<String, dynamic> json) {
    if (json['redeemList'] != null && (json['redeemList'] is List)) {
      final v = json['redeemList'];
      final arr0 = <LoyaltyRedeemListModelRedeemList>[];
      v.forEach((v) {
        arr0.add(LoyaltyRedeemListModelRedeemList.fromJson(v));
      });
      redeemList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (redeemList != null) {
      final v = redeemList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['redeemList'] = arr0;
    }
    return data;
  }
}
