///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoyaltyUserPointsModelPoints {
/*
{
  "vPoints": 41,
  "mPoints": 0
} 
*/

  int? vPoints;
  int? mPoints;

  LoyaltyUserPointsModelPoints({
    this.vPoints,
    this.mPoints,
  });
  LoyaltyUserPointsModelPoints.fromJson(Map<String, dynamic> json) {
    vPoints = int.tryParse(json['vPoints']?.toString() ?? '');
    mPoints = int.tryParse(json['mPoints']?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['vPoints'] = vPoints;
    data['mPoints'] = mPoints;
    return data;
  }
}

class LoyaltyUserPointsModel {
/*
{
  "points": {
    "vPoints": 41,
    "mPoints": 0
  }
} 
*/

  LoyaltyUserPointsModelPoints? points;

  LoyaltyUserPointsModel({
    this.points,
  });
  LoyaltyUserPointsModel.fromJson(Map<String, dynamic> json) {
    points = (json['points'] != null && (json['points'] is Map))
        ? LoyaltyUserPointsModelPoints.fromJson(json['points'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (points != null) {
      data['points'] = points!.toJson();
    }
    return data;
  }
}
