///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserPnGetModalDataChoices {
/*
{
  "pnTypeId": "07401220-e52a-11ed-b3b7-f1bd6fc659d7",
  "pnType": "MINDFULNESS",
  "icon": "/aayu/app/notification/mindfulness.svg",
  "displayText": "Mindfulness",
  "desc": "Meditation, Music, Relationships, Affirmations.",
  "priority": 1,
  "enabled": false
} 
*/

  String? pnTypeId;
  String? pnType;
  String? icon;
  String? displayText;
  String? desc;
  int? priority;
  bool? enabled;

  UserPnGetModalDataChoices({
    this.pnTypeId,
    this.pnType,
    this.icon,
    this.displayText,
    this.desc,
    this.priority,
    this.enabled,
  });
  UserPnGetModalDataChoices.fromJson(Map<String, dynamic> json) {
    pnTypeId = json['pnTypeId']?.toString();
    pnType = json['pnType']?.toString();
    icon = json['icon']?.toString();
    displayText = json['displayText']?.toString();
    desc = json['desc']?.toString();
    priority = json['priority']?.toInt();
    enabled = json['enabled'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['pnTypeId'] = pnTypeId;
    data['pnType'] = pnType;
    data['icon'] = icon;
    data['displayText'] = displayText;
    data['desc'] = desc;
    data['priority'] = priority;
    data['enabled'] = enabled;
    return data;
  }
}

class UserPnGetModalData {
/*
{
  "choices": [
    {
      "pnTypeId": "575e5320-e52a-11ed-b3b7-f1bd6fc659d7",
      "pnType": "CONSULTATION",
      "displayText": "Consultation",
      "enabled": false
    }
  ]
} 
*/

  List<UserPnGetModalDataChoices?>? choices;

  UserPnGetModalData({
    this.choices,
  });
  UserPnGetModalData.fromJson(Map<String, dynamic> json) {
    if (json['choices'] != null) {
      final v = json['choices'];
      final arr0 = <UserPnGetModalDataChoices>[];
      v.forEach((v) {
        arr0.add(UserPnGetModalDataChoices.fromJson(v));
      });
      choices = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (choices != null) {
      final v = choices;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['choices'] = arr0;
    }
    return data;
  }
}

class UserPnGetModal {
/*
{
  "success": true,
  "error": null,
  "data": {
    "choices": [
      {
        "pnTypeId": "575e5320-e52a-11ed-b3b7-f1bd6fc659d7",
        "pnType": "CONSULTATION",
        "displayText": "Consultation",
        "enabled": false
      }
    ]
  }
} 
*/

  bool? success;
  String? error;
  UserPnGetModalData? data;

  UserPnGetModal({
    this.success,
    this.error,
    this.data,
  });
  UserPnGetModal.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    error = json['error']?.toString();
    data = (json['data'] != null)
        ? UserPnGetModalData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['error'] = error;
    data['data'] = this.data!.toJson();
    return data;
  }
}
