///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserPnPostModalData {
/*
{
  "isUpdated": false
} 
*/

  bool? isUpdated;

  UserPnPostModalData({
    this.isUpdated,
  });
  UserPnPostModalData.fromJson(Map<String, dynamic> json) {
    isUpdated = json['isUpdated'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isUpdated'] = isUpdated;
    return data;
  }
}

class UserPnPostModal {
/*
{
  "success": true,
  "error": null,
  "data": {
    "isUpdated": false
  }
} 
*/

  bool? success;
  String? error;
  UserPnPostModalData? data;

  UserPnPostModal({
    this.success,
    this.error,
    this.data,
  });
  UserPnPostModal.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    error = json['error']?.toString();
    data = (json['data'] != null) ? UserPnPostModalData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['error'] = error;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
