///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TodaysWeightDetailsModelDetailsLatestWeight {
/*
{
  "checkInDate": 1682380800000,
  "weight": 100.2
} 
*/

  int? checkInDate;
  double? weight;

  TodaysWeightDetailsModelDetailsLatestWeight({
    this.checkInDate,
    this.weight,
  });
  TodaysWeightDetailsModelDetailsLatestWeight.fromJson(
      Map<String, dynamic> json) {
    checkInDate = int.tryParse(json['checkInDate']?.toString() ?? '');
    weight = double.tryParse(json['weight']?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['checkInDate'] = checkInDate;
    data['weight'] = weight;
    return data;
  }
}

class TodaysWeightDetailsModelDetailsReminder {
/*
{
  "isActive": true,
  "repeat": [
    "SUN"
  ]
} 
*/

  bool? isActive;
  List<String?>? repeat;
  int? reminderTime;

  TodaysWeightDetailsModelDetailsReminder(
      {this.isActive, this.repeat, this.reminderTime});
  TodaysWeightDetailsModelDetailsReminder.fromJson(Map<String, dynamic> json) {
    isActive = json['isActive'];
    if (json['repeat'] != null && (json['repeat'] is List)) {
      final v = json['repeat'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      repeat = arr0;
      reminderTime = int.tryParse(json['reminderTime']?.toString() ?? '');
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isActive'] = isActive;
    if (repeat != null) {
      final v = repeat;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['repeat'] = arr0;
      data['reminderTime'] = reminderTime;
    }
    return data;
  }
}

class TodaysWeightDetailsModelDetailsWeightGoal {
/*
{
  "isActive": true,
  "targetWeight": 60.2
} 
*/

  bool? isActive;
  double? targetWeight;

  TodaysWeightDetailsModelDetailsWeightGoal({
    this.isActive,
    this.targetWeight,
  });
  TodaysWeightDetailsModelDetailsWeightGoal.fromJson(
      Map<String, dynamic> json) {
    isActive = json['isActive'];
    targetWeight = double.tryParse(json['targetWeight']?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isActive'] = isActive;
    data['targetWeight'] = targetWeight;
    return data;
  }
}

class TodaysWeightDetailsModelDetailsHeight {
/*
{
  "unit": "FEET",
  "value": "5.6"
} 
*/

  String? unit;
  String? value;

  TodaysWeightDetailsModelDetailsHeight({
    this.unit,
    this.value,
  });
  TodaysWeightDetailsModelDetailsHeight.fromJson(Map<String, dynamic> json) {
    unit = json['unit']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['unit'] = unit;
    data['value'] = value;
    return data;
  }
}

class TodaysWeightDetailsModelDetails {
/*
{
  "height": {
    "unit": "FEET",
    "value": "5.6"
  },
  "weightGoal": {
    "isActive": true,
    "targetWeight": 60.2
  },
  "defaultUnit": "LBS",
  "reminder": {
    "isActive": true,
    "repeat": [
      "SUN"
    ]
  },
  "todaysDate": 1682467200000,
  "todaysWeight": 0.2,
  "latestWeight": {
    "checkInDate": 1682380800000,
    "weight": 100.2
  }
} 
*/

  TodaysWeightDetailsModelDetailsHeight? height;
  TodaysWeightDetailsModelDetailsWeightGoal? weightGoal;
  String? defaultUnit;
  TodaysWeightDetailsModelDetailsReminder? reminder;
  int? todaysDate;
  double? todaysWeight;
  TodaysWeightDetailsModelDetailsLatestWeight? latestWeight;

  TodaysWeightDetailsModelDetails({
    this.height,
    this.weightGoal,
    this.defaultUnit,
    this.reminder,
    this.todaysDate,
    this.todaysWeight,
    this.latestWeight,
  });
  TodaysWeightDetailsModelDetails.fromJson(Map<String, dynamic> json) {
    height = (json['height'] != null && (json['height'] is Map))
        ? TodaysWeightDetailsModelDetailsHeight.fromJson(json['height'])
        : null;
    weightGoal = (json['weightGoal'] != null && (json['weightGoal'] is Map))
        ? TodaysWeightDetailsModelDetailsWeightGoal.fromJson(json['weightGoal'])
        : null;
    defaultUnit = json['defaultUnit']?.toString();
    reminder = (json['reminder'] != null && (json['reminder'] is Map))
        ? TodaysWeightDetailsModelDetailsReminder.fromJson(json['reminder'])
        : null;
    todaysDate = int.tryParse(json['todaysDate']?.toString() ?? '');
    todaysWeight = double.tryParse(json['todaysWeight']?.toString() ?? '');
    latestWeight =
        (json['latestWeight'] != null && (json['latestWeight'] is Map))
            ? TodaysWeightDetailsModelDetailsLatestWeight.fromJson(
                json['latestWeight'])
            : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (height != null) {
      data['height'] = height!.toJson();
    }
    if (weightGoal != null) {
      data['weightGoal'] = weightGoal!.toJson();
    }
    data['defaultUnit'] = defaultUnit;
    if (reminder != null) {
      data['reminder'] = reminder!.toJson();
    }
    data['todaysDate'] = todaysDate;
    data['todaysWeight'] = todaysWeight;
    if (latestWeight != null) {
      data['latestWeight'] = latestWeight!.toJson();
    }
    return data;
  }
}

class TodaysWeightDetailsModel {
/*
{
  "details": {
    "height": {
      "unit": "FEET",
      "value": "5.6"
    },
    "weightGoal": {
      "isActive": true,
      "targetWeight": 60.2
    },
    "defaultUnit": "LBS",
    "reminder": {
      "isActive": true,
      "repeat": [
        "SUN"
      ]
    },
    "todaysDate": 1682467200000,
    "todaysWeight": 0.2,
    "latestWeight": {
      "checkInDate": 1682380800000,
      "weight": 100.2
    }
  }
} 
*/

  TodaysWeightDetailsModelDetails? details;

  TodaysWeightDetailsModel({
    this.details,
  });
  TodaysWeightDetailsModel.fromJson(Map<String, dynamic> json) {
    details = (json['details'] != null && (json['details'] is Map))
        ? TodaysWeightDetailsModelDetails.fromJson(json['details'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (details != null) {
      data['details'] = details!.toJson();
    }
    return data;
  }
}
