///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DoctorsPastListModelLiveStatus {
/*
{
  "isLive": true,
  "isUnderMaintenance": false,
  "message": ""
} 
*/

  bool? isLive;
  bool? isUnderMaintenance;
  String? message;

  DoctorsPastListModelLiveStatus({
    this.isLive,
    this.isUnderMaintenance,
    this.message,
  });
  DoctorsPastListModelLiveStatus.fromJson(Map<String, dynamic> json) {
    isLive = json['isLive'];
    isUnderMaintenance = json['isUnderMaintenance'];
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isLive'] = isLive;
    data['isUnderMaintenance'] = isUnderMaintenance;
    data['message'] = message;
    return data;
  }
}

class DoctorsPastListModelDoctors {
/*
{
  "doctorId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
  "doctorName": "Dr. Aayu Expert",
  "profilePic": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1673427209776.jpg",
  "speciality": "Allopathy, Ayurveda, Counseling, Energy Medicine Therapy, Homeopathy, Integrative Medicine, Naturopathy, Nutrition, Physiotherapy, Psychotherapy, Siddha Medicine, Yoga, Yoga Therapy, 2 years Exp.",
  "desc": "Testing",
  "rating": 4.1,
  "sessionFee": 0,
  "isOnline": true,
  "speaks": "English, Hindi, Marathi",
  "sessionCount": 3,
  "level": 1,
  "epochTime": 1670855400000
} 
*/

  String? doctorId;
  String? doctorName;
  String? profilePic;
  String? speciality;
  String? desc;
  double? rating;
  int? sessionFee;
  bool? isOnline;
  String? speaks;
  int? sessionCount;
  int? level;
  int? epochTime;

  DoctorsPastListModelDoctors({
    this.doctorId,
    this.doctorName,
    this.profilePic,
    this.speciality,
    this.desc,
    this.rating,
    this.sessionFee,
    this.isOnline,
    this.speaks,
    this.sessionCount,
    this.level,
    this.epochTime,
  });
  DoctorsPastListModelDoctors.fromJson(Map<String, dynamic> json) {
    doctorId = json['doctorId']?.toString();
    doctorName = json['doctorName']?.toString();
    profilePic = json['profilePic']?.toString();
    speciality = json['speciality']?.toString();
    desc = json['desc']?.toString();
    rating = json['rating']?.toDouble();
    sessionFee = json['sessionFee']?.toInt();
    isOnline = json['isOnline'];
    speaks = json['speaks']?.toString();
    sessionCount = json['sessionCount']?.toInt();
    level = json['level']?.toInt();
    epochTime = json['epochTime']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['doctorId'] = doctorId;
    data['doctorName'] = doctorName;
    data['profilePic'] = profilePic;
    data['speciality'] = speciality;
    data['desc'] = desc;
    data['rating'] = rating;
    data['sessionFee'] = sessionFee;
    data['isOnline'] = isOnline;
    data['speaks'] = speaks;
    data['sessionCount'] = sessionCount;
    data['level'] = level;
    data['epochTime'] = epochTime;
    return data;
  }
}

class DoctorsPastListModel {
/*
{
  "doctors": [
    {
      "doctorId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
      "doctorName": "Dr. Aayu Expert",
      "profilePic": "https://resetcontent.s3.amazonaws.com/trainerprofile/8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e/image_cropper_1673427209776.jpg",
      "speciality": "Allopathy, Ayurveda, Counseling, Energy Medicine Therapy, Homeopathy, Integrative Medicine, Naturopathy, Nutrition, Physiotherapy, Psychotherapy, Siddha Medicine, Yoga, Yoga Therapy, 2 years Exp.",
      "desc": "Testing",
      "rating": 4.1,
      "sessionFee": 0,
      "isOnline": true,
      "speaks": "English, Hindi, Marathi",
      "sessionCount": 3,
      "level": 1,
      "epochTime": 1670855400000
    }
  ],
  "liveStatus": {
    "isLive": true,
    "isUnderMaintenance": false,
    "message": ""
  }
} 
*/

  List<DoctorsPastListModelDoctors?>? doctors;
  DoctorsPastListModelLiveStatus? liveStatus;

  DoctorsPastListModel({
    this.doctors,
    this.liveStatus,
  });
  DoctorsPastListModel.fromJson(Map<String, dynamic> json) {
    if (json['doctors'] != null) {
      final v = json['doctors'];
      final arr0 = <DoctorsPastListModelDoctors>[];
      v.forEach((v) {
        arr0.add(DoctorsPastListModelDoctors.fromJson(v));
      });
      doctors = arr0;
    }
    liveStatus = (json['liveStatus'] != null)
        ? DoctorsPastListModelLiveStatus.fromJson(json['liveStatus'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (doctors != null) {
      final v = doctors;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['doctors'] = arr0;
    }
    if (liveStatus != null) {
      data['liveStatus'] = liveStatus!.toJson();
    }
    return data;
  }
}
