///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RecommendedProgramResponseRecommendationSilverAppBarImage {
/*
{
  "imageUrl": "https://stg-content.aayu.live/healing/anxiety_icon.png",
  "height": 65,
  "width": 104
} 
*/

  String? imageUrl;
  int? height;
  int? width;

  RecommendedProgramResponseRecommendationSilverAppBarImage({
    this.imageUrl,
    this.height,
    this.width,
  });
  RecommendedProgramResponseRecommendationSilverAppBarImage.fromJson(
      Map<String, dynamic> json) {
    imageUrl = json['imageUrl']?.toString();
    height = json['height']?.toInt();
    width = json['width']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['imageUrl'] = imageUrl;
    data['height'] = height;
    data['width'] = width;
    return data;
  }
}

class RecommendedProgramResponseRecommendationSilverAppBar {
/*
{
  "title": "Anxiety Disorder Care",
  "textColor": "#FFB3B0",
  "backgroundImage": "https://stg-content.aayu.live/healing/disease.png",
  "image": {
    "imageUrl": "https://stg-content.aayu.live/healing/anxiety_icon.png",
    "height": 65,
    "width": 104
  }
} 
*/

  String? title;
  String? textColor;
  String? backgroundImage;
  RecommendedProgramResponseRecommendationSilverAppBarImage? image;

  RecommendedProgramResponseRecommendationSilverAppBar({
    this.title,
    this.textColor,
    this.backgroundImage,
    this.image,
  });
  RecommendedProgramResponseRecommendationSilverAppBar.fromJson(
      Map<String, dynamic> json) {
    title = json['title']?.toString();
    textColor = json['textColor']?.toString();
    backgroundImage = json['backgroundImage']?.toString();
    image = (json['image'] != null)
        ? RecommendedProgramResponseRecommendationSilverAppBarImage.fromJson(
            json['image'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['textColor'] = textColor;
    data['backgroundImage'] = backgroundImage;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    return data;
  }
}

class RecommendedProgramResponseRecommendationDisease {
/*
{
  "diseaseId": "d34deb00-c21a-11ec-8195-fb3d9a5f7244",
  "diseaseName": "Diabetes"
} 
*/

  String? diseaseId;
  String? diseaseName;

  RecommendedProgramResponseRecommendationDisease({
    this.diseaseId,
    this.diseaseName,
  });
  RecommendedProgramResponseRecommendationDisease.fromJson(
      Map<String, dynamic> json) {
    diseaseId = json['diseaseId']?.toString();
    diseaseName = json['diseaseName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['diseaseId'] = diseaseId;
    data['diseaseName'] = diseaseName;
    return data;
  }
}

class RecommendedProgramResponseRecommendationDoctorDetails {
/*
{
  "doctorName": "Dr. Aayu Expert",
  "doctorId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
  "gender": "Male",
  "photo": "",
  "profession": [
    "Doctor"
  ]
} 
*/

  String? doctorName;
  String? doctorId;
  String? gender;
  String? photo;
  List<String?>? profession;

  RecommendedProgramResponseRecommendationDoctorDetails({
    this.doctorName,
    this.doctorId,
    this.gender,
    this.photo,
    this.profession,
  });
  RecommendedProgramResponseRecommendationDoctorDetails.fromJson(
      Map<String, dynamic> json) {
    doctorName = json['doctorName']?.toString();
    doctorId = json['doctorId']?.toString();
    gender = json['gender']?.toString();
    photo = json['photo']?.toString();
    if (json['profession'] != null) {
      final v = json['profession'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      profession = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['doctorName'] = doctorName;
    data['doctorId'] = doctorId;
    data['gender'] = gender;
    data['photo'] = photo;
    if (profession != null) {
      final v = profession;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['profession'] = arr0;
    }
    return data;
  }
}

class RecommendedProgramResponseRecommendation {
/*
{
  "doctorDetails": {
    "doctorName": "Dr. Aayu Expert",
    "doctorId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
    "gender": "Male",
    "photo": "",
    "profession": [
      "Doctor"
    ]
  },
  "programType": "SINGLE DISEASE",
  "disease": [
    {
      "diseaseId": "d34deb00-c21a-11ec-8195-fb3d9a5f7244",
      "diseaseName": "Diabetes"
    }
  ],
  "identityId": "da4ea560-3e26-11ed-8433-9f88b92b454d",
  "duration": "30",
  "period": "90",
  "programId": "90",
  "sessionId": "4ded4c70-3e26-11ed-931d-6b8fbb69dd7e",
  "silverAppBar": {
    "title": "Anxiety Disorder Care",
    "textColor": "#FFB3B0",
    "backgroundImage": "https://stg-content.aayu.live/healing/disease.png",
    "image": {
      "imageUrl": "https://stg-content.aayu.live/healing/anxiety_icon.png",
      "height": 65,
      "width": 104
    }
  }
} 
*/

  RecommendedProgramResponseRecommendationDoctorDetails? doctorDetails;
  String? programType;
  List<RecommendedProgramResponseRecommendationDisease?>? disease;
  String? identityId;
  String? duration;
  String? period;
  String? programId;
  String? sessionId;
  RecommendedProgramResponseRecommendationSilverAppBar? silverAppBar;

  RecommendedProgramResponseRecommendation({
    this.doctorDetails,
    this.programType,
    this.disease,
    this.identityId,
    this.duration,
    this.period,
    this.programId,
    this.sessionId,
    this.silverAppBar,
  });
  RecommendedProgramResponseRecommendation.fromJson(Map<String, dynamic> json) {
    doctorDetails = (json['doctorDetails'] != null)
        ? RecommendedProgramResponseRecommendationDoctorDetails.fromJson(
            json['doctorDetails'])
        : null;
    programType = json['programType']?.toString();
    if (json['disease'] != null) {
      final v = json['disease'];
      final arr0 = <RecommendedProgramResponseRecommendationDisease>[];
      v.forEach((v) {
        arr0.add(RecommendedProgramResponseRecommendationDisease.fromJson(v));
      });
      disease = arr0;
    }
    identityId = json['identityId']?.toString();
    duration = json['duration']?.toString();
    period = json['period']?.toString();
    programId = json['programId']?.toString();
    sessionId = json['sessionId']?.toString();
    silverAppBar = (json['silverAppBar'] != null)
        ? RecommendedProgramResponseRecommendationSilverAppBar.fromJson(
            json['silverAppBar'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (doctorDetails != null) {
      data['doctorDetails'] = doctorDetails!.toJson();
    }
    data['programType'] = programType;
    if (disease != null) {
      final v = disease;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['disease'] = arr0;
    }
    data['identityId'] = identityId;
    data['duration'] = duration;
    data['period'] = period;
    data['programId'] = programId;
    data['sessionId'] = sessionId;
    if (silverAppBar != null) {
      data['silverAppBar'] = silverAppBar!.toJson();
    }
    return data;
  }
}

class RecommendedProgramResponse {
/*
{
  "recommendation": {
    "doctorDetails": {
      "doctorName": "Dr. Aayu Expert",
      "doctorId": "8ddc36d0-fd16-11ec-86fd-5bbfc80ca82e",
      "gender": "Male",
      "photo": "",
      "profession": [
        "Doctor"
      ]
    },
    "programType": "SINGLE DISEASE",
    "disease": [
      {
        "diseaseId": "d34deb00-c21a-11ec-8195-fb3d9a5f7244",
        "diseaseName": "Diabetes"
      }
    ],
    "identityId": "da4ea560-3e26-11ed-8433-9f88b92b454d",
    "duration": "30",
    "period": "90",
    "sessionId": "4ded4c70-3e26-11ed-931d-6b8fbb69dd7e",
    "silverAppBar": {
      "title": "Anxiety Disorder Care",
      "textColor": "#FFB3B0",
      "backgroundImage": "https://stg-content.aayu.live/healing/disease.png",
      "image": {
        "imageUrl": "https://stg-content.aayu.live/healing/anxiety_icon.png",
        "height": 65,
        "width": 104
      }
    }
  }
} 
*/

  RecommendedProgramResponseRecommendation? recommendation;

  RecommendedProgramResponse({
    this.recommendation,
  });
  RecommendedProgramResponse.fromJson(Map<String, dynamic> json) {
    recommendation = (json['recommendation'] != null)
        ? RecommendedProgramResponseRecommendation.fromJson(
            json['recommendation'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (recommendation != null) {
      data['recommendation'] = recommendation!.toJson();
    }
    return data;
  }
}
