///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TrainersPastListModelLiveStatus {
/*
{
  "isLive": true,
  "isUnderMaintenance": false,
  "message": ""
} 
*/

  bool? isLive;
  bool? isUnderMaintenance;
  String? message;

  TrainersPastListModelLiveStatus({
    this.isLive,
    this.isUnderMaintenance,
    this.message,
  });
  TrainersPastListModelLiveStatus.fromJson(Map<String, dynamic> json) {
    isLive = json['isLive'];
    isUnderMaintenance = json['isUnderMaintenance'];
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isLive'] = isLive;
    data['isUnderMaintenance'] = isUnderMaintenance;
    data['message'] = message;
    return data;
  }
}

class TrainersPastListModelTrainer {
/*
{
  "trainerId": "36362500-f846-11ec-b571-6d35ec14eac1",
  "trainerName": "test trainer",
  "profilePic": "",
  "speciality": "Allopathy, Ayurveda, Counseling, Energy Medicine Therapy, 8 years Exp.",
  "desc": "vjnsjdzjnvjkjnfd dfskmvkodsfv",
  "rating": 4.1,
  "sessionFee": 0,
  "isOnline": true,
  "speaks": "English, Hindi, Marathi, Kannad",
  "sessionCount": 0,
  "level": 1,
  "epochTime": 1670518800000
} 
*/

  String? trainerId;
  String? trainerName;
  String? profilePic;
  String? speciality;
  String? desc;
  double? rating;
  int? sessionFee;
  bool? isOnline;
  String? speaks;
  int? sessionCount;
  int? level;
  int? epochTime;

  TrainersPastListModelTrainer({
    this.trainerId,
    this.trainerName,
    this.profilePic,
    this.speciality,
    this.desc,
    this.rating,
    this.sessionFee,
    this.isOnline,
    this.speaks,
    this.sessionCount,
    this.level,
    this.epochTime,
  });
  TrainersPastListModelTrainer.fromJson(Map<String, dynamic> json) {
    trainerId = json['trainerId']?.toString();
    trainerName = json['trainerName']?.toString();
    profilePic = json['profilePic']?.toString();
    speciality = json['speciality']?.toString();
    desc = json['desc']?.toString();
    rating = json['rating']?.toDouble();
    sessionFee = json['sessionFee']?.toInt();
    isOnline = json['isOnline'];
    speaks = json['speaks']?.toString();
    sessionCount = json['sessionCount']?.toInt();
    level = json['level']?.toInt();
    epochTime = json['epochTime']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['trainerId'] = trainerId;
    data['trainerName'] = trainerName;
    data['profilePic'] = profilePic;
    data['speciality'] = speciality;
    data['desc'] = desc;
    data['rating'] = rating;
    data['sessionFee'] = sessionFee;
    data['isOnline'] = isOnline;
    data['speaks'] = speaks;
    data['sessionCount'] = sessionCount;
    data['level'] = level;
    data['epochTime'] = epochTime;
    return data;
  }
}

class TrainersPastListModel {
/*
{
  "trainer": [
    {
      "trainerId": "36362500-f846-11ec-b571-6d35ec14eac1",
      "trainerName": "test trainer",
      "profilePic": "",
      "speciality": "Allopathy, Ayurveda, Counseling, Energy Medicine Therapy, 8 years Exp.",
      "desc": "vjnsjdzjnvjkjnfd dfskmvkodsfv",
      "rating": 4.1,
      "sessionFee": 0,
      "isOnline": true,
      "speaks": "English, Hindi, Marathi, Kannad",
      "sessionCount": 0,
      "level": 1,
      "epochTime": 1670518800000
    }
  ],
  "liveStatus": {
    "isLive": true,
    "isUnderMaintenance": false,
    "message": ""
  }
} 
*/

  List<TrainersPastListModelTrainer?>? trainer;
  TrainersPastListModelLiveStatus? liveStatus;

  TrainersPastListModel({
    this.trainer,
    this.liveStatus,
  });
  TrainersPastListModel.fromJson(Map<String, dynamic> json) {
    if (json['trainer'] != null) {
      final v = json['trainer'];
      final arr0 = <TrainersPastListModelTrainer>[];
      v.forEach((v) {
        arr0.add(TrainersPastListModelTrainer.fromJson(v));
      });
      trainer = arr0;
    }
    liveStatus = (json['liveStatus'] != null)
        ? TrainersPastListModelLiveStatus.fromJson(json['liveStatus'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (trainer != null) {
      final v = trainer;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['trainer'] = arr0;
    }
    if (liveStatus != null) {
      data['liveStatus'] = liveStatus!.toJson();
    }
    return data;
  }
}
