///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TrainerSessionSummaryResponseSessionsDisease {
/*
{
  "diseaseId": "9f1a5e90-c215-11ec-8195-fb3d9a5f7244"
} 
*/

  String? diseaseId;

  TrainerSessionSummaryResponseSessionsDisease({
    this.diseaseId,
  });
  TrainerSessionSummaryResponseSessionsDisease.fromJson(Map<String, dynamic> json) {
    diseaseId = json['diseaseId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['diseaseId'] = diseaseId;
    return data;
  }
}

class TrainerSessionSummaryResponseSessions {
/*
{
  "scheduledDate": "08 Dec 2022, 23:30 PM",
  "epochTime": 1670542200000,
  "status": "BOOKED",
  "trainerId": "36362500-f846-11ec-b571-6d35ec14eac1",
  "trainerName": "Dr. test trainer",
  "profilePic": "",
  "expiresOn": "",
  "disease": [
    {
      "diseaseId": "9f1a5e90-c215-11ec-8195-fb3d9a5f7244"
    }
  ],
  "callJoinLink": null,
  "consultType": "ADD-ON",
  "sessionId": "37fa9300-7616-11ed-a50a-61dfbab5d096"
} 
*/

  String? scheduledDate;
  int? epochTime;
  String? status;
  String? trainerId;
  String? trainerName;
  String? profilePic;
  String? expiresOn;
  List<TrainerSessionSummaryResponseSessionsDisease?>? disease;
  String? callJoinLink;
  String? consultType;
  String? sessionId;

  TrainerSessionSummaryResponseSessions({
    this.scheduledDate,
    this.epochTime,
    this.status,
    this.trainerId,
    this.trainerName,
    this.profilePic,
    this.expiresOn,
    this.disease,
    this.callJoinLink,
    this.consultType,
    this.sessionId,
  });
  TrainerSessionSummaryResponseSessions.fromJson(Map<String, dynamic> json) {
    scheduledDate = json['scheduledDate']?.toString();
    epochTime = json['epochTime']?.toInt();
    status = json['status']?.toString();
    trainerId = json['trainerId']?.toString();
    trainerName = json['trainerName']?.toString();
    profilePic = json['profilePic']?.toString();
    expiresOn = json['expiresOn']?.toString();
  if (json['disease'] != null) {
  final v = json['disease'];
  final arr0 = <TrainerSessionSummaryResponseSessionsDisease>[];
  v.forEach((v) {
  arr0.add(TrainerSessionSummaryResponseSessionsDisease.fromJson(v));
  });
    disease = arr0;
    }
    callJoinLink = json['callJoinLink']?.toString();
    consultType = json['consultType']?.toString();
    sessionId = json['sessionId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['scheduledDate'] = scheduledDate;
    data['epochTime'] = epochTime;
    data['status'] = status;
    data['trainerId'] = trainerId;
    data['trainerName'] = trainerName;
    data['profilePic'] = profilePic;
    data['expiresOn'] = expiresOn;
    if (disease != null) {
      final v = disease;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['disease'] = arr0;
    }
    data['callJoinLink'] = callJoinLink;
    data['consultType'] = consultType;
    data['sessionId'] = sessionId;
    return data;
  }
}

class TrainerSessionSummaryResponse {
/*
{
  "sessions": [
    {
      "scheduledDate": "08 Dec 2022, 23:30 PM",
      "epochTime": 1670542200000,
      "status": "BOOKED",
      "trainerId": "36362500-f846-11ec-b571-6d35ec14eac1",
      "trainerName": "Dr. test trainer",
      "profilePic": "",
      "expiresOn": "",
      "disease": [
        {
          "diseaseId": "9f1a5e90-c215-11ec-8195-fb3d9a5f7244"
        }
      ],
      "callJoinLink": null,
      "consultType": "ADD-ON",
      "sessionId": "37fa9300-7616-11ed-a50a-61dfbab5d096"
    }
  ]
} 
*/

  List<TrainerSessionSummaryResponseSessions?>? sessions;

  TrainerSessionSummaryResponse({
    this.sessions,
  });
  TrainerSessionSummaryResponse.fromJson(Map<String, dynamic> json) {
  if (json['sessions'] != null) {
  final v = json['sessions'];
  final arr0 = <TrainerSessionSummaryResponseSessions>[];
  v.forEach((v) {
  arr0.add(TrainerSessionSummaryResponseSessions.fromJson(v));
  });
    sessions = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (sessions != null) {
      final v = sessions;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['sessions'] = arr0;
    }
    return data;
  }
}

