///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SleepTrackerIntroPageModel {
/*
{
  "image": "assets/images/mood-tracker/mood_imag2.png",
  "title": "How does mood tracking work?",
  "subtitle": "It works brilliantly! By checking-in and tracking your mood at regular intervals, you can understand what makes you tick and what ticks you off.\n\n We can then help you understand, regulate and manage your emotions and also develop healthy coping strategies through sleep, diet and exercise."
} 
*/

  String? image;
  String? title;
  String? subtitle;

  SleepTrackerIntroPageModel({
    this.image,
    this.title,
    this.subtitle,
  });
  SleepTrackerIntroPageModel.fromJson(Map<String, dynamic> json) {
    image = json['image']?.toString();
    title = json['title']?.toString();
    subtitle = json['subtitle']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['image'] = image;
    data['title'] = title;
    data['subtitle'] = subtitle;
    return data;
  }
}
