///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SleepCheckInModelIdentifications {
/*
{
  "identificationId": "ad6ef308-d9ec-11ed-afa1-0242ac120002",
  "identification": "Too much screen usage"
} 
*/

  String? identificationId;
  String? identification;

  SleepCheckInModelIdentifications({
    this.identificationId,
    this.identification,
  });
  SleepCheckInModelIdentifications.fromJson(Map<String, dynamic> json) {
    identificationId = json['identificationId']?.toString();
    identification = json['identification']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['identificationId'] = identificationId;
    data['identification'] = identification;
    return data;
  }
}

class SleepCheckInModelSleep {
/*
{
  "sleepId": "7dc5f962-d9ec-11ed-afa1-0242ac120002",
  "sleep": "Alright",
  "icon": "assets/images/sleep-tracker/alright-icon.png"
} 
*/

  String? sleepId;
  String? sleep;
  String? icon;

  SleepCheckInModelSleep({
    this.sleepId,
    this.sleep,
    this.icon,
  });
  SleepCheckInModelSleep.fromJson(Map<String, dynamic> json) {
    sleepId = json['sleepId']?.toString();
    sleep = json['sleep']?.toString();
    icon = json['icon']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['sleepId'] = sleepId;
    data['sleep'] = sleep;
    data['icon'] = icon;
    return data;
  }
}

class SleepCheckInModel {
/*
{
  "checkInId": "96f85190-df74-11ed-b7c5-93fc8cac47a8",
  "sleep": {
    "sleepId": "7dc5f962-d9ec-11ed-afa1-0242ac120002",
    "sleep": "Alright",
    "icon": "assets/images/sleep-tracker/alright-icon.png"
  },
  "bedTime": 1682028000000,
  "wakeupTime": 1682060400000,
  "sleepHours": 9,
  "identifications": [
    {
      "identificationId": "ad6ef308-d9ec-11ed-afa1-0242ac120002",
      "identification": "Too much screen usage"
    }
  ],
  "checkInTime": 1681899144472
} 
*/

  String? checkInId;
  SleepCheckInModelSleep? sleep;
  int? bedTime;
  int? wakeupTime;
  double? sleepHours;
  List<SleepCheckInModelIdentifications?>? identifications;
  int? checkInTime;

  SleepCheckInModel({
    this.checkInId,
    this.sleep,
    this.bedTime,
    this.wakeupTime,
    this.sleepHours,
    this.identifications,
    this.checkInTime,
  });
  SleepCheckInModel.fromJson(Map<String, dynamic> json) {
    checkInId = json['checkInId']?.toString();
    sleep = (json['sleep'] != null)
        ? SleepCheckInModelSleep.fromJson(json['sleep'])
        : null;
    bedTime = json['bedTime']?.toInt();
    wakeupTime = json['wakeupTime']?.toInt();
    sleepHours = json['sleepHours']?.toDouble();
    if (json['identifications'] != null) {
      final v = json['identifications'];
      final arr0 = <SleepCheckInModelIdentifications>[];
      v.forEach((v) {
        arr0.add(SleepCheckInModelIdentifications.fromJson(v));
      });
      identifications = arr0;
    }
    checkInTime = json['checkInTime']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['checkInId'] = checkInId;
    if (sleep != null) {
      data['sleep'] = sleep!.toJson();
    }
    data['bedTime'] = bedTime;
    data['wakeupTime'] = wakeupTime;
    data['sleepHours'] = sleepHours;
    if (identifications != null) {
      final v = identifications;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['identifications'] = arr0;
    }
    data['checkInTime'] = checkInTime;
    return data;
  }
}
