// ///
// /// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
// ///
// class SleepTrackerWeeklySummaryModelSummaryDayWise {
// /*
// {
//   "completeDate": "14-03-2022",
//   "date": "14",
//   "day": "Mon",
//   "inTime": 276,
//   "outTime": 84
// } 
// */

//   String? completeDate;
//   String? date;
//   String? day;
//   int? inTime;
//   int? outTime;

//   SleepTrackerWeeklySummaryModelSummaryDayWise({
//     this.completeDate,
//     this.date,
//     this.day,
//     this.inTime,
//     this.outTime,
//   });
//   SleepTrackerWeeklySummaryModelSummaryDayWise.fromJson(
//       Map<String, dynamic> json) {
//     completeDate = json['completeDate']?.toString();
//     date = json['date']?.toString();
//     day = json['day']?.toString();
//     inTime = json['inTime']?.toInt();
//     outTime = json['outTime']?.toInt();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['completeDate'] = completeDate;
//     data['date'] = date;
//     data['day'] = day;
//     data['inTime'] = inTime;
//     data['outTime'] = outTime;
//     return data;
//   }
// }

// class SleepTrackerWeeklySummaryModelSummary {
// /*
// {
//   "week": "14 Mar - 20 Mar",
//   "dayWise": [
//     {
//       "completeDate": "14-03-2022",
//       "date": "14",
//       "day": "Mon",
//       "inTime": 276,
//       "outTime": 84
//     }
//   ]
// } 
// */

//   String? week;
//   List<SleepTrackerWeeklySummaryModelSummaryDayWise?>? dayWise;

//   SleepTrackerWeeklySummaryModelSummary({
//     this.week,
//     this.dayWise,
//   });
//   SleepTrackerWeeklySummaryModelSummary.fromJson(Map<String, dynamic> json) {
//     week = json['week']?.toString();
//     if (json['dayWise'] != null) {
//       final v = json['dayWise'];
//       final arr0 = <SleepTrackerWeeklySummaryModelSummaryDayWise>[];
//       v.forEach((v) {
//         arr0.add(SleepTrackerWeeklySummaryModelSummaryDayWise.fromJson(v));
//       });
//       dayWise = arr0;
//     }
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['week'] = week;
//     if (dayWise != null) {
//       final v = dayWise;
//       final arr0 = [];
//       v!.forEach((v) {
//         arr0.add(v!.toJson());
//       });
//       data['dayWise'] = arr0;
//     }
//     return data;
//   }
// }

// class SleepTrackerWeeklySummaryModel {
// /*
// {
//   "summary": [
//     {
//       "week": "14 Mar - 20 Mar",
//       "dayWise": [
//         {
//           "completeDate": "14-03-2022",
//           "date": "14",
//           "day": "Mon",
//           "inTime": 276,
//           "outTime": 84
//         }
//       ]
//     }
//   ]
// } 
// */

//   List<SleepTrackerWeeklySummaryModelSummary?>? summary;

//   SleepTrackerWeeklySummaryModel({
//     this.summary,
//   });
//   SleepTrackerWeeklySummaryModel.fromJson(Map<String, dynamic> json) {
//     if (json['summary'] != null) {
//       final v = json['summary'];
//       final arr0 = <SleepTrackerWeeklySummaryModelSummary>[];
//       v.forEach((v) {
//         arr0.add(SleepTrackerWeeklySummaryModelSummary.fromJson(v));
//       });
//       summary = arr0;
//     }
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     if (summary != null) {
//       final v = summary;
//       final arr0 = [];
//       v!.forEach((v) {
//         arr0.add(v!.toJson());
//       });
//       data['summary'] = arr0;
//     }
//     return data;
//   }
// }
