///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WeeklySleepCheckInModelInsightBecauseOf {
/*
{
  "identificationId": "ad6ef718-d9ec-11ed-afa1-0242ac120002",
  "identification": "Heavy food intake"
} 
*/

  String? identificationId;
  String? identification;

  WeeklySleepCheckInModelInsightBecauseOf({
    this.identificationId,
    this.identification,
  });
  WeeklySleepCheckInModelInsightBecauseOf.fromJson(Map<String, dynamic> json) {
    identificationId = json['identificationId']?.toString();
    identification = json['identification']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['identificationId'] = identificationId;
    data['identification'] = identification;
    return data;
  }
}

class WeeklySleepCheckInModelInsightAverage {
/*
{
  "bedTime": 1682031600000,
  "wakeupTime": 1681982700000,
  "sleepHours": 10.416666666666666
} 
*/

  int? bedTime;
  int? wakeupTime;
  double? sleepHours;

  WeeklySleepCheckInModelInsightAverage({
    this.bedTime,
    this.wakeupTime,
    this.sleepHours,
  });
  WeeklySleepCheckInModelInsightAverage.fromJson(Map<String, dynamic> json) {
    bedTime = json['bedTime']?.toInt();
    wakeupTime = json['wakeupTime']?.toInt();
    sleepHours = json['sleepHours']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bedTime'] = bedTime;
    data['wakeupTime'] = wakeupTime;
    data['sleepHours'] = sleepHours;
    return data;
  }
}

class WeeklySleepCheckInModelInsightSleepQuality {
/*
{
  "sleepId": "7dc5f962-d9ec-11ed-afa1-0242ac120002",
  "sleep": "Alright",
  "icon": "assets/images/sleep-tracker/alright-icon.png"
} 
*/

  String? sleepId;
  String? sleep;
  String? icon;

  WeeklySleepCheckInModelInsightSleepQuality({
    this.sleepId,
    this.sleep,
    this.icon,
  });
  WeeklySleepCheckInModelInsightSleepQuality.fromJson(
      Map<String, dynamic> json) {
    sleepId = json['sleepId']?.toString();
    sleep = json['sleep']?.toString();
    icon = json['icon']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['sleepId'] = sleepId;
    data['sleep'] = sleep;
    data['icon'] = icon;
    return data;
  }
}

class WeeklySleepCheckInModelInsight {
/*
{
  "sleepQuality": {
    "sleepId": "7dc5f962-d9ec-11ed-afa1-0242ac120002",
    "sleep": "Alright",
    "icon": "assets/images/sleep-tracker/alright-icon.png"
  },
  "average": {
    "bedTime": 1682031600000,
    "wakeupTime": 1681982700000,
    "sleepHours": 10.416666666666666
  },
  "becauseOf": [
    {
      "identificationId": "ad6ef718-d9ec-11ed-afa1-0242ac120002",
      "identification": "Heavy food intake"
    }
  ]
} 
*/

  WeeklySleepCheckInModelInsightSleepQuality? sleepQuality;
  WeeklySleepCheckInModelInsightAverage? average;
  List<WeeklySleepCheckInModelInsightBecauseOf?>? becauseOf;

  WeeklySleepCheckInModelInsight({
    this.sleepQuality,
    this.average,
    this.becauseOf,
  });
  WeeklySleepCheckInModelInsight.fromJson(Map<String, dynamic> json) {
    sleepQuality = (json['sleepQuality'] != null)
        ? WeeklySleepCheckInModelInsightSleepQuality.fromJson(
            json['sleepQuality'])
        : null;
    average = (json['average'] != null)
        ? WeeklySleepCheckInModelInsightAverage.fromJson(json['average'])
        : null;
    if (json['becauseOf'] != null) {
      final v = json['becauseOf'];
      final arr0 = <WeeklySleepCheckInModelInsightBecauseOf>[];
      v.forEach((v) {
        arr0.add(WeeklySleepCheckInModelInsightBecauseOf.fromJson(v));
      });
      becauseOf = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (sleepQuality != null) {
      data['sleepQuality'] = sleepQuality!.toJson();
    }
    if (average != null) {
      data['average'] = average!.toJson();
    }
    if (becauseOf != null) {
      final v = becauseOf;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['becauseOf'] = arr0;
    }
    return data;
  }
}

class WeeklySleepCheckInModelDayWiseCheckIns {
/*
{
  "checkInDate": 1681948800000,
  "bedTime": 1682031600000,
  "wakeupTime": 1682069100000,
  "sleepHours": 10.416666666666666
} 
*/

  DateTime? checkInDate;
  int? bedTime;
  int? wakeupTime;
  double? sleepHours;

  WeeklySleepCheckInModelDayWiseCheckIns({
    this.checkInDate,
    this.bedTime,
    this.wakeupTime,
    this.sleepHours,
  });
  WeeklySleepCheckInModelDayWiseCheckIns.fromJson(Map<String, dynamic> json) {
    checkInDate =
        DateTime.fromMillisecondsSinceEpoch(json['checkInDate']?.toInt());
    bedTime = json['bedTime']?.toInt();
    wakeupTime = json['wakeupTime']?.toInt();
    sleepHours = json['sleepHours']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['checkInDate'] = checkInDate!.millisecondsSinceEpoch;
    data['bedTime'] = bedTime;
    data['wakeupTime'] = wakeupTime;
    data['sleepHours'] = sleepHours;
    return data;
  }
}

class WeeklySleepCheckInModel {
/*
{
  "dayWiseCheckIns": [
    {
      "checkInDate": 1681948800000,
      "bedTime": 1682031600000,
      "wakeupTime": 1682069100000,
      "sleepHours": 10.416666666666666
    }
  ],
  "insight": {
    "sleepQuality": {
      "sleepId": "7dc5f962-d9ec-11ed-afa1-0242ac120002",
      "sleep": "Alright",
      "icon": "assets/images/sleep-tracker/alright-icon.png"
    },
    "average": {
      "bedTime": 1682031600000,
      "wakeupTime": 1681982700000,
      "sleepHours": 10.416666666666666
    },
    "becauseOf": [
      {
        "identificationId": "ad6ef718-d9ec-11ed-afa1-0242ac120002",
        "identification": "Heavy food intake"
      }
    ]
  }
} 
*/

  List<WeeklySleepCheckInModelDayWiseCheckIns?>? dayWiseCheckIns;
  WeeklySleepCheckInModelInsight? insight;

  WeeklySleepCheckInModel({
    this.dayWiseCheckIns,
    this.insight,
  });
  WeeklySleepCheckInModel.fromJson(Map<String, dynamic> json) {
    if (json['dayWiseCheckIns'] != null) {
      final v = json['dayWiseCheckIns'];
      final arr0 = <WeeklySleepCheckInModelDayWiseCheckIns>[];
      v.forEach((v) {
        arr0.add(WeeklySleepCheckInModelDayWiseCheckIns.fromJson(v));
      });
      dayWiseCheckIns = arr0;
    }
    insight = (json['insight'] != null)
        ? WeeklySleepCheckInModelInsight.fromJson(json['insight'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (dayWiseCheckIns != null) {
      final v = dayWiseCheckIns;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['dayWiseCheckIns'] = arr0;
    }
    if (insight != null) {
      data['insight'] = insight!.toJson();
    }
    return data;
  }
}
