///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PsychologyRandomJournalModelJournal {
/*
{
  "journalId": "060fab90-f97a-11ed-b060-3dc5aabd89be",
  "journal": "What are three things you are grateful for today? - 4"
} 
*/

  String? journalId;
  String? journal;

  PsychologyRandomJournalModelJournal({
    this.journalId,
    this.journal,
  });
  PsychologyRandomJournalModelJournal.fromJson(Map<String, dynamic> json) {
    journalId = json['journalId']?.toString();
    journal = json['journal']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['journalId'] = journalId;
    data['journal'] = journal;
    return data;
  }
}

class PsychologyRandomJournalModel {
/*
{
  "journal": {
    "journalId": "060fab90-f97a-11ed-b060-3dc5aabd89be",
    "journal": "What are three things you are grateful for today? - 4"
  }
} 
*/

  PsychologyRandomJournalModelJournal? journal;

  PsychologyRandomJournalModel({
    this.journal,
  });
  PsychologyRandomJournalModel.fromJson(Map<String, dynamic> json) {
    journal = (json['journal'] != null) ? PsychologyRandomJournalModelJournal.fromJson(json['journal']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (journal != null) {
      data['journal'] = journal!.toJson();
    }
    return data;
  }
}
