///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PsychologyStartingPlansModelPackagesCurrency {
/*
{
  "display": "₹",
  "billing": "INR"
} 
*/

  String? display;
  String? billing;

  PsychologyStartingPlansModelPackagesCurrency({
    this.display,
    this.billing,
  });
  PsychologyStartingPlansModelPackagesCurrency.fromJson(
      Map<String, dynamic> json) {
    display = json['display']?.toString();
    billing = json['billing']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['display'] = display;
    data['billing'] = billing;
    return data;
  }
}

class PsychologyStartingPlansModelPackages {
/*
{
  "packageId": "e11a8790-d793-11ed-aebc-b5392c20a7dc",
  "packageName": "FIRST_TIME_BASIC_4_WEEKS_SESSION_1",
  "displayText": "4 Weeks",
  "packageType": "BASIC",
  "purchaseType": "FIRST TIME",
  "duration": "4 Weeks",
  "purchaseAmount": 475,
  "currency": {
    "display": "₹",
    "billing": "INR"
  }
} 
*/

  String? packageId;
  String? packageName;
  String? displayText;
  String? packageType;
  String? purchaseType;
  String? duration;
  int? purchaseAmount;
  PsychologyStartingPlansModelPackagesCurrency? currency;

  PsychologyStartingPlansModelPackages({
    this.packageId,
    this.packageName,
    this.displayText,
    this.packageType,
    this.purchaseType,
    this.duration,
    this.purchaseAmount,
    this.currency,
  });
  PsychologyStartingPlansModelPackages.fromJson(Map<String, dynamic> json) {
    packageId = json['packageId']?.toString();
    packageName = json['packageName']?.toString();
    displayText = json['displayText']?.toString();
    packageType = json['packageType']?.toString();
    purchaseType = json['purchaseType']?.toString();
    duration = json['duration']?.toString();
    purchaseAmount = json['purchaseAmount']?.toInt();
    currency = (json['currency'] != null)
        ? PsychologyStartingPlansModelPackagesCurrency.fromJson(
            json['currency'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['packageId'] = packageId;
    data['packageName'] = packageName;
    data['displayText'] = displayText;
    data['packageType'] = packageType;
    data['purchaseType'] = purchaseType;
    data['duration'] = duration;
    data['purchaseAmount'] = purchaseAmount;
    if (currency != null) {
      data['currency'] = currency!.toJson();
    }
    return data;
  }
}

class PsychologyStartingPlansModel {
/*
{
  "isBillingAllowed": true,
  "packages": [
    {
      "packageId": "e11a8790-d793-11ed-aebc-b5392c20a7dc",
      "packageName": "FIRST_TIME_BASIC_4_WEEKS_SESSION_1",
      "displayText": "4 Weeks",
      "packageType": "BASIC",
      "purchaseType": "FIRST TIME",
      "duration": "4 Weeks",
      "purchaseAmount": 475,
      "currency": {
        "display": "₹",
        "billing": "INR"
      }
    }
  ]
} 
*/

  bool? isBillingAllowed;
  List<PsychologyStartingPlansModelPackages?>? packages;

  PsychologyStartingPlansModel({
    this.isBillingAllowed,
    this.packages,
  });
  PsychologyStartingPlansModel.fromJson(Map<String, dynamic> json) {
    isBillingAllowed = json['isBillingAllowed'];
    if (json['packages'] != null) {
      final v = json['packages'];
      final arr0 = <PsychologyStartingPlansModelPackages>[];
      v.forEach((v) {
        arr0.add(PsychologyStartingPlansModelPackages.fromJson(v));
      });
      packages = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isBillingAllowed'] = isBillingAllowed;
    if (packages != null) {
      final v = packages;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['packages'] = arr0;
    }
    return data;
  }
}
