///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OptionsModel {
/*
{
  "text": "",
  "selected": false
} 
*/

  String text = "";
  bool selected = false;

  OptionsModel({
    required this.text,
    required this.selected,
  });
  OptionsModel.fromJson(Map<String, dynamic> json) {
    text = json['text'];
    selected = json['selected'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['text'] = text;
    data['selected'] = selected;
    return data;
  }
}
