///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserDetailsResponseUserDetailsLocation {
/*
{
  "country": "India",
  "state": "Maharashtra",
  "city": "Mumbai",
  "pinCode": "400067"
} 
*/

  String? country;
  String? state;
  String? city;
  String? pinCode;

  UserDetailsResponseUserDetailsLocation({
    this.country,
    this.state,
    this.city,
    this.pinCode,
  });
  UserDetailsResponseUserDetailsLocation.fromJson(Map<String, dynamic> json) {
    country = json['country']?.toString();
    state = json['state']?.toString();
    city = json['city']?.toString();
    pinCode = json['pinCode']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['state'] = state;
    data['city'] = city;
    data['pinCode'] = pinCode;
    return data;
  }
}

class UserDetailsResponseUserDetailsSocialNetwork {
/*
{
  "network": "Facebook",
  "socialId": "1234567890",
  "profilePic": ""
} 
*/

  String? network;
  String? socialId;
  String? profilePic;

  UserDetailsResponseUserDetailsSocialNetwork({
    this.network,
    this.socialId,
    this.profilePic,
  });
  UserDetailsResponseUserDetailsSocialNetwork.fromJson(Map<String, dynamic> json) {
    network = json['network']?.toString();
    socialId = json['socialId']?.toString();
    profilePic = json['profilePic']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['network'] = network;
    data['socialId'] = socialId;
    data['profilePic'] = profilePic;
    return data;
  }
}

class UserDetailsResponseUserDetails {
/*
{
  "userId": "b3c19280-9468-11ec-8a40-6bdca23f9e37",
  "firebaseUId": "RchpY3hDthOzxdumvewhIKaUeKF2",
  "firstName": "Mahesh",
  "lastName": "Karande",
  "mobileNumber": "919930104412",
  "emailId": "",
  "profilePic": "",
  "gender": "Male",
  "dob": "27-11-1985",
  "isFirstTime": true,
  "isOnboard": true,
  "status": "",
  "createdAt": "2022-02-23T05:23:15.498Z",
  "lastVisitAt": "2022-02-26T07:27:47.227Z",
  "socialNetwork": [
    {
      "network": "Facebook",
      "socialId": "1234567890",
      "profilePic": ""
    }
  ],
  "location": [
    {
      "country": "India",
      "state": "Maharashtra",
      "city": "Mumbai",
      "pinCode": "400067"
    }
  ]
} 
*/

  String? userId;
  String? firebaseUId;
  String? firstName;
  String? lastName;
  String? mobileNumber;
  String? emailId;
  String? profilePic;
  String? gender;
  String? dob;
  bool? isFirstTime;
  bool? isOnboard;
  String? status;
  String? createdAt;
  String? lastVisitAt;
  List<UserDetailsResponseUserDetailsSocialNetwork?>? socialNetwork;
  List<UserDetailsResponseUserDetailsLocation?>? location;

  UserDetailsResponseUserDetails({
    this.userId,
    this.firebaseUId,
    this.firstName,
    this.lastName,
    this.mobileNumber,
    this.emailId,
    this.profilePic,
    this.gender,
    this.dob,
    this.isFirstTime,
    this.isOnboard,
    this.status,
    this.createdAt,
    this.lastVisitAt,
    this.socialNetwork,
    this.location,
  });
  UserDetailsResponseUserDetails.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toString();
    firebaseUId = json['firebaseUId']?.toString();
    firstName = json['firstName']?.toString();
    lastName = json['lastName']?.toString();
    mobileNumber = json['mobileNumber']?.toString();
    emailId = json['emailId']?.toString();
    profilePic = json['profilePic']?.toString();
    gender = json['gender']?.toString();
    dob = json['dob']?.toString();
    isFirstTime = json['isFirstTime'];
    isOnboard = json['isOnboard'];
    status = json['status']?.toString();
    createdAt = json['createdAt']?.toString();
    lastVisitAt = json['lastVisitAt']?.toString();
  if (json['socialNetwork'] != null) {
  final v = json['socialNetwork'];
  final arr0 = <UserDetailsResponseUserDetailsSocialNetwork>[];
  v.forEach((v) {
  arr0.add(UserDetailsResponseUserDetailsSocialNetwork.fromJson(v));
  });
    socialNetwork = arr0;
    }
  if (json['location'] != null) {
  final v = json['location'];
  final arr0 = <UserDetailsResponseUserDetailsLocation>[];
  v.forEach((v) {
  arr0.add(UserDetailsResponseUserDetailsLocation.fromJson(v));
  });
    location = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['firebaseUId'] = firebaseUId;
    data['firstName'] = firstName;
    data['lastName'] = lastName;
    data['mobileNumber'] = mobileNumber;
    data['emailId'] = emailId;
    data['profilePic'] = profilePic;
    data['gender'] = gender;
    data['dob'] = dob;
    data['isFirstTime'] = isFirstTime;
    data['isOnboard'] = isOnboard;
    data['status'] = status;
    data['createdAt'] = createdAt;
    data['lastVisitAt'] = lastVisitAt;
    if (socialNetwork != null) {
      final v = socialNetwork;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['socialNetwork'] = arr0;
    }
    if (location != null) {
      final v = location;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['location'] = arr0;
    }
    return data;
  }
}

class UserDetailsResponse {
/*
{
  "userDetails": {
    "userId": "b3c19280-9468-11ec-8a40-6bdca23f9e37",
    "firebaseUId": "RchpY3hDthOzxdumvewhIKaUeKF2",
    "firstName": "Mahesh",
    "lastName": "Karande",
    "mobileNumber": "919930104412",
    "emailId": "",
    "profilePic": "",
    "gender": "Male",
    "dob": "27-11-1985",
    "isFirstTime": true,
    "isOnboard": true,
    "status": "",
    "createdAt": "2022-02-23T05:23:15.498Z",
    "lastVisitAt": "2022-02-26T07:27:47.227Z",
    "socialNetwork": [
      {
        "network": "Facebook",
        "socialId": "1234567890",
        "profilePic": ""
      }
    ],
    "location": [
      {
        "country": "India",
        "state": "Maharashtra",
        "city": "Mumbai",
        "pinCode": "400067"
      }
    ]
  }
} 
*/

  UserDetailsResponseUserDetails? userDetails;

  UserDetailsResponse({
    this.userDetails,
  });
  UserDetailsResponse.fromJson(Map<String, dynamic> json) {
    userDetails = (json['userDetails'] != null) ? UserDetailsResponseUserDetails.fromJson(json['userDetails']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (userDetails != null) {
      data['userDetails'] = userDetails!.toJson();
    }
    return data;
  }
}
