///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserHealthTrackingModelHealthTracking {
/*
{
  "trackerId": "9fe41ea0-c1a7-11ed-bc51-61aefd6f2c1c",
  "onDate": 1678665600000,
  "parameter": "WEIGHT",
  "value": 72.1,
  "unit": "KG",
  "source": "Manual"
} 
*/

  String? trackerId;
  int? onDate;
  String? parameter;
  String? value;
  String? unit;
  String? source;

  UserHealthTrackingModelHealthTracking({
    this.trackerId,
    this.onDate,
    this.parameter,
    this.value,
    this.unit,
    this.source,
  });
  UserHealthTrackingModelHealthTracking.fromJson(Map<String, dynamic> json) {
    trackerId = json['trackerId']?.toString();
    onDate = json['onDate']?.toInt();
    parameter = json['parameter']?.toString();
    value = json['value']?.toString();
    unit = json['unit']?.toString();
    source = json['source']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['trackerId'] = trackerId;
    data['onDate'] = onDate;
    data['parameter'] = parameter;
    data['value'] = value;
    data['unit'] = unit;
    data['source'] = source;
    return data;
  }
}

class UserHealthTrackingModel {
/*
{
  "healthTracking": [
    {
      "trackerId": "9fe41ea0-c1a7-11ed-bc51-61aefd6f2c1c",
      "onDate": 1678665600000,
      "parameter": "WEIGHT",
      "value": 72.1,
      "unit": "KG",
      "source": "Manual"
    }
  ]
} 
*/

  List<UserHealthTrackingModelHealthTracking?>? healthTracking;

  UserHealthTrackingModel({
    this.healthTracking,
  });
  UserHealthTrackingModel.fromJson(Map<String, dynamic> json) {
  if (json['healthTracking'] != null) {
  final v = json['healthTracking'];
  final arr0 = <UserHealthTrackingModelHealthTracking>[];
  v.forEach((v) {
  arr0.add(UserHealthTrackingModelHealthTracking.fromJson(v));
  });
    healthTracking = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (healthTracking != null) {
      final v = healthTracking;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['healthTracking'] = arr0;
    }
    return data;
  }
}
