import '../grow/grow.page.content.model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class SearchRecomendationModelTags {
/*
{
  "enabled": true,
  "maxSelect": 3,
  "title": "Tags",
  "items": [
    {
      "displayTagId": "5",
      "displayTag": "Begineer"
    }
  ]
} 
*/

  bool? enabled;
  int? maxSelect;
  String? title;
  List<ContentMetaDataTags?>? items;

  SearchRecomendationModelTags({
    this.enabled,
    this.maxSelect,
    this.title,
    this.items,
  });
  SearchRecomendationModelTags.fromJson(Map<String, dynamic> json) {
    enabled = json['enabled'];
    maxSelect = json['maxSelect']?.toInt();
    title = json['title']?.toString();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <ContentMetaDataTags>[];
      v.forEach((v) {
        arr0.add(ContentMetaDataTags.fromJson(v));
      });
      items = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['enabled'] = enabled;
    data['maxSelect'] = maxSelect;
    data['title'] = title;
    if (items != null) {
      final v = items;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['items'] = arr0;
    }
    return data;
  }
}

class SearchRecomendationModelContentDurationItems {
/*
{
  "duration": 5,
  "compare": "EXACT",
  "type": "Min"
} 
*/

  int? duration;
  String? compare;
  String? type;

  SearchRecomendationModelContentDurationItems({
    this.duration,
    this.compare,
    this.type,
  });
  SearchRecomendationModelContentDurationItems.fromJson(
      Map<String, dynamic> json) {
    duration = json['duration']?.toInt();
    compare = json['compare']?.toString();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['duration'] = duration;
    data['compare'] = compare;
    data['type'] = type;
    return data;
  }
}

class SearchRecomendationModelContentDuration {
/*
{
  "enabled": true,
  "maxSelect": 1,
  "title": "Duration",
  "items": [
    {
      "duration": 5,
      "compare": "EXACT",
      "type": "Min"
    }
  ]
} 
*/

  bool? enabled;
  int? maxSelect;
  String? title;
  List<SearchRecomendationModelContentDurationItems?>? items;

  SearchRecomendationModelContentDuration({
    this.enabled,
    this.maxSelect,
    this.title,
    this.items,
  });
  SearchRecomendationModelContentDuration.fromJson(Map<String, dynamic> json) {
    enabled = json['enabled'];
    maxSelect = json['maxSelect']?.toInt();
    title = json['title']?.toString();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <SearchRecomendationModelContentDurationItems>[];
      v.forEach((v) {
        arr0.add(SearchRecomendationModelContentDurationItems.fromJson(v));
      });
      items = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['enabled'] = enabled;
    data['maxSelect'] = maxSelect;
    data['title'] = title;
    if (items != null) {
      final v = items;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['items'] = arr0;
    }
    return data;
  }
}

class SearchRecomendationModelContentTypesItems {
/*
{
  "contentType": "AUDIO",
  "displayText": "Audio"
} 
*/

  String? contentType;
  String? displayText;

  SearchRecomendationModelContentTypesItems({
    this.contentType,
    this.displayText,
  });
  SearchRecomendationModelContentTypesItems.fromJson(
      Map<String, dynamic> json) {
    contentType = json['contentType']?.toString();
    displayText = json['displayText']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['contentType'] = contentType;
    data['displayText'] = displayText;
    return data;
  }
}

class SearchRecomendationModelContentTypes {
/*
{
  "enabled": true,
  "maxSelect": 3,
  "title": "Types",
  "items": [
    {
      "contentType": "AUDIO",
      "displayText": "Audio"
    }
  ]
} 
*/

  bool? enabled;
  int? maxSelect;
  String? title;
  List<SearchRecomendationModelContentTypesItems?>? items;

  SearchRecomendationModelContentTypes({
    this.enabled,
    this.maxSelect,
    this.title,
    this.items,
  });
  SearchRecomendationModelContentTypes.fromJson(Map<String, dynamic> json) {
    enabled = json['enabled'];
    maxSelect = json['maxSelect']?.toInt();
    title = json['title']?.toString();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <SearchRecomendationModelContentTypesItems>[];
      v.forEach((v) {
        arr0.add(SearchRecomendationModelContentTypesItems.fromJson(v));
      });
      items = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['enabled'] = enabled;
    data['maxSelect'] = maxSelect;
    data['title'] = title;
    if (items != null) {
      final v = items;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['items'] = arr0;
    }
    return data;
  }
}

class SearchRecomendationModel {
/*
{
  "contentTypes": {
    "enabled": true,
    "maxSelect": 3,
    "title": "Types",
    "items": [
      {
        "contentType": "AUDIO",
        "displayText": "Audio"
      }
    ]
  },
  "contentDuration": {
    "enabled": true,
    "maxSelect": 1,
    "title": "Duration",
    "items": [
      {
        "duration": 5,
        "compare": "EXACT",
        "type": "Min"
      }
    ]
  },
  "tags": {
    "enabled": true,
    "maxSelect": 3,
    "title": "Tags",
    "items": [
      {
        "displayTagId": "5",
        "displayText": "Begineer"
      }
    ]
  }
} 
*/

  SearchRecomendationModelContentTypes? contentTypes;
  SearchRecomendationModelContentDuration? contentDuration;
  SearchRecomendationModelTags? tags;

  SearchRecomendationModel({
    this.contentTypes,
    this.contentDuration,
    this.tags,
  });
  SearchRecomendationModel.fromJson(Map<String, dynamic> json) {
    contentTypes = (json['contentTypes'] != null)
        ? SearchRecomendationModelContentTypes.fromJson(json['contentTypes'])
        : null;
    contentDuration = (json['contentDuration'] != null)
        ? SearchRecomendationModelContentDuration.fromJson(
            json['contentDuration'])
        : null;
    tags = (json['tags'] != null)
        ? SearchRecomendationModelTags.fromJson(json['tags'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (contentTypes != null) {
      data['contentTypes'] = contentTypes!.toJson();
    }
    if (contentDuration != null) {
      data['contentDuration'] = contentDuration!.toJson();
    }
    if (tags != null) {
      data['tags'] = tags!.toJson();
    }
    return data;
  }
}
