///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ActivationCodeVailidateModelActivationCodeWhatYouGet {
/*
{
  "title": "",
  "desc": [
    "Welcome"
  ]
} 
*/

  String? title;
  List<String?>? desc;

  ActivationCodeVailidateModelActivationCodeWhatYouGet({
    this.title,
    this.desc,
  });
  ActivationCodeVailidateModelActivationCodeWhatYouGet.fromJson(
      Map<String, dynamic> json) {
    title = json['title']?.toString();
    if (json['desc'] != null && (json['desc'] is List)) {
      final v = json['desc'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      desc = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    if (desc != null) {
      final v = desc;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['desc'] = arr0;
    }
    return data;
  }
}

class ActivationCodeVailidateModelActivationCode {
/*
{
  "activationCode": "50L-J5T-62Q",
  "usedFor": "SUBSCRIPTION",
  "source": "AMAZON",
  "referenceId": "456789",
  "status": "ACTIVE",
  "activationCodeId": "90ab7f12-ceee-11ed-ab85-5703c0beeb8d",
  "whatYouGet": {
    "title": "",
    "desc": [
      "Welcome"
    ]
  }
} 
*/

  String? activationCode;
  String? usedFor;
  String? source;
  String? referenceId;
  String? status;
  String? activationCodeId;
  ActivationCodeVailidateModelActivationCodeWhatYouGet? whatYouGet;

  ActivationCodeVailidateModelActivationCode({
    this.activationCode,
    this.usedFor,
    this.source,
    this.referenceId,
    this.status,
    this.activationCodeId,
    this.whatYouGet,
  });
  ActivationCodeVailidateModelActivationCode.fromJson(
      Map<String, dynamic> json) {
    activationCode = json['activationCode']?.toString();
    usedFor = json['usedFor']?.toString();
    source = json['source']?.toString();
    referenceId = json['referenceId']?.toString();
    status = json['status']?.toString();
    activationCodeId = json['activationCodeId']?.toString();
    whatYouGet = (json['whatYouGet'] != null && (json['whatYouGet'] is Map))
        ? ActivationCodeVailidateModelActivationCodeWhatYouGet.fromJson(
            json['whatYouGet'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['activationCode'] = activationCode;
    data['usedFor'] = usedFor;
    data['source'] = source;
    data['referenceId'] = referenceId;
    data['status'] = status;
    data['activationCodeId'] = activationCodeId;
    if (whatYouGet != null) {
      data['whatYouGet'] = whatYouGet!.toJson();
    }
    return data;
  }
}

class ActivationCodeVailidateModel {
/*
{
  "activationCode": {
    "activationCode": "50L-J5T-62Q",
    "usedFor": "SUBSCRIPTION",
    "source": "AMAZON",
    "referenceId": "456789",
    "status": "ACTIVE",
    "activationCodeId": "90ab7f12-ceee-11ed-ab85-5703c0beeb8d",
    "whatYouGet": {
      "title": "",
      "desc": [
        "Welcome"
      ]
    }
  }
} 
*/

  ActivationCodeVailidateModelActivationCode? activationCode;

  ActivationCodeVailidateModel({
    this.activationCode,
  });
  ActivationCodeVailidateModel.fromJson(Map<String, dynamic> json) {
    activationCode =
        (json['activationCode'] != null && (json['activationCode'] is Map))
            ? ActivationCodeVailidateModelActivationCode.fromJson(
                json['activationCode'])
            : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (activationCode != null) {
      data['activationCode'] = activationCode!.toJson();
    }
    return data;
  }
}
