///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SpecialOfferModelOfferDetailsCountries {
/*
{
  "country": "IN",
  "discount": 20,
  "maxCount": 1
} 
*/

  String? country;
  double? discount;
  int? maxCount;

  SpecialOfferModelOfferDetailsCountries({
    this.country,
    this.discount,
    this.maxCount,
  });
  SpecialOfferModelOfferDetailsCountries.fromJson(Map<String, dynamic> json) {
    country = json['country']?.toString();
    discount = json['discount']?.toDouble();
    maxCount = json['maxCount']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['discount'] = discount;
    data['maxCount'] = maxCount;
    return data;
  }
}

class SpecialOfferModelOfferDetailsRepeat {
/*
{
  "duration": "DAY",
  "value": 1
} 
*/

  String? duration;
  int? value;

  SpecialOfferModelOfferDetailsRepeat({
    this.duration,
    this.value,
  });
  SpecialOfferModelOfferDetailsRepeat.fromJson(Map<String, dynamic> json) {
    duration = json['duration']?.toString();
    value = json['value']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['duration'] = duration;
    data['value'] = value;
    return data;
  }
}

class SpecialOfferModelOfferDetails {
/*
{
  "repeat": {
    "duration": "DAY",
    "value": 1
  },
  "source": "PAYMENT FAILURE",
  "offerOn": "SUBSCRIPTION",
  "title": "Savings opportunity",
  "desc": "Just for YOU",
  "discountOn": "SAME PACKAGE",
  "theme": "green",
  "status": "ACTIVE",
  "countries": [
    {
      "country": "IN",
      "discount": 20,
      "maxCount": 1
    }
  ],
  "specialOfferId": "242b1920-e4f8-11ed-a42f-2928977d2512"
} 
*/

  SpecialOfferModelOfferDetailsRepeat? repeat;
  String? source;
  String? offerOn;
  String? title;
  String? desc;
  String? discountOn;
  String? theme;
  String? status;
  List<SpecialOfferModelOfferDetailsCountries?>? countries;
  String? specialOfferId;

  SpecialOfferModelOfferDetails({
    this.repeat,
    this.source,
    this.offerOn,
    this.title,
    this.desc,
    this.discountOn,
    this.theme,
    this.status,
    this.countries,
    this.specialOfferId,
  });
  SpecialOfferModelOfferDetails.fromJson(Map<String, dynamic> json) {
    repeat = (json['repeat'] != null)
        ? SpecialOfferModelOfferDetailsRepeat.fromJson(json['repeat'])
        : null;
    source = json['source']?.toString();
    offerOn = json['offerOn']?.toString();
    title = json['title']?.toString();
    desc = json['desc']?.toString();
    discountOn = json['discountOn']?.toString();
    theme = json['theme']?.toString();
    status = json['status']?.toString();
    if (json['countries'] != null) {
      final v = json['countries'];
      final arr0 = <SpecialOfferModelOfferDetailsCountries>[];
      v.forEach((v) {
        arr0.add(SpecialOfferModelOfferDetailsCountries.fromJson(v));
      });
      countries = arr0;
    }
    specialOfferId = json['specialOfferId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (repeat != null) {
      data['repeat'] = repeat!.toJson();
    }
    data['source'] = source;
    data['offerOn'] = offerOn;
    data['title'] = title;
    data['desc'] = desc;
    data['discountOn'] = discountOn;
    data['theme'] = theme;
    data['status'] = status;
    if (countries != null) {
      final v = countries;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['countries'] = arr0;
    }
    data['specialOfferId'] = specialOfferId;
    return data;
  }
}

class SpecialOfferModel {
/*
{
  "offerDetails": {
    "repeat": {
      "duration": "DAY",
      "value": 1
    },
    "source": "PAYMENT FAILURE",
    "offerOn": "SUBSCRIPTION",
    "title": "Savings opportunity",
    "desc": "Just for YOU",
    "discountOn": "SAME PACKAGE",
    "theme": "green",
    "status": "ACTIVE",
    "countries": [
      {
        "country": "IN",
        "discount": 20,
        "maxCount": 1
      }
    ],
    "specialOfferId": "242b1920-e4f8-11ed-a42f-2928977d2512"
  }
} 
*/

  SpecialOfferModelOfferDetails? offerDetails;

  SpecialOfferModel({
    this.offerDetails,
  });
  SpecialOfferModel.fromJson(Map<String, dynamic> json) {
    offerDetails = (json['offerDetails'] != null)
        ? SpecialOfferModelOfferDetails.fromJson(json['offerDetails'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (offerDetails != null) {
      data['offerDetails'] = offerDetails!.toJson();
    }
    return data;
  }
}
