///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ContentReviewsModelReviews {
/*
{
  "userId": "f317ea50-98a5-11ed-870a-698e4e82c604",
  "comments": "Nice content!",
  "createdAt": "2023-01-23T07:13:38.315Z",
  "rating": 3,
  "ratingId": "753c5bd0-9aed-11ed-ba7b-f9d943e11994",
  "userName": "Mahesh",
  "profilePhoto": "",
  "gender": "Male"
} 
*/

  String? userId;
  String? comments;
  int? createdAt;
  int? rating;
  String? ratingId;
  String? userName;
  String? profilePhoto;
  String? gender;

  ContentReviewsModelReviews({
    this.userId,
    this.comments,
    this.createdAt,
    this.rating,
    this.ratingId,
    this.userName,
    this.profilePhoto,
    this.gender,
  });
  ContentReviewsModelReviews.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toString();
    comments = json['comments']?.toString();
    createdAt = json['createdAt']?.toInt();
    rating = json['rating']?.toInt();
    ratingId = json['ratingId']?.toString();
    userName = json['userName']?.toString();
    profilePhoto = json['profilePhoto']?.toString();
    gender = json['gender']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['comments'] = comments;
    data['createdAt'] = createdAt;
    data['rating'] = rating;
    data['ratingId'] = ratingId;
    data['userName'] = userName;
    data['profilePhoto'] = profilePhoto;
    data['gender'] = gender;
    return data;
  }
}

class ContentReviewsModel {
/*
{
  "reviews": [
    {
      "userId": "f317ea50-98a5-11ed-870a-698e4e82c604",
      "comments": "Nice content!",
      "createdAt": "2023-01-23T07:13:38.315Z",
      "rating": 3,
      "ratingId": "753c5bd0-9aed-11ed-ba7b-f9d943e11994",
      "userName": "Mahesh",
      "profilePhoto": "",
      "gender": "Male"
    }
  ]
} 
*/

  List<ContentReviewsModelReviews?>? reviews;

  ContentReviewsModel({
    this.reviews,
  });
  ContentReviewsModel.fromJson(Map<String, dynamic> json) {
  if (json['reviews'] != null) {
  final v = json['reviews'];
  final arr0 = <ContentReviewsModelReviews>[];
  v.forEach((v) {
  arr0.add(ContentReviewsModelReviews.fromJson(v));
  });
    reviews = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (reviews != null) {
      final v = reviews;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['reviews'] = arr0;
    }
    return data;
  }
}
