import 'package:aayu/model/grow/grow.page.content.model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FavouritesContentResponseContent {
/*
{
  "grow": [
    {
      "contentId": "ede9c55a-b21a-40bc-88cd-32f0a3e3e94c",
      "contentName": "Affectionate Breathing - Self Love Meditation",
      "contentImage": "https://stg-content.aayu.live/Relationship/finalcontent/AffectionateBreathingSelfLoveMeditation/AffectionateBreathingSelfLoveMeditation_750x554.jpg",
      "contentType": "Audio",
      "contentPath": "https://stg-content.aayu.live/Relationship/finalcontent/AffectionateBreathingSelfLoveMeditation/AffectionateBreathingSelfLoveMeditation.mp3",
      "playBGImage": "https://stg-content.aayu.live/Relationship/finalcontent/AffectionateBreathingSelfLoveMeditation/AffectionateBreathingSelfLoveMeditation_1125x2436.jpg",
      "favourite": true,
      "artist": {
        "artistId": "623c63-79af00707-3b0782br0",
        "artistName": "Cara Pereira",
        "artistImage": "https://stg-content.aayu.live/Meditations/artistimages/images3x/CaraPereira.png"
      },
      "metaData": {
        "duration": "9",
        "rating": 4.4,
        "views": "5k",
        "language": "English",
        "multiSeries": false,
        "tags": [
          {
            "displayTagId": "1",
            "displayTag": "Self -Observation"
          }
        ]
      }
    }
  ],
  "affirmations": [
    {
      "contentId": "81e167cf-7de1-4594-92e9-0d96d54d995e",
      "contentName": "Affirmation Logo",
      "contentImage": "https://stg-content.aayu.live/Affirmations/Image/affirmationlogotext.jpg",
      "favourite": true
    }
  ],
  "tips": [
    {
      "contentId": "81e167cf-7de1-4594-92e9-0d96d54d995e",
      "contentName": "Affirmation Logo",
      "contentImage": "https://stg-content.aayu.live/Affirmations/Image/affirmationlogotext.jpg",
      "favourite": true
    }
  ]
} 
*/

  List<Content?>? grow;
  List<Content?>? affirmations;
  List<Content?>? tips;

  FavouritesContentResponseContent({
    this.grow,
    this.affirmations,
    this.tips,
  });
  FavouritesContentResponseContent.fromJson(Map<String, dynamic> json) {
  if (json['grow'] != null) {
  final v = json['grow'];
  final arr0 = <Content>[];
  v.forEach((v) {
  arr0.add(Content.fromJson(v));
  });
    grow = arr0;
    }
  if (json['affirmations'] != null) {
  final v = json['affirmations'];
  final arr0 = <Content>[];
  v.forEach((v) {
  arr0.add(Content.fromJson(v));
  });
    affirmations = arr0;
    }
  if (json['tips'] != null) {
  final v = json['tips'];
  final arr0 = <Content>[];
  v.forEach((v) {
  arr0.add(Content.fromJson(v));
  });
    tips = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (grow != null) {
      final v = grow;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['grow'] = arr0;
    }
    if (affirmations != null) {
      final v = affirmations;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['affirmations'] = arr0;
    }
    if (tips != null) {
      final v = tips;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['tips'] = arr0;
    }
    return data;
  }
}

class FavouritesContentResponse {
/*
{
  "content": {
    "grow": [
      {
        "contentId": "ede9c55a-b21a-40bc-88cd-32f0a3e3e94c",
        "contentName": "Affectionate Breathing - Self Love Meditation",
        "contentImage": "https://stg-content.aayu.live/Relationship/finalcontent/AffectionateBreathingSelfLoveMeditation/AffectionateBreathingSelfLoveMeditation_750x554.jpg",
        "contentType": "Audio",
        "contentPath": "https://stg-content.aayu.live/Relationship/finalcontent/AffectionateBreathingSelfLoveMeditation/AffectionateBreathingSelfLoveMeditation.mp3",
        "playBGImage": "https://stg-content.aayu.live/Relationship/finalcontent/AffectionateBreathingSelfLoveMeditation/AffectionateBreathingSelfLoveMeditation_1125x2436.jpg",
        "favourite": true,
        "artist": {
          "artistId": "623c63-79af00707-3b0782br0",
          "artistName": "Cara Pereira",
          "artistImage": "https://stg-content.aayu.live/Meditations/artistimages/images3x/CaraPereira.png"
        },
        "metaData": {
          "duration": "9",
          "rating": 4.4,
          "views": "5k",
          "language": "English",
          "multiSeries": false,
          "tags": [
            {
              "displayTagId": "1",
              "displayTag": "Self -Observation"
            }
          ]
        }
      }
    ],
    "affrirmations": [
      {
        "contentId": "81e167cf-7de1-4594-92e9-0d96d54d995e",
        "contentName": "Affirmation Logo",
        "contentImage": "https://stg-content.aayu.live/Affirmations/Image/affirmationlogotext.jpg",
        "favourite": true
      }
    ],
    "tips": [
      {
        "contentId": "81e167cf-7de1-4594-92e9-0d96d54d995e",
        "contentName": "Affirmation Logo",
        "contentImage": "https://stg-content.aayu.live/Affirmations/Image/affirmationlogotext.jpg",
        "favourite": true
      }
    ]
  }
} 
*/

  FavouritesContentResponseContent? content;

  FavouritesContentResponse({
    this.content,
  });
  FavouritesContentResponse.fromJson(Map<String, dynamic> json) {
    content = (json['content'] != null) ? FavouritesContentResponseContent.fromJson(json['content']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (content != null) {
      data['content'] = content!.toJson();
    }
    return data;
  }
}
