///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProfileImageUploadResponse {
/*
{
  "userId": "25dd74f0-ac34-11ec-960f-0bd031cca007",
  "image": "https://resetcontent.s3.amazonaws.com/userprofile/25dd74f0-ac34-11ec-960f-0bd031cca007/counting-star-couple.jpg",
  "updatedAt": 1649416310000
} 
*/

  String? userId;
  String? image;
  int? updatedAt;

  ProfileImageUploadResponse({
    this.userId,
    this.image,
    this.updatedAt,
  });
  ProfileImageUploadResponse.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toString();
    image = json['image']?.toString();
    updatedAt = json['updatedAt']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['image'] = image;
    data['updatedAt'] = updatedAt;
    return data;
  }
}
