///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RemindersModelData {
/*
{
  "title": "Anxiety Care Program",
  "image": "XYZ",
  "active": false,
  "activeText": "fvfhvrje",
  "inactiveText": "enwb",
  "time": "11:30 pm",
  "color": "#948CEF"
} 
*/

  String? title;
  String? image;
  bool? active;
  String? activeText;
  String? inactiveText;
  String? time;
  String? color;

  RemindersModelData({
    this.title,
    this.image,
    this.active,
    this.activeText,
    this.inactiveText,
    this.time,
    this.color,
  });
  RemindersModelData.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    image = json['image']?.toString();
    active = json['active'];
    activeText = json['activeText']?.toString();
    inactiveText = json['inactiveText']?.toString();
    time = json['time']?.toString();
    color = json['color']?.toString();
  }
  switchReminder() {
    active = !active!;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['image'] = image;
    data['active'] = active;
    data['activeText'] = activeText;
    data['inactiveText'] = inactiveText;
    data['time'] = time;
    data['color'] = color;
    return data;
  }
}

class RemindersModel {
/*
{
  "data": [
    {
      "title": "Anxiety Care Program",
      "image": "XYZ",
      "active": false,
      "activeText": "fvfhvrje",
      "inactiveText": "enwb",
      "time": "11:30 pm",
      "color": "#948CEF"
    }
  ]
} 
*/

  List<RemindersModelData?>? data;

  RemindersModel({
    this.data,
  });
  RemindersModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <RemindersModelData>[];
      v.forEach((v) {
        arr0.add(RemindersModelData.fromJson(v));
      });
      data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    return data;
  }
}
