///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class YouMinutesSummaryResponseDetails {
/*
{
  "yogaMinutes": 0,
  "meditationMinutes": 8,
  "streak": 5
} 
*/

  int? yogaMinutes;
  int? meditationMinutes;
  int? streak;

  YouMinutesSummaryResponseDetails({
    this.yogaMinutes,
    this.meditationMinutes,
    this.streak,
  });
  YouMinutesSummaryResponseDetails.fromJson(Map<String, dynamic> json) {
    yogaMinutes = json['yogaMinutes']?.toInt();
    meditationMinutes = json['meditationMinutes']?.toInt();
    streak = json['streak']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['yogaMinutes'] = yogaMinutes;
    data['meditationMinutes'] = meditationMinutes;
    data['streak'] = streak;
    return data;
  }
}

class YouMinutesSummaryResponse {
/*
{
  "details": {
    "yogaMinutes": 0,
    "meditationMinutes": 8,
    "streak": 5
  }
} 
*/

  YouMinutesSummaryResponseDetails? details;

  YouMinutesSummaryResponse({
    this.details,
  });
  YouMinutesSummaryResponse.fromJson(Map<String, dynamic> json) {
    details = (json['details'] != null) ? YouMinutesSummaryResponseDetails.fromJson(json['details']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (details != null) {
      data['details'] = details!.toJson();
    }
    return data;
  }
}
