///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class YouLinksModelLinks {
/*
{
  "icon": "AppIcons.mySubscriptionsSVG",
  "width": 24,
  "height": 28.22,
  "title": "My Subscriptions",
  "navigation": ""
} 
*/

  String? icon;
  int? width;
  double? height;
  String? title;
  String? navigation;

  YouLinksModelLinks({
    this.icon,
    this.width,
    this.height,
    this.title,
    this.navigation,
  });
  YouLinksModelLinks.fromJson(Map<String, dynamic> json) {
    icon = json['icon']?.toString();
    width = json['width']?.toInt();
    height = json['height']?.toDouble();
    title = json['title']?.toString();
    navigation = json['navigation']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['icon'] = icon;
    data['width'] = width;
    data['height'] = height;
    data['title'] = title;
    data['navigation'] = navigation;
    return data;
  }
}

class YouLinksModel {
/*
{
  "links": [
    {
      "icon": "AppIcons.mySubscriptionsSVG",
      "width": 24,
      "height": 28.22,
      "title": "My Subscriptions",
      "navigation": ""
    }
  ]
} 
*/

  List<YouLinksModelLinks?>? links;

  YouLinksModel({
    this.links,
  });
  YouLinksModel.fromJson(Map<String, dynamic> json) {
  if (json['links'] != null) {
  final v = json['links'];
  final arr0 = <YouLinksModelLinks>[];
  v.forEach((v) {
  arr0.add(YouLinksModelLinks.fromJson(v));
  });
    links = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (links != null) {
      final v = links;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['links'] = arr0;
    }
    return data;
  }
}
