///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class YouMinutesSummaryModelSummaryPostion {
/*
{
  "top": -37.37
} 
*/

  double? top;

  YouMinutesSummaryModelSummaryPostion({
    this.top,
  });
  YouMinutesSummaryModelSummaryPostion.fromJson(Map<String, dynamic> json) {
    top = json['top']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['top'] = top;
    return data;
  }
}

class YouMinutesSummaryModelSummaryImage {
/*
{
  "imageUrl": "assets/images/you/yoga.png",
  "width": 44,
  "height": 64
} 
*/

  String? imageUrl;
  int? width;
  int? height;

  YouMinutesSummaryModelSummaryImage({
    this.imageUrl,
    this.width,
    this.height,
  });
  YouMinutesSummaryModelSummaryImage.fromJson(Map<String, dynamic> json) {
    imageUrl = json['imageUrl']?.toString();
    width = json['width']?.toInt();
    height = json['height']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['imageUrl'] = imageUrl;
    data['width'] = width;
    data['height'] = height;
    return data;
  }
}

class YouMinutesSummaryModelSummary {
/*
{
  "image": {
    "imageUrl": "assets/images/you/yoga.png",
    "width": 44,
    "height": 64
  },
  "postion": {
    "top": -37.37
  },
  "count": 3500,
  "section": "Minutes of Yoga"
} 
*/

  YouMinutesSummaryModelSummaryImage? image;
  YouMinutesSummaryModelSummaryPostion? postion;
  int? count;
  String? section;
  String? type;

  YouMinutesSummaryModelSummary({
    this.image,
    this.postion,
    this.count,
    this.section,
    this.type,
  });
  YouMinutesSummaryModelSummary.fromJson(Map<String, dynamic> json) {
    image = (json['image'] != null) ? YouMinutesSummaryModelSummaryImage.fromJson(json['image']) : null;
    postion = (json['postion'] != null) ? YouMinutesSummaryModelSummaryPostion.fromJson(json['postion']) : null;
    count = json['count']?.toInt();
    section = json['section']?.toString();
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (image != null) {
      data['image'] = image!.toJson();
    }
    if (postion != null) {
      data['postion'] = postion!.toJson();
    }
    data['count'] = count;
    data['section'] = section;
    data['type'] = type;
    return data;
  }
}

class YouMinutesSummaryModel {
/*
{
  "summary": [
    {
      "image": {
        "imageUrl": "assets/images/you/yoga.png",
        "width": 44,
        "height": 64
      },
      "postion": {
        "top": -37.37
      },
      "count": 3500,
      "section": "Minutes of Yoga"
      "type": "Yoga"
    }
  ]
} 
*/

  List<YouMinutesSummaryModelSummary?>? summary;

  YouMinutesSummaryModel({
    this.summary,
  });
  YouMinutesSummaryModel.fromJson(Map<String, dynamic> json) {
  if (json['summary'] != null) {
  final v = json['summary'];
  final arr0 = <YouMinutesSummaryModelSummary>[];
  v.forEach((v) {
  arr0.add(YouMinutesSummaryModelSummary.fromJson(v));
  });
    summary = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (summary != null) {
      final v = summary;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['summary'] = arr0;
    }
    return data;
  }
}
