///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CheckRegistrationResponseModel {
/*
{
  "userId": null,
  "status": null,
  "createdAt": null,
  "isRegister": false
} 
*/

  String? userId;
  String? status;
  String? createdAt;
  bool? isRegister;

  CheckRegistrationResponseModel({
    this.userId,
    this.status,
    this.createdAt,
    this.isRegister,
  });
  CheckRegistrationResponseModel.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toString();
    status = json['status']?.toString();
    createdAt = json['createdAt']?.toString();
    isRegister = json['isRegister'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['status'] = status;
    data['createdAt'] = createdAt;
    data['isRegister'] = isRegister;
    return data;
  }
}
