///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OnbardingRequestLocation {
/*
{
  "country": "India",
  "state": "Maharashtra",
  "city": "Mumbai",
  "pinCode": "400067"
} 
*/

  String? country;
  String? state;
  String? city;
  String? pinCode;

  OnbardingRequestLocation({
    this.country,
    this.state,
    this.city,
    this.pinCode,
  });
  OnbardingRequestLocation.fromJson(Map<String, dynamic> json) {
    country = json['country']?.toString();
    state = json['state']?.toString();
    city = json['city']?.toString();
    pinCode = json['pinCode']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['country'] = country;
    data['state'] = state;
    data['city'] = city;
    data['pinCode'] = pinCode;
    return data;
  }
}

class OnbardingRequestSocialNetwork {
/*
{
  "network": "Facebook",
  "socialId": "123456",
  "profilePic": ""
} 
*/

  String? network;
  String? socialId;
  String? profilePic;

  OnbardingRequestSocialNetwork({
    this.network,
    this.socialId,
    this.profilePic,
  });
  OnbardingRequestSocialNetwork.fromJson(Map<String, dynamic> json) {
    network = json['network']?.toString();
    socialId = json['socialId']?.toString();
    profilePic = json['profilePic']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['network'] = network;
    data['socialId'] = socialId;
    data['profilePic'] = profilePic;
    return data;
  }
}

class OnbardingRequest {
/*
{
  "firebaseUId": "RchpY3hDthOzxdumvewhIKaUeKF2",
  "firstName": "Mahesh",
  "lastName": "Karande",
  "gender": "Male",
  "dob": "27-11-1985",
  "socialNetwork": [
    {
      "network": "Facebook",
      "socialId": "123456",
      "profilePic": ""
    }
  ],
  "location": [
    {
      "country": "India",
      "state": "Maharashtra",
      "city": "Mumbai",
      "pinCode": "400067"
    }
  ]
} 
*/

  String? firebaseUId;
  String? firstName;
  String? lastName;
  String? emailId;
  String? gender;
  String? dob;
  List<OnbardingRequestSocialNetwork?>? socialNetwork;
  List<OnbardingRequestLocation?>? location;

  OnbardingRequest({
    this.firebaseUId,
    this.firstName,
    this.lastName,
    this.emailId,
    this.gender,
    this.dob,
    this.socialNetwork,
    this.location,
  });
  OnbardingRequest.fromJson(Map<String, dynamic> json) {
    firebaseUId = json['firebaseUId']?.toString();
    firstName = json['firstName']?.toString();
    lastName = json['lastName']?.toString();
    emailId = json['emailId']?.toString();
    gender = json['gender']?.toString();
    dob = json['dob']?.toString();
    if (json['socialNetwork'] != null) {
      final v = json['socialNetwork'];
      final arr0 = <OnbardingRequestSocialNetwork>[];
      v.forEach((v) {
        arr0.add(OnbardingRequestSocialNetwork.fromJson(v));
      });
      socialNetwork = arr0;
    }
    if (json['location'] != null) {
      final v = json['location'];
      final arr0 = <OnbardingRequestLocation>[];
      v.forEach((v) {
        arr0.add(OnbardingRequestLocation.fromJson(v));
      });
      location = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['firebaseUId'] = firebaseUId;
    data['firstName'] = firstName;
    data['lastName'] = lastName;
    data['emailId'] = emailId;
    data['gender'] = gender;
    data['dob'] = dob;
    if (socialNetwork != null) {
      final v = socialNetwork;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['socialNetwork'] = arr0;
    }
    if (location != null) {
      final v = location;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['location'] = arr0;
    }
    return data;
  }
}
