///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OnboardingResponse {
/*
{
  "userId": "6b9b71d0-7d14-11ec-ab33-158739dbb2aa",
  "isFirstTime": true,
  "createdAt": 1643028719000,
  "updatedAt": 1643028719000
} 
*/

  String? userId;
  bool? isFirstTime;
  String? createdAt;
  String? updatedAt;

  OnboardingResponse({
    this.userId,
    this.isFirstTime,
    this.createdAt,
    this.updatedAt,
  });
  OnboardingResponse.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toString();
    isFirstTime = json['isFirstTime'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['isFirstTime'] = isFirstTime;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}
