///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubmitAssessmentRequestModelAssessmentOptions {
/*
{
  "text": "Posture",
  "selected": true
} 
*/

  String? text;
  bool? selected;

  SubmitAssessmentRequestModelAssessmentOptions({
    this.text,
    this.selected,
  });
  SubmitAssessmentRequestModelAssessmentOptions.fromJson(
      Map<String, dynamic> json) {
    text = json['text']?.toString();
    selected = json['selected'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['text'] = text;
    data['selected'] = selected;
    return data;
  }
}

class SubmitAssessmentRequestModelAssessment {
/*
{
  "assessmentId": "1",
  "options": [
    {
      "text": "Posture",
      "selected": true
    }
  ]
} 
*/

  String? assessmentId;
  List<SubmitAssessmentRequestModelAssessmentOptions?>? options;

  SubmitAssessmentRequestModelAssessment({
    this.assessmentId,
    this.options,
  });
  SubmitAssessmentRequestModelAssessment.fromJson(Map<String, dynamic> json) {
    assessmentId = json['assessmentId']?.toString();
    if (json['options'] != null) {
      final v = json['options'];
      final arr0 = <SubmitAssessmentRequestModelAssessmentOptions>[];
      v.forEach((v) {
        arr0.add(SubmitAssessmentRequestModelAssessmentOptions.fromJson(v));
      });
      options = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['assessmentId'] = assessmentId;
    if (options != null) {
      final v = options;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['options'] = arr0;
    }
    return data;
  }
}

class SubmitAssessmentRequestModel {
/*
{
  "assessment": [
    {
      "assessmentId": "1",
      "options": [
        {
          "text": "Posture",
          "selected": true
        }
      ]
    }
  ]
} 
*/

  List<SubmitAssessmentRequestModelAssessment?>? assessment;

  SubmitAssessmentRequestModel({
    this.assessment,
  });
  SubmitAssessmentRequestModel.fromJson(Map<String, dynamic> json) {
    if (json['assessment'] != null) {
      final v = json['assessment'];
      final arr0 = <SubmitAssessmentRequestModelAssessment>[];
      v.forEach((v) {
        arr0.add(SubmitAssessmentRequestModelAssessment.fromJson(v));
      });
      assessment = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (assessment != null) {
      final v = assessment;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['assessment'] = arr0;
    }
    return data;
  }
}
