///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubmitAssessmentResponseModel {
/*
{
  "onboardAssessmentId": "bbbe0210-a9d6-11ec-96b7-23d12427667c",
  "createdAt": 1647950027000
} 
*/

  String? onboardAssessmentId;
  String? createdAt;

  SubmitAssessmentResponseModel({
    this.onboardAssessmentId,
    this.createdAt,
  });
  SubmitAssessmentResponseModel.fromJson(Map<String, dynamic> json) {
    onboardAssessmentId = json['onboardAssessmentId']?.toString();
    createdAt = json['createdAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['onboardAssessmentId'] = onboardAssessmentId;
    data['createdAt'] = createdAt;
    return data;
  }
}
