///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GrowCategoriesResponseCategories {
/*
{
  "categoryId": "f32da430-b011-11ec-b7b3-799f0c855eac",
  "categoryName": "affirmation",
  "categoryImage": "https://resetcontent.s3.ap-south-1.amazonaws.com/categoryicon/Affirmation.svg",
  "accessType": "content"
} 
*/

  String? categoryId;
  String? categoryName;
  String? categoryImage;
  String? accessType;

  GrowCategoriesResponseCategories({
    this.categoryId,
    this.categoryName,
    this.categoryImage,
    this.accessType,
  });
  GrowCategoriesResponseCategories.fromJson(Map<String, dynamic> json) {
    categoryId = json['categoryId']?.toString();
    categoryName = json['categoryName']?.toString();
    categoryImage = json['categoryImage']?.toString();
    accessType = json['accessType']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['categoryId'] = categoryId;
    data['categoryName'] = categoryName;
    data['categoryImage'] = categoryImage;
    data['accessType'] = accessType;
    return data;
  }
}

class GrowCategoriesResponse {
/*
{
  "categories": [
    {
      "categoryId": "f32da430-b011-11ec-b7b3-799f0c855eac",
      "categoryName": "affirmation",
      "categoryImage": "https://resetcontent.s3.ap-south-1.amazonaws.com/categoryicon/Affirmation.svg",
      "accessType": "content"
    }
  ]
} 
*/

  List<GrowCategoriesResponseCategories?>? categories;

  GrowCategoriesResponse({
    this.categories,
  });
  GrowCategoriesResponse.fromJson(Map<String, dynamic> json) {
  if (json['categories'] != null) {
  final v = json['categories'];
  final arr0 = <GrowCategoriesResponseCategories>[];
  v.forEach((v) {
  arr0.add(GrowCategoriesResponseCategories.fromJson(v));
  });
    categories = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (categories != null) {
      final v = categories;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['categories'] = arr0;
    }
    return data;
  }
}
