///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DayZeroContentResponseContentArtist {
/*
{
  "artistId": "",
  "artistName": "",
  "artistImage": "",
  "followers": "",
  "isFollowed": false
} 
*/

  String? artistId;
  String? artistName;
  String? artistImage;
  String? followers;
  bool? isFollowed;

  DayZeroContentResponseContentArtist({
    this.artistId,
    this.artistName,
    this.artistImage,
    this.followers,
    this.isFollowed,
  });
  DayZeroContentResponseContentArtist.fromJson(Map<String, dynamic> json) {
    artistId = json['artistId']?.toString();
    artistName = json['artistName']?.toString();
    artistImage = json['artistImage']?.toString();
    followers = json['followers']?.toString();
    isFollowed = json['isFollowed'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['artistId'] = artistId;
    data['artistName'] = artistName;
    data['artistImage'] = artistImage;
    data['followers'] = followers;
    data['isFollowed'] = isFollowed;
    return data;
  }
}

class DayZeroContentResponseContentMetaData {
/*
{
  "duration": "6.5",
  "rating": 0,
  "views": null,
  "language": null,
  "multiSeries": false,
  "tags": null
} 
*/

  String? duration;
  int? rating;
  String? views;
  String? language;
  bool? multiSeries;
  String? tags;

  DayZeroContentResponseContentMetaData({
    this.duration,
    this.rating,
    this.views,
    this.language,
    this.multiSeries,
    this.tags,
  });
  DayZeroContentResponseContentMetaData.fromJson(Map<String, dynamic> json) {
    duration = json['duration']?.toString();
    rating = json['rating']?.toInt();
    views = json['views']?.toString();
    language = json['language']?.toString();
    multiSeries = json['multiSeries'];
    tags = json['tags']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['duration'] = duration;
    data['rating'] = rating;
    data['views'] = views;
    data['language'] = language;
    data['multiSeries'] = multiSeries;
    data['tags'] = tags;
    return data;
  }
}

class DayZeroContentResponseContent {
/*
{
  "contentId": "bf6c1f4a-4166-4060-b24d-c0d625df9601",
  "contentName": "DeepRelaxationTechnique",
  "contentImage": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique_966x543.jpg",
  "contentPath": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique.mp4",
  "contentDesc": null,
  "playBGImage": null,
  "contentType": "Video",
  "isFavourite": false,
  "metaData": {
    "duration": "6.5",
    "rating": 0,
    "views": null,
    "language": null,
    "multiSeries": false,
    "tags": null
  },
  "artist": {
    "artistId": "",
    "artistName": "",
    "artistImage": "",
    "followers": "",
    "isFollowed": false
  }
} 
*/

  String? contentId;
  String? contentName;
  String? contentImage;
  String? contentPath;
  String? contentDesc;
  String? playBGImage;
  String? contentType;
  bool? isFavourite;
  DayZeroContentResponseContentMetaData? metaData;
  DayZeroContentResponseContentArtist? artist;

  DayZeroContentResponseContent({
    this.contentId,
    this.contentName,
    this.contentImage,
    this.contentPath,
    this.contentDesc,
    this.playBGImage,
    this.contentType,
    this.isFavourite,
    this.metaData,
    this.artist,
  });
  DayZeroContentResponseContent.fromJson(Map<String, dynamic> json) {
    contentId = json['contentId']?.toString();
    contentName = json['contentName']?.toString();
    contentImage = json['contentImage']?.toString();
    contentPath = json['contentPath']?.toString();
    contentDesc = json['contentDesc']?.toString();
    playBGImage = json['playBGImage']?.toString();
    contentType = json['contentType']?.toString();
    isFavourite = json['isFavourite'];
    metaData = (json['metaData'] != null)
        ? DayZeroContentResponseContentMetaData.fromJson(json['metaData'])
        : null;
    artist = (json['artist'] != null)
        ? DayZeroContentResponseContentArtist.fromJson(json['artist'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['contentId'] = contentId;
    data['contentName'] = contentName;
    data['contentImage'] = contentImage;
    data['contentPath'] = contentPath;
    data['contentDesc'] = contentDesc;
    data['playBGImage'] = playBGImage;
    data['contentType'] = contentType;
    data['isFavourite'] = isFavourite;
    if (metaData != null) {
      data['metaData'] = metaData!.toJson();
    }
    if (artist != null) {
      data['artist'] = artist!.toJson();
    }
    return data;
  }
}

class DayZeroContentResponse {
/*
{
  "day": 0,
  "content": {
    "contentId": "bf6c1f4a-4166-4060-b24d-c0d625df9601",
    "contentName": "DeepRelaxationTechnique",
    "contentImage": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique_966x543.jpg",
    "contentPath": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique.mp4",
    "contentDesc": null,
    "playBGImage": null,
    "contentType": "Video",
    "isFavourite": false,
    "metaData": {
      "duration": "6.5",
      "rating": 0,
      "views": null,
      "language": null,
      "multiSeries": false,
      "tags": null
    },
    "artist": {
      "artistId": "",
      "artistName": "",
      "artistImage": "",
      "followers": "",
      "isFollowed": false
    }
  },
  "status": "Open"
} 
*/

  int? day;
  DayZeroContentResponseContent? content;
  String? status;

  DayZeroContentResponse({
    this.day,
    this.content,
    this.status,
  });
  DayZeroContentResponse.fromJson(Map<String, dynamic> json) {
    day = json['day']?.toInt();
    content = (json['content'] != null)
        ? DayZeroContentResponseContent.fromJson(json['content'])
        : null;
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['day'] = day;
    if (content != null) {
      data['content'] = content!.toJson();
    }
    data['status'] = status;
    return data;
  }
}
