///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HealingTipsResponseTodaysTip {
/*
{
  "tip": "Be smart with snacks.",
  "isFavourite": false
} 
*/

  String? tipId;
  String? tip;
  bool? isFavourite;

  HealingTipsResponseTodaysTip({
    this.tipId,
    this.tip,
    this.isFavourite,
  });
  HealingTipsResponseTodaysTip.fromJson(Map<String, dynamic> json) {
    tipId = json['tipId']?.toString();
    tip = json['tip']?.toString();
    isFavourite = json['isFavourite'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['tipId'] = tipId;
    data['tip'] = tip;
    data['isFavourite'] = isFavourite;
    return data;
  }
}

class HealingTipsResponse {
/*
{
  "todaysTip": {
    "tip": "Be smart with snacks.",
    "isFavourite": false
  }
} 
*/

  HealingTipsResponseTodaysTip? todaysTip;

  HealingTipsResponse({
    this.todaysTip,
  });
  HealingTipsResponse.fromJson(Map<String, dynamic> json) {
    todaysTip = (json['todaysTip'] != null)
        ? HealingTipsResponseTodaysTip.fromJson(json['todaysTip'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (todaysTip != null) {
      data['todaysTip'] = todaysTip!.toJson();
    }
    return data;
  }
}
