///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InsightCardResponseDetailsInsight {
/*
{
  "bgColor": "#A5ECD1",
  "title": "Diabetes Care",
  "started": 23,
  "nowAt": 44,
  "image": "Images.diabetesCareImage",
  "width": 57.44,
  "height": 65.68,
  "status": "Good Start"
} 
*/

  String? bgColor;
  String? title;
  int? started;
  int? nowAt;
  String? image;
  double? width;
  double? height;
  String? status;

  InsightCardResponseDetailsInsight({
    this.bgColor,
    this.title,
    this.started,
    this.nowAt,
    this.image,
    this.width,
    this.height,
    this.status,
  });
  InsightCardResponseDetailsInsight.fromJson(Map<String, dynamic> json) {
    bgColor = json['bgColor']?.toString();
    title = json['title']?.toString();
    started = json['started']?.toInt();
    nowAt = json['nowAt']?.toInt();
    image = json['image']?.toString();
    width = json['width']?.toDouble();
    height = json['height']?.toDouble();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bgColor'] = bgColor;
    data['title'] = title;
    data['started'] = started;
    data['nowAt'] = nowAt;
    data['image'] = image;
    data['width'] = width;
    data['height'] = height;
    data['status'] = status;
    return data;
  }
}

class InsightCardResponseDetails {
/*
{
  "overallPercentage": 48,
  "insight": [
    {
      "bgColor": "#A5ECD1",
      "title": "Diabetes Care",
      "started": 23,
      "nowAt": 44,
      "image": "Images.diabetesCareImage",
      "width": 57.44,
      "height": 65.68,
      "status": "Good Start"
    }
  ]
} 
*/

  int? overallPercentage;
  List<InsightCardResponseDetailsInsight?>? insight;

  InsightCardResponseDetails({
    this.overallPercentage,
    this.insight,
  });
  InsightCardResponseDetails.fromJson(Map<String, dynamic> json) {
    overallPercentage = json['overallPercentage']?.toInt();
  if (json['insight'] != null) {
  final v = json['insight'];
  final arr0 = <InsightCardResponseDetailsInsight>[];
  v.forEach((v) {
  arr0.add(InsightCardResponseDetailsInsight.fromJson(v));
  });
    insight = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['overallPercentage'] = overallPercentage;
    if (insight != null) {
      final v = insight;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['insight'] = arr0;
    }
    return data;
  }
}

class InsightCardResponse {
/*
{
  "details": {
    "overallPercentage": 48,
    "insight": [
      {
        "bgColor": "#A5ECD1",
        "title": "Diabetes Care",
        "started": 23,
        "nowAt": 44,
        "image": "Images.diabetesCareImage",
        "width": 57.44,
        "height": 65.68,
        "status": "Good Start"
      }
    ]
  }
} 
*/

  InsightCardResponseDetails? details;

  InsightCardResponse({
    this.details,
  });
  InsightCardResponse.fromJson(Map<String, dynamic> json) {
    details = (json['details'] != null) ? InsightCardResponseDetails.fromJson(json['details']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (details != null) {
      data['details'] = details!.toJson();
    }
    return data;
  }
}
