///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HealingProgramContentResponseProgramDetailsDaysContentArtist {
/*
{
  "artistId": "",
  "artistName": "",
  "artistImage": "",
  "followers": "",
  "isFollowed": false
} 
*/

  String? artistId;
  String? artistName;
  String? artistImage;
  String? followers;
  bool? isFollowed;

  HealingProgramContentResponseProgramDetailsDaysContentArtist({
    this.artistId,
    this.artistName,
    this.artistImage,
    this.followers,
    this.isFollowed,
  });
  HealingProgramContentResponseProgramDetailsDaysContentArtist.fromJson(
      Map<String, dynamic> json) {
    artistId = json['artistId']?.toString();
    artistName = json['artistName']?.toString();
    artistImage = json['artistImage']?.toString();
    followers = json['followers']?.toString();
    isFollowed = json['isFollowed'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['artistId'] = artistId;
    data['artistName'] = artistName;
    data['artistImage'] = artistImage;
    data['followers'] = followers;
    data['isFollowed'] = isFollowed;
    return data;
  }
}

class HealingProgramContentResponseProgramDetailsDaysContentMetaData {
/*
{
  "duration": "6.5",
  "rating": 0,
  "views": null,
  "language": null,
  "multiSeries": false,
  "tags": null
} 
*/

  String? duration;
  int? rating;
  String? views;
  String? language;
  bool? multiSeries;
  String? tags;

  HealingProgramContentResponseProgramDetailsDaysContentMetaData({
    this.duration,
    this.rating,
    this.views,
    this.language,
    this.multiSeries,
    this.tags,
  });
  HealingProgramContentResponseProgramDetailsDaysContentMetaData.fromJson(
      Map<String, dynamic> json) {
    duration = json['duration']?.toString();
    rating = json['rating']?.toInt();
    views = json['views']?.toString();
    language = json['language']?.toString();
    multiSeries = json['multiSeries'];
    tags = json['tags']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['duration'] = duration;
    data['rating'] = rating;
    data['views'] = views;
    data['language'] = language;
    data['multiSeries'] = multiSeries;
    data['tags'] = tags;
    return data;
  }
}

class HealingProgramContentResponseProgramDetailsDaysContent {
/*
{
  "contentId": "bf6c1f4a-4166-4060-b24d-c0d625df9601",
  "contentName": "DeepRelaxationTechnique",
  "contentImage": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique_966x543.jpg",
  "contentPath": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique.mp4",
  "contentDesc": null,
  "playBGImage": null,
  "contentType": "Video",
  "isFavourite": false,
  "metaData": {
    "duration": "6.5",
    "rating": 0,
    "views": null,
    "language": null,
    "multiSeries": false,
    "tags": null
  },
  "artist": {
    "artistId": "",
    "artistName": "",
    "artistImage": "",
    "followers": "",
    "isFollowed": false
  }
} 
*/

  String? contentId;
  String? contentName;
  String? contentImage;
  String? contentPath;
  String? contentDesc;
  String? playBGImage;
  String? contentType;
  bool? isFavourite;
  HealingProgramContentResponseProgramDetailsDaysContentMetaData? metaData;
  HealingProgramContentResponseProgramDetailsDaysContentArtist? artist;

  HealingProgramContentResponseProgramDetailsDaysContent({
    this.contentId,
    this.contentName,
    this.contentImage,
    this.contentPath,
    this.contentDesc,
    this.playBGImage,
    this.contentType,
    this.isFavourite,
    this.metaData,
    this.artist,
  });
  HealingProgramContentResponseProgramDetailsDaysContent.fromJson(
      Map<String, dynamic> json) {
    contentId = json['contentId']?.toString();
    contentName = json['contentName']?.toString();
    contentImage = json['contentImage']?.toString();
    contentPath = json['contentPath']?.toString();
    contentDesc = json['contentDesc']?.toString();
    playBGImage = json['playBGImage']?.toString();
    contentType = json['contentType']?.toString();
    isFavourite = json['isFavourite'];
    metaData = (json['metaData'] != null)
        ? HealingProgramContentResponseProgramDetailsDaysContentMetaData
            .fromJson(json['metaData'])
        : null;
    artist = (json['artist'] != null)
        ? HealingProgramContentResponseProgramDetailsDaysContentArtist.fromJson(
            json['artist'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['contentId'] = contentId;
    data['contentName'] = contentName;
    data['contentImage'] = contentImage;
    data['contentPath'] = contentPath;
    data['contentDesc'] = contentDesc;
    data['playBGImage'] = playBGImage;
    data['contentType'] = contentType;
    data['isFavourite'] = isFavourite;
    if (metaData != null) {
      data['metaData'] = metaData!.toJson();
    }
    if (artist != null) {
      data['artist'] = artist!.toJson();
    }
    return data;
  }
}

class HealingProgramContentResponseProgramDetailsDays {
/*
{
  "day": 0,
  "content": {
    "contentId": "bf6c1f4a-4166-4060-b24d-c0d625df9601",
    "contentName": "DeepRelaxationTechnique",
    "contentImage": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique_966x543.jpg",
    "contentPath": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique.mp4",
    "contentDesc": null,
    "playBGImage": null,
    "contentType": "Video",
    "isFavourite": false,
    "metaData": {
      "duration": "6.5",
      "rating": 0,
      "views": null,
      "language": null,
      "multiSeries": false,
      "tags": null
    },
    "artist": {
      "artistId": "",
      "artistName": "",
      "artistImage": "",
      "followers": "",
      "isFollowed": false
    }
  },
  "status": "OPEN"
} 
*/

  int? day;
  HealingProgramContentResponseProgramDetailsDaysContent? content;
  String? status;

  HealingProgramContentResponseProgramDetailsDays({
    this.day,
    this.content,
    this.status,
  });
  HealingProgramContentResponseProgramDetailsDays.fromJson(
      Map<String, dynamic> json) {
    day = json['day']?.toInt();
    content = (json['content'] != null)
        ? HealingProgramContentResponseProgramDetailsDaysContent.fromJson(
            json['content'])
        : null;
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['day'] = day;
    if (content != null) {
      data['content'] = content!.toJson();
    }
    data['status'] = status;
    return data;
  }
}

class HealingProgramContentResponseProgramDetailsSliverAppBar {
/*
{
  "titleColor": "#A0A0A0",
  "dayColor": "#FCAFAF",
  "title": "Heart Disease Care",
  "image": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique_966x543.jpg"
} 
*/

  String? titleColor;
  String? dayColor;
  String? title;
  String? image;

  HealingProgramContentResponseProgramDetailsSliverAppBar({
    this.titleColor,
    this.dayColor,
    this.title,
    this.image,
  });
  HealingProgramContentResponseProgramDetailsSliverAppBar.fromJson(
      Map<String, dynamic> json) {
    titleColor = json['titleColor']?.toString();
    dayColor = json['dayColor']?.toString();
    title = json['title']?.toString();
    image = json['image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['titleColor'] = titleColor;
    data['dayColor'] = dayColor;
    data['title'] = title;
    data['image'] = image;
    return data;
  }
}

class HealingProgramContentResponseProgramDetails {
/*
{
  "programId": "e22f0480-af1c-11ec-9467-13c66ae1408d",
  "type": "30",
  "diseaseId": "d1c90410-ae63-11ec-9d44-1bcb25ed5896",
  "period": "30",
  "startDate": "2022-03-30",
  "endDate": "2022-04-29",
  "sliverAppBar": {
    "titleColor": "#A0A0A0",
    "dayColor": "#FCAFAF",
    "title": "Heart Disease Care",
    "image": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique_966x543.jpg"
  },
  "days": [
    {
      "day": 0,
      "content": {
        "contentId": "bf6c1f4a-4166-4060-b24d-c0d625df9601",
        "contentName": "DeepRelaxationTechnique",
        "contentImage": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique_966x543.jpg",
        "contentPath": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique.mp4",
        "contentDesc": null,
        "playBGImage": null,
        "contentType": "Video",
        "isFavourite": false,
        "metaData": {
          "duration": "6.5",
          "rating": 0,
          "views": null,
          "language": null,
          "multiSeries": false,
          "tags": null
        },
        "artist": {
          "artistId": "",
          "artistName": "",
          "artistImage": "",
          "followers": "",
          "isFollowed": false
        }
      },
      "status": "OPEN"
    }
  ]
} 
*/

  String? programId;
  String? type;
  String? diseaseId;
  String? period;
  String? startDate;
  String? endDate;
  HealingProgramContentResponseProgramDetailsSliverAppBar? sliverAppBar;
  List<HealingProgramContentResponseProgramDetailsDays?>? days;

  HealingProgramContentResponseProgramDetails({
    this.programId,
    this.type,
    this.diseaseId,
    this.period,
    this.startDate,
    this.endDate,
    this.sliverAppBar,
    this.days,
  });
  HealingProgramContentResponseProgramDetails.fromJson(
      Map<String, dynamic> json) {
    programId = json['programId']?.toString();
    type = json['type']?.toString();
    diseaseId = json['diseaseId']?.toString();
    period = json['period']?.toString();
    startDate = json['startDate']?.toString();
    endDate = json['endDate']?.toString();
    sliverAppBar = (json['sliverAppBar'] != null)
        ? HealingProgramContentResponseProgramDetailsSliverAppBar.fromJson(
            json['sliverAppBar'])
        : null;
    if (json['days'] != null) {
      final v = json['days'];
      final arr0 = <HealingProgramContentResponseProgramDetailsDays>[];
      v.forEach((v) {
        arr0.add(HealingProgramContentResponseProgramDetailsDays.fromJson(v));
      });
      days = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['programId'] = programId;
    data['type'] = type;
    data['diseaseId'] = diseaseId;
    data['period'] = period;
    data['startDate'] = startDate;
    data['endDate'] = endDate;
    if (sliverAppBar != null) {
      data['sliverAppBar'] = sliverAppBar!.toJson();
    }
    if (days != null) {
      final v = days;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['days'] = arr0;
    }
    return data;
  }
}

class HealingProgramContentResponse {
/*
{
  "programDetails": {
    "programId": "e22f0480-af1c-11ec-9467-13c66ae1408d",
    "type": "30",
    "diseaseId": "d1c90410-ae63-11ec-9d44-1bcb25ed5896",
    "period": "30",
    "startDate": "2022-03-30",
    "endDate": "2022-04-29",
    "sliverAppBar": {
      "titleColor": "#A0A0A0",
      "dayColor": "#FCAFAF",
      "title": "Heart Disease Care",
      "image": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique_966x543.jpg"
    },
    "days": [
      {
        "day": 0,
        "content": {
          "contentId": "bf6c1f4a-4166-4060-b24d-c0d625df9601",
          "contentName": "DeepRelaxationTechnique",
          "contentImage": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique_966x543.jpg",
          "contentPath": "https://resetcontent.s3.ap-south-1.amazonaws.com/280322/DeepRelaxationTechnique/DeepRelaxationTechnique.mp4",
          "contentDesc": null,
          "playBGImage": null,
          "contentType": "Video",
          "isFavourite": false,
          "metaData": {
            "duration": "6.5",
            "rating": 0,
            "views": null,
            "language": null,
            "multiSeries": false,
            "tags": null
          },
          "artist": {
            "artistId": "",
            "artistName": "",
            "artistImage": "",
            "followers": "",
            "isFollowed": false
          }
        },
        "status": "OPEN"
      }
    ]
  }
} 
*/

  HealingProgramContentResponseProgramDetails? programDetails;

  HealingProgramContentResponse({
    this.programDetails,
  });
  HealingProgramContentResponse.fromJson(Map<String, dynamic> json) {
    programDetails = (json['programDetails'] != null)
        ? HealingProgramContentResponseProgramDetails.fromJson(
            json['programDetails'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (programDetails != null) {
      data['programDetails'] = programDetails!.toJson();
    }
    return data;
  }
}
