///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HealingQuestionResponseTodaysQuestionOptions {
/*
{
  "options": "No",
  "selected": false
} 
*/

  String? options;
  bool? selected;

  HealingQuestionResponseTodaysQuestionOptions({
    this.options,
    this.selected,
  });
  HealingQuestionResponseTodaysQuestionOptions.fromJson(Map<String, dynamic> json) {
    options = json['options']?.toString();
    selected = json['selected'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['options'] = options;
    data['selected'] = selected;
    return data;
  }
}

class HealingQuestionResponseTodaysQuestion {
/*
{
  "question": "Do you see an improvement in flexibility?",
  "answerSubmitted": false,
  "options": [
    {
      "options": "No",
      "selected": false
    }
  ]
} 
*/

  String? question;
  bool? answerSubmitted;
  List<HealingQuestionResponseTodaysQuestionOptions?>? options;

  HealingQuestionResponseTodaysQuestion({
    this.question,
    this.answerSubmitted,
    this.options,
  });
  HealingQuestionResponseTodaysQuestion.fromJson(Map<String, dynamic> json) {
    question = json['question']?.toString();
    answerSubmitted = json['answerSubmitted'];
  if (json['options'] != null) {
  final v = json['options'];
  final arr0 = <HealingQuestionResponseTodaysQuestionOptions>[];
  v.forEach((v) {
  arr0.add(HealingQuestionResponseTodaysQuestionOptions.fromJson(v));
  });
    options = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['question'] = question;
    data['answerSubmitted'] = answerSubmitted;
    if (options != null) {
      final v = options;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['options'] = arr0;
    }
    return data;
  }
}

class HealingQuestionResponse {
/*
{
  "todaysQuestion": {
    "question": "Do you see an improvement in flexibility?",
    "answerSubmitted": false,
    "options": [
      {
        "options": "No",
        "selected": false
      }
    ]
  }
} 
*/

  HealingQuestionResponseTodaysQuestion? todaysQuestion;

  HealingQuestionResponse({
    this.todaysQuestion,
  });
  HealingQuestionResponse.fromJson(Map<String, dynamic> json) {
    todaysQuestion = (json['todaysQuestion'] != null) ? HealingQuestionResponseTodaysQuestion.fromJson(json['todaysQuestion']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (todaysQuestion != null) {
      data['todaysQuestion'] = todaysQuestion!.toJson();
    }
    return data;
  }
}
