///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HealingQuizSubmitAnswerRequestOptions {
/*
{
  "option": "Type 1",
  "selected": false,
  "correctAnswer": true
} 
*/

  String? option;
  bool? selected;
  bool? correctAnswer;

  HealingQuizSubmitAnswerRequestOptions({
    this.option,
    this.selected,
    this.correctAnswer,
  });
  HealingQuizSubmitAnswerRequestOptions.fromJson(Map<String, dynamic> json) {
    option = json['option']?.toString();
    selected = json['selected'];
    correctAnswer = json['correctAnswer'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['option'] = option;
    data['selected'] = selected;
    data['correctAnswer'] = correctAnswer;
    return data;
  }
}

class HealingQuizSubmitAnswerRequest {
/*
{
  "diseaseId": "d1c90410-ae63-11ec-9d44-1bcb25ed5896",
  "programId": "72570cf0-af1e-11ec-9467-13c66ae1408d",
  "quizId": "07cb6b44-5b7e-4e13-8e69-e9a2619dbf12",
  "options": [
    {
      "option": "Type 1",
      "selected": false,
      "correctAnswer": true
    }
  ]
} 
*/

  String? diseaseId;
  String? programId;
  String? quizId;
  List<HealingQuizSubmitAnswerRequestOptions?>? options;

  HealingQuizSubmitAnswerRequest({
    this.diseaseId,
    this.programId,
    this.quizId,
    this.options,
  });
  HealingQuizSubmitAnswerRequest.fromJson(Map<String, dynamic> json) {
    diseaseId = json['diseaseId']?.toString();
    programId = json['programId']?.toString();
    quizId = json['quizId']?.toString();
    if (json['options'] != null) {
      final v = json['options'];
      final arr0 = <HealingQuizSubmitAnswerRequestOptions>[];
      v.forEach((v) {
        arr0.add(HealingQuizSubmitAnswerRequestOptions.fromJson(v));
      });
      options = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['diseaseId'] = diseaseId;
    data['programId'] = programId;
    data['quizId'] = quizId;
    if (options != null) {
      final v = options;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['options'] = arr0;
    }
    return data;
  }
}
