///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DeeplinkDiseaseDetailModelBenefits {
/*
{
  "icon": "https://stg-content.aayu.live/healing/group55.png",
  "text": "Induces relaxation in body and mind"
} 
*/

  String? icon;
  String? text;

  DeeplinkDiseaseDetailModelBenefits({
    this.icon,
    this.text,
  });
  DeeplinkDiseaseDetailModelBenefits.fromJson(Map<String, dynamic> json) {
    icon = json['icon']?.toString();
    text = json['text']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['icon'] = icon;
    data['text'] = text;
    return data;
  }
}

class DeeplinkDiseaseDetailModelDetailsHowtoproceed {
/*
{
  "image": "dnd",
  "title": "Choose Program Preferences",
  "description": "Choose your daily programs (30/60 mins) based on your preferences"
} 
*/

  String? image;
  String? title;
  String? description;

  DeeplinkDiseaseDetailModelDetailsHowtoproceed({
    this.image,
    this.title,
    this.description,
  });
  DeeplinkDiseaseDetailModelDetailsHowtoproceed.fromJson(
      Map<String, dynamic> json) {
    image = json['image']?.toString();
    title = json['title']?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['image'] = image;
    data['title'] = title;
    data['description'] = description;
    return data;
  }
}

class DeeplinkDiseaseDetailModelDetailsAddOns {
/*
{
  "icon": "bbv",
  "text": "1-on-1 Doctor Consultation"
} 
*/

  String? icon;
  String? text;

  DeeplinkDiseaseDetailModelDetailsAddOns({
    this.icon,
    this.text,
  });
  DeeplinkDiseaseDetailModelDetailsAddOns.fromJson(Map<String, dynamic> json) {
    icon = json['icon']?.toString();
    text = json['text']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['icon'] = icon;
    data['text'] = text;
    return data;
  }
}

class DeeplinkDiseaseDetailModelDetailsList {
/*
{
  "icon": "https://stg-content.aayu.live/healing/group55.png",
  "text": "Daily Online Practice"
} 
*/

  String? icon;
  String? text;

  DeeplinkDiseaseDetailModelDetailsList({
    this.icon,
    this.text,
  });
  DeeplinkDiseaseDetailModelDetailsList.fromJson(Map<String, dynamic> json) {
    icon = json['icon']?.toString();
    text = json['text']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['icon'] = icon;
    data['text'] = text;
    return data;
  }
}

class DeeplinkDiseaseDetailModelDetails {
/*
{
  "overview": "Our Anxiety Disorder program is inclusive and open to all. There are no restrictions based on age, gender or body-type.. Our program offers Daily Online Practice with compassionate, trained and professional experts.",
  "list": [
    {
      "icon": "https://stg-content.aayu.live/healing/group55.png",
      "text": "Daily Online Practice"
    }
  ],
  "add-ons": [
    {
      "icon": "bbv",
      "text": "1-on-1 Doctor Consultation"
    }
  ],
  "svyasa": "We can write 2 - 3 lines about the s.-vyasa and science backed research and decaded of practice. We should also mention about s-vyasa core speciality. Also mention about the years of experience in the wellness space",
  "howtoproceed": [
    {
      "image": "dnd",
      "title": "Choose Program Preferences",
      "description": "Choose your daily programs (30/60 mins) based on your preferences"
    }
  ]
} 
*/

  String? overview;
  List<DeeplinkDiseaseDetailModelDetailsList?>? list;
  List<DeeplinkDiseaseDetailModelDetailsAddOns?>? addOns;
  String? svyasa;
  List<DeeplinkDiseaseDetailModelDetailsHowtoproceed?>? howtoproceed;

  DeeplinkDiseaseDetailModelDetails({
    this.overview,
    this.list,
    this.addOns,
    this.svyasa,
    this.howtoproceed,
  });
  DeeplinkDiseaseDetailModelDetails.fromJson(Map<String, dynamic> json) {
    overview = json['overview']?.toString();
    if (json['list'] != null) {
      final v = json['list'];
      final arr0 = <DeeplinkDiseaseDetailModelDetailsList>[];
      v.forEach((v) {
        arr0.add(DeeplinkDiseaseDetailModelDetailsList.fromJson(v));
      });
      list = arr0;
    }
    if (json['add-ons'] != null) {
      final v = json['add-ons'];
      final arr0 = <DeeplinkDiseaseDetailModelDetailsAddOns>[];
      v.forEach((v) {
        arr0.add(DeeplinkDiseaseDetailModelDetailsAddOns.fromJson(v));
      });
      addOns = arr0;
    }
    svyasa = json['svyasa']?.toString();
    if (json['howtoproceed'] != null) {
      final v = json['howtoproceed'];
      final arr0 = <DeeplinkDiseaseDetailModelDetailsHowtoproceed>[];
      v.forEach((v) {
        arr0.add(DeeplinkDiseaseDetailModelDetailsHowtoproceed.fromJson(v));
      });
      howtoproceed = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['overview'] = overview;
    if (list != null) {
      final v = list;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['list'] = arr0;
    }
    if (addOns != null) {
      final v = addOns;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['add-ons'] = arr0;
    }
    data['svyasa'] = svyasa;
    if (howtoproceed != null) {
      final v = howtoproceed;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['howtoproceed'] = arr0;
    }
    return data;
  }
}

class DeeplinkDiseaseDetailModelAbout {
/*
{
  "type": "text",
  "data": "In today’s fast-paced world, stress is a constant companion. And guess what comes hand in hand with stress? Yes, Anxiety. Living with Anxiety can be challenging. It’s not just a state of mind, it has an impact on bodily responses. Here’s the thing. Your body can’t tell the difference between a mental threat and a physical threat. So, when you imagine stressful situations like looming deadlines, your body treats it like it’s really under attack – like a bear is chasing it, for instance. In such a perceived fight or flight situation, the body releases stress hormones like adrenaline, noradrenaline and cortisol internally."
} 
*/

  String? type;
  String? data;

  DeeplinkDiseaseDetailModelAbout({
    this.type,
    this.data,
  });
  DeeplinkDiseaseDetailModelAbout.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    data = json['data']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['data'] = this.data;
    return data;
  }
}

class DeeplinkDiseaseDetailModel {
/*
{
  "about": [
    {
      "type": "text",
      "data": "In today’s fast-paced world, stress is a constant companion. And guess what comes hand in hand with stress? Yes, Anxiety. Living with Anxiety can be challenging. It’s not just a state of mind, it has an impact on bodily responses. Here’s the thing. Your body can’t tell the difference between a mental threat and a physical threat. So, when you imagine stressful situations like looming deadlines, your body treats it like it’s really under attack – like a bear is chasing it, for instance. In such a perceived fight or flight situation, the body releases stress hormones like adrenaline, noradrenaline and cortisol internally."
    }
  ],
  "details": {
    "overview": "Our Anxiety Disorder program is inclusive and open to all. There are no restrictions based on age, gender or body-type.. Our program offers Daily Online Practice with compassionate, trained and professional experts.",
    "list": [
      {
        "icon": "https://stg-content.aayu.live/healing/group55.png",
        "text": "Daily Online Practice"
      }
    ],
    "add-ons": [
      {
        "icon": "bbv",
        "text": "1-on-1 Doctor Consultation"
      }
    ],
    "svyasa": "We can write 2 - 3 lines about the s.-vyasa and science backed research and decaded of practice. We should also mention about s-vyasa core speciality. Also mention about the years of experience in the wellness space",
    "howtoproceed": [
      {
        "image": "dnd",
        "title": "Choose Program Preferences",
        "description": "Choose your daily programs (30/60 mins) based on your preferences"
      }
    ]
  },
  "benefits": [
    {
      "icon": "https://stg-content.aayu.live/healing/group55.png",
      "text": "Induces relaxation in body and mind"
    }
  ]
} 
*/

  List<DeeplinkDiseaseDetailModelAbout?>? about;
  DeeplinkDiseaseDetailModelDetails? details;
  List<DeeplinkDiseaseDetailModelBenefits?>? benefits;

  DeeplinkDiseaseDetailModel({
    this.about,
    this.details,
    this.benefits,
  });
  DeeplinkDiseaseDetailModel.fromJson(Map<String, dynamic> json) {
    if (json['about'] != null) {
      final v = json['about'];
      final arr0 = <DeeplinkDiseaseDetailModelAbout>[];
      v.forEach((v) {
        arr0.add(DeeplinkDiseaseDetailModelAbout.fromJson(v));
      });
      about = arr0;
    }
    details = (json['details'] != null)
        ? DeeplinkDiseaseDetailModelDetails.fromJson(json['details'])
        : null;
    if (json['benefits'] != null) {
      final v = json['benefits'];
      final arr0 = <DeeplinkDiseaseDetailModelBenefits>[];
      v.forEach((v) {
        arr0.add(DeeplinkDiseaseDetailModelBenefits.fromJson(v));
      });
      benefits = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (about != null) {
      final v = about;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['about'] = arr0;
    }
    if (details != null) {
      data['details'] = details!.toJson();
    }
    if (benefits != null) {
      final v = benefits;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['benefits'] = arr0;
    }
    return data;
  }
}
