///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DiseaseDetailsRequestDisease {
/*
{
  "diseaseId": "1"
} 
*/

  String? diseaseId;

  DiseaseDetailsRequestDisease({
    this.diseaseId,
  });
  DiseaseDetailsRequestDisease.fromJson(Map<String, dynamic> json) {
    diseaseId = json['diseaseId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['diseaseId'] = diseaseId;
    return data;
  }
}

class DiseaseDetailsRequest {
/*
{
  "disease": [
    {
      "diseaseId": "1"
    }
  ]
} 
*/

  List<DiseaseDetailsRequestDisease?>? disease;

  DiseaseDetailsRequest({
    this.disease,
  });
  DiseaseDetailsRequest.fromJson(Map<String, dynamic> json) {
    if (json['disease'] != null) {
      final v = json['disease'];
      final arr0 = <DiseaseDetailsRequestDisease>[];
      v.forEach((v) {
        arr0.add(DiseaseDetailsRequestDisease.fromJson(v));
      });
      disease = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (disease != null) {
      final v = disease;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['disease'] = arr0;
    }
    return data;
  }
}
