///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FollowupAssessmentResponsePostAssessmentSubjective {
/*
{
  "text": "My life is absolutely amazing! ",
  "weightage": "",
  "selected": false,
  "responseText": ""
} 
*/

  String? text;
  String? weightage;
  bool? selected;
  String? responseText;
  String? childId;

  FollowupAssessmentResponsePostAssessmentSubjective({
    this.text,
    this.weightage,
    this.selected,
    this.responseText,
    this.childId,
  });
  FollowupAssessmentResponsePostAssessmentSubjective.fromJson(
      Map<String, dynamic> json) {
    text = json['text']?.toString();
    weightage = json['weightage']?.toString();
    selected = json['selected'];
    responseText = json['responseText']?.toString();
    childId = json['childId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['text'] = text;
    data['weightage'] = weightage;
    data['selected'] = selected;
    data['responseText'] = responseText;
    data['childId'] = childId;
    return data;
  }
}

class FollowupAssessmentResponsePostAssessment {
/*
{
  "questionId": "936bb7a4-9472-4534-a941-d229118e348a",
  "question": "How would you describe your quality of life?",
  "priority": 0,
  "assessmentType": "followup assessment",
  "questionType": "subjective assessment",
  "objective": null,
  "subjective": [
    {
      "text": "My life is absolutely amazing! ",
      "weightage": "",
      "selected": false,
      "responseText": ""
    }
  ],
  "generalResponse": null,
  "isCompleted": false
} 
*/

  String? questionId;
  String? question;
  String? masterId;
  int? priority;
  String? assessmentType;
  String? questionType;
  String? categoryId;
  String? objective;
  List<FollowupAssessmentResponsePostAssessmentSubjective?>? subjective;
  String? generalResponse;
  bool? isCompleted;

  FollowupAssessmentResponsePostAssessment({
    this.questionId,
    this.question,
    this.masterId,
    this.priority,
    this.assessmentType,
    this.questionType,
    this.categoryId,
    this.objective,
    this.subjective,
    this.generalResponse,
    this.isCompleted,
  });
  FollowupAssessmentResponsePostAssessment.fromJson(Map<String, dynamic> json) {
    questionId = json['questionId']?.toString();
    question = json['question']?.toString();
    priority = json['priority']?.toInt();
    masterId = json['masterId']?.toString();
    assessmentType = json['assessmentType']?.toString();
    questionType = json['questionType']?.toString();
    categoryId = json['categoryId']?.toString();
    objective = json['objective']?.toString();
    if (json['subjective'] != null) {
      final v = json['subjective'];
      final arr0 = <FollowupAssessmentResponsePostAssessmentSubjective>[];
      v.forEach((v) {
        arr0.add(
            FollowupAssessmentResponsePostAssessmentSubjective.fromJson(v));
      });
      subjective = arr0;
    }
    generalResponse = json['generalResponse']?.toString();
    isCompleted = json['isCompleted'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['questionId'] = questionId;
    data['question'] = question;
    data['masterId'] = masterId;
    data['priority'] = priority;
    data['assessmentType'] = assessmentType;
    data['questionType'] = questionType;
    data['categoryId'] = categoryId;
    data['objective'] = objective;
    if (subjective != null) {
      final v = subjective;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['subjective'] = arr0;
    }
    data['generalResponse'] = generalResponse;
    data['isCompleted'] = isCompleted;
    return data;
  }
}

class FollowupAssessmentResponse {
/*
{
  "postAssessment": {
    "questionId": "936bb7a4-9472-4534-a941-d229118e348a",
    "question": "How would you describe your quality of life?",
    "priority": 0,
    "assessmentType": "followup assessment",
    "questionType": "subjective assessment",
    "objective": null,
    "subjective": [
      {
        "text": "My life is absolutely amazing! ",
        "weightage": "",
        "selected": false,
        "responseText": ""
      }
    ],
    "generalResponse": null,
    "isCompleted": false
  }
} 
*/

  FollowupAssessmentResponsePostAssessment? postAssessment;

  FollowupAssessmentResponse({
    this.postAssessment,
  });
  FollowupAssessmentResponse.fromJson(Map<String, dynamic> json) {
    postAssessment = (json['postAssessment'] != null)
        ? FollowupAssessmentResponsePostAssessment.fromJson(
            json['postAssessment'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (postAssessment != null) {
      data['postAssessment'] = postAssessment!.toJson();
    }
    return data;
  }
}
