///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HealthCardModelListOfBlocks {
/*
{
  "title": "Nutrition",
  "score": 98,
  "color": "#3034894"
} 
*/

  String? title;
  int? score;
  String? color;

  HealthCardModelListOfBlocks({
    this.title,
    this.score,
    this.color,
  });
  HealthCardModelListOfBlocks.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    score = json['score']?.toInt();
    color = json['color']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['score'] = score;
    data['color'] = color;
    return data;
  }
}

class HealthCardModel {
/*
{
  "healthScore": 48,
  "listOfBlocks": [
    {
      "title": "Nutrition",
      "score": 98,
      "color": "#3034894"
    }
  ]
} 
*/

  int? healthScore;
  List<HealthCardModelListOfBlocks?>? listOfBlocks;

  HealthCardModel({
    this.healthScore,
    this.listOfBlocks,
  });
  HealthCardModel.fromJson(Map<String, dynamic> json) {
    healthScore = json['healthScore']?.toInt();
    if (json['listOfBlocks'] != null) {
      final v = json['listOfBlocks'];
      final arr0 = <HealthCardModelListOfBlocks>[];
      v.forEach((v) {
        arr0.add(HealthCardModelListOfBlocks.fromJson(v));
      });
      listOfBlocks = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['healthScore'] = healthScore;
    if (listOfBlocks != null) {
      final v = listOfBlocks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['listOfBlocks'] = arr0;
    }
    return data;
  }
}
