///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HealingListResponseDiseasesImage {
/*
{
  "imageUrl": "/healing/heartdisease.png",
  "width": 70.5,
  "height": 108.2
} 
*/

  String? imageUrl;
  double? width;
  double? height;

  HealingListResponseDiseasesImage({
    this.imageUrl,
    this.width,
    this.height,
  });
  HealingListResponseDiseasesImage.fromJson(Map<String, dynamic> json) {
    imageUrl = json['imageUrl']?.toString();
    width = json['width']?.toDouble();
    height = json['height']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['imageUrl'] = imageUrl;
    data['width'] = width;
    data['height'] = height;
    return data;
  }
}

class HealingListResponseDiseases {
/*
{
  "diseaseId": "cf7f7590-2042-11ec-aa8f-ed884725c287",
  "disease": "heart disease",
  "image": {
    "imageUrl": "/healing/heartdisease.png",
    "width": 70.5,
    "height": 108.2
  }
} 
*/

  String? diseaseId;
  String? disease;
  HealingListResponseDiseasesImage? image;
  bool? isSelected;
  bool? isActive;

  HealingListResponseDiseases({
    this.diseaseId,
    this.disease,
    this.image,
  });
  HealingListResponseDiseases.fromJson(Map<String, dynamic> json) {
    diseaseId = json['diseaseId']?.toString();
    disease = json['disease']?.toString();
    image = (json['image'] != null)
        ? HealingListResponseDiseasesImage.fromJson(json['image'])
        : null;
    isSelected = json['isSelected'] ?? false;
    isActive = json['isActive'] ?? false;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['diseaseId'] = diseaseId;
    data['disease'] = disease;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    data['isSelected'] = isSelected ?? false;
    data['isActive'] = isActive ?? false;
    return data;
  }
}

class HealingListResponsePageContent {
/*
{
  "title": "Healing & You",
  "desc": "Our healing programs are holistic in their approach, backed by decades of scientific research and surprisingly simple to follow.",
  "helpText": "Tell us, what you need help with.",
  "backgroundImage": "https://resetcontent.s3.ap-south-1.amazonaws.com/healing/healing.png"
} 
*/

  String? title;
  String? desc;
  String? helpText;
  String? backgroundImage;
  String? videoURL;
  bool? playVideo;

  HealingListResponsePageContent({
    this.title,
    this.desc,
    this.helpText,
    this.backgroundImage,
    this.videoURL,
    this.playVideo,
  });
  HealingListResponsePageContent.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    desc = json['desc']?.toString();
    helpText = json['helpText']?.toString();
    backgroundImage = json['backgroundImage']?.toString();
    videoURL = json['videoURL']?.toString();
    playVideo = json['playVideo'] ?? false;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['desc'] = desc;
    data['helpText'] = helpText;
    data['backgroundImage'] = backgroundImage;
    data['videoURL'] = videoURL;
    data['playVideo'] = playVideo ?? false;
    return data;
  }
}

class HealingListResponse {
/*
{
  "pageContent": {
    "title": "Healing & You",
    "desc": "Our healing programs are holistic in their approach, backed by decades of scientific research and surprisingly simple to follow.",
    "helpText": "Tell us, what you need help with.",
    "backgroundImage": "https://resetcontent.s3.ap-south-1.amazonaws.com/healing/healing.png"
  },
  "diseases": [
    {
      "diseaseId": "cf7f7590-2042-11ec-aa8f-ed884725c287",
      "disease": "heart disease",
      "image": {
        "imageUrl": "/healing/heartdisease.png",
        "width": 70.5,
        "height": 108.2
      }
    }
  ]
} 
*/

  HealingListResponsePageContent? pageContent;
  List<HealingListResponseDiseases?>? diseases;

  HealingListResponse({
    this.pageContent,
    this.diseases,
  });
  HealingListResponse.fromJson(Map<String, dynamic> json) {
    pageContent = (json['pageContent'] != null)
        ? HealingListResponsePageContent.fromJson(json['pageContent'])
        : null;
    if (json['diseases'] != null) {
      final v = json['diseases'];
      final arr0 = <HealingListResponseDiseases>[];
      v.forEach((v) {
        arr0.add(HealingListResponseDiseases.fromJson(v));
      });
      diseases = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pageContent != null) {
      data['pageContent'] = pageContent!.toJson();
    }
    if (diseases != null) {
      final v = diseases;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['diseases'] = arr0;
    }
    return data;
  }
}
