///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SelectedDiseaseDetailsRequestDisease {
/*
{
  "diseaseId": "1"
} 
*/

  String? diseaseId;
  String? diseaseName;

  SelectedDiseaseDetailsRequestDisease({
    this.diseaseId,
  });
  SelectedDiseaseDetailsRequestDisease.fromJson(Map<String, dynamic> json) {
    diseaseId = json['diseaseId']?.toString();
    diseaseName = json['diseaseName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['diseaseId'] = diseaseId;
    data['diseaseName'] = diseaseName;
    return data;
  }
}

class SelectedDiseaseDetailsRequest {
/*
{
  "disease": [
    {
      "diseaseId": "1"
    }
  ]
} 
*/

  List<SelectedDiseaseDetailsRequestDisease?>? disease;

  SelectedDiseaseDetailsRequest({
    this.disease,
  });
  SelectedDiseaseDetailsRequest.fromJson(Map<String, dynamic> json) {
    if (json['disease'] != null) {
      final v = json['disease'];
      final arr0 = <SelectedDiseaseDetailsRequestDisease>[];
      v.forEach((v) {
        arr0.add(SelectedDiseaseDetailsRequestDisease.fromJson(v));
      });
      disease = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (disease != null) {
      final v = disease;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['disease'] = arr0;
    }
    return data;
  }
}
