///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserIdentificationResponseIdentificationDetails {
/*
{
  "userIdentification": "05d4f150-d697-11ec-a672-b51a70d749d6",
  "startDate": "2022-05-18T00:00:00.000Z",
  "expiryDate": "2022-06-08T00:00:00.000Z"
} 
*/

  String? userIdentification;
  String? startDate;
  String? expiryDate;

  UserIdentificationResponseIdentificationDetails({
    this.userIdentification,
    this.startDate,
    this.expiryDate,
  });
  UserIdentificationResponseIdentificationDetails.fromJson(Map<String, dynamic> json) {
    userIdentification = json['userIdentification']?.toString();
    startDate = json['startDate']?.toString();
    expiryDate = json['expiryDate']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userIdentification'] = userIdentification;
    data['startDate'] = startDate;
    data['expiryDate'] = expiryDate;
    return data;
  }
}

class UserIdentificationResponse {
/*
{
  "identificationDetails": {
    "userIdentification": "05d4f150-d697-11ec-a672-b51a70d749d6",
    "startDate": "2022-05-18T00:00:00.000Z",
    "expiryDate": "2022-06-08T00:00:00.000Z"
  }
} 
*/

  UserIdentificationResponseIdentificationDetails? identificationDetails;

  UserIdentificationResponse({
    this.identificationDetails,
  });
  UserIdentificationResponse.fromJson(Map<String, dynamic> json) {
    identificationDetails = (json['identificationDetails'] != null) ? UserIdentificationResponseIdentificationDetails.fromJson(json['identificationDetails']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (identificationDetails != null) {
      data['identificationDetails'] = identificationDetails!.toJson();
    }
    return data;
  }
}

