///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DidYouKnowModelDetails {
/*
{
  "didYouKnowId": "e20a13f0-eaa8-11ed-8225-075a1b3850b2",
  "didYouKnow": "Someone busier than you is running right now."
} 
*/

  String? didYouKnowId;
  String? didYouKnow;

  DidYouKnowModelDetails({
    this.didYouKnowId,
    this.didYouKnow,
  });
  DidYouKnowModelDetails.fromJson(Map<String, dynamic> json) {
    didYouKnowId = json['didYouKnowId']?.toString();
    didYouKnow = json['didYouKnow']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['didYouKnowId'] = didYouKnowId;
    data['didYouKnow'] = didYouKnow;
    return data;
  }
}

class DidYouKnowModel {
/*
{
  "details": {
    "didYouKnowId": "e20a13f0-eaa8-11ed-8225-075a1b3850b2",
    "didYouKnow": "Someone busier than you is running right now."
  }
} 
*/

  DidYouKnowModelDetails? details;

  DidYouKnowModel({
    this.details,
  });
  DidYouKnowModel.fromJson(Map<String, dynamic> json) {
    details = (json['details'] != null && (json['details'] is Map)) ? DidYouKnowModelDetails.fromJson(json['details']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (details != null) {
      data['details'] = details!.toJson();
    }
    return data;
  }
}
