import 'package:aayu/model/grow/grow.page.content.model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HomePageTopSectionResponseDetailsInApp {
/*
{
  "type": "DOCTOR_CONSULTATION",
  "bannerId": "",
  "bannerImage": ""
} 
*/

  String? type;
  String? bannerId;
  String? bannerImage;
  String? referenceId;

  HomePageTopSectionResponseDetailsInApp({
    this.type,
    this.bannerId,
    this.bannerImage,
    this.referenceId,
  });
  HomePageTopSectionResponseDetailsInApp.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    bannerId = json['bannerId']?.toString();
    bannerImage = json['bannerImage']?.toString();
    referenceId = json['referenceId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['bannerId'] = bannerId;
    data['bannerImage'] = bannerImage;
    data['referenceId'] = referenceId;
    return data;
  }
}

class HomePageTopSectionResponseDetailsBanner {
/*
{
  "bannerId": "1",
  "bannerImage": "https://stg-content.aayu.live/aayu/app/banners/yogaeventbanner.png",
  "ctaType": "",
  "bannerType": "Video",
  "url": "",
  "passUserId": false
} 
*/

  String? bannerId;
  String? bannerImage;
  String? ctaType;
  String? bannerType;
  String? url;
  bool? passUserId;

  HomePageTopSectionResponseDetailsBanner({
    this.bannerId,
    this.bannerImage,
    this.ctaType,
    this.bannerType,
    this.url,
    this.passUserId,
  });
  HomePageTopSectionResponseDetailsBanner.fromJson(Map<String, dynamic> json) {
    bannerId = json['bannerId']?.toString();
    bannerImage = json['bannerImage']?.toString();
    ctaType = json['ctaType']?.toString();
    bannerType = json['bannerType']?.toString();
    url = json['url']?.toString();
    passUserId = json['passUserId'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bannerId'] = bannerId;
    data['bannerImage'] = bannerImage;
    data['ctaType'] = ctaType;
    data['bannerType'] = bannerType;
    data['url'] = url;
    data['passUserId'] = passUserId;
    return data;
  }
}

class HomePageTopSectionResponseDetailsPoseCorrection {
/*
{
  "headerText": "POSE CORRECTION",
  "bannerImage": "https://stg-content.aayu.live/aayu/app/posecorrection/compressedPoseCorrection.jpg",
  "description": "Improve your strength and stability with our new"
} 
*/

  String? headerText;
  String? bannerImage;
  String? description;

  HomePageTopSectionResponseDetailsPoseCorrection({
    this.headerText,
    this.bannerImage,
    this.description,
  });
  HomePageTopSectionResponseDetailsPoseCorrection.fromJson(Map<String, dynamic> json) {
    headerText = json['headerText']?.toString();
    bannerImage = json['bannerImage']?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['headerText'] = headerText;
    data['bannerImage'] = bannerImage;
    data['description'] = description;
    return data;
  }
}

class HomePageTopSectionResponseDetailsSleep {
/*
{
  "countDownTimer": 25
} 
*/

  int? countDownTimer;

  HomePageTopSectionResponseDetailsSleep({
    this.countDownTimer,
  });
  HomePageTopSectionResponseDetailsSleep.fromJson(Map<String, dynamic> json) {
    countDownTimer = json['countDownTimer']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['countDownTimer'] = countDownTimer;
    return data;
  }
}

class HomePageTopSectionResponseDetailsProgram {
/*
{
  "diseaseId": "",
  "diseaseName": "",
  "diseaseImage": ""
} 
*/

  String? diseaseId;
  String? diseaseName;
  String? diseaseImage;

  HomePageTopSectionResponseDetailsProgram({
    this.diseaseId,
    this.diseaseName,
    this.diseaseImage,
  });
  HomePageTopSectionResponseDetailsProgram.fromJson(Map<String, dynamic> json) {
    diseaseId = json['diseaseId']?.toString();
    diseaseName = json['diseaseName']?.toString();
    diseaseImage = json['diseaseImage']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['diseaseId'] = diseaseId;
    data['diseaseName'] = diseaseName;
    data['diseaseImage'] = diseaseImage;
    return data;
  }
}

class HomePageTopSectionResponseDetailsSequence {
/*
{
  "type": "poseCorrection",
  "sequenceId": "",
  "template": null
} 
*/

  String? type;
  String? sequenceId;
  String? template;

  HomePageTopSectionResponseDetailsSequence({
    this.type,
    this.sequenceId,
    this.template,
  });
  HomePageTopSectionResponseDetailsSequence.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    sequenceId = json['sequenceId']?.toString();
    template = json['template']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['sequenceId'] = sequenceId;
    data['template'] = template;
    return data;
  }
}

class HomePageTopSectionResponseDetails {
/*
{
  "sequence": [
    {
      "type": "poseCorrection",
      "sequenceId": "",
      "template": null
    }
  ],
  "sectionType": "Program",
  "program": {
    "diseaseId": "",
    "diseaseName": "",
    "diseaseImage": ""
  },
  "content": [
    {
      "contentId": "21dff4eb-50e6-40b9-b136-cd96588b1882",
      "contentName": "Yoga For The Skin",
      "contentImage": "https://stg-content.aayu.live/Yoga/Video/080422/YogaForTheSkin/YogaForTheSkin_1125x1620.jpg",
      "contentType": "Video",
      "contentPath": "https://stg-content.aayu.live/Yoga/Video/080422/YogaForTheSkin/YogaForTheSkin.mp4",
      "playBGImage": "https://stg-content.aayu.live",
      "isFavourite": false,
      "artist": {
        "artistId": "623c63-79af00707-3b0713b13",
        "artistName": "Aayu",
        "artistImage": "https://stg-content.aayu.live/Music/artistimages/images3x/AayuImage.png"
      },
      "metaData": {
        "duration": "15 min",
        "rating": 4.4,
        "views": "5k",
        "multiSeries": false,
        "tags": [
          {
            "displayTagId": "1",
            "displayTag": " Health"
          }
        ],
        "isPremium": false,
        "contentTag": "Pain Management"
      }
    }
  ],
  "sleep": {
    "countDownTimer": 25
  },
  "poseCorrection": {
    "headerText": "POSE CORRECTION",
    "bannerImage": "https://stg-content.aayu.live/aayu/app/posecorrection/compressedPoseCorrection.jpg",
    "description": "Improve your strength and stability with our new"
  },
  "banner": [
    {
      "bannerId": "1",
      "bannerImage": "https://stg-content.aayu.live/aayu/app/banners/yogaeventbanner.png",
      "ctaType": "",
      "bannerType": "Video",
      "url": "",
      "passUserId": false
    }
  ],
  "inApp": [
    {
      "type": "DOCTOR_CONSULTATION",
      "bannerId": "",
      "bannerImage": ""
    }
  ]
} 
*/

  List<HomePageTopSectionResponseDetailsSequence?>? sequence;
  String? sectionType;
  HomePageTopSectionResponseDetailsProgram? program;
  List<Content?>? content;
  HomePageTopSectionResponseDetailsSleep? sleep;
  HomePageTopSectionResponseDetailsPoseCorrection? poseCorrection;
  List<HomePageTopSectionResponseDetailsBanner?>? banner;
  List<HomePageTopSectionResponseDetailsInApp?>? inApp;

  HomePageTopSectionResponseDetails({
    this.sequence,
    this.sectionType,
    this.program,
    this.content,
    this.sleep,
    this.poseCorrection,
    this.banner,
    this.inApp,
  });
  HomePageTopSectionResponseDetails.fromJson(Map<String, dynamic> json) {
  if (json['sequence'] != null) {
  final v = json['sequence'];
  final arr0 = <HomePageTopSectionResponseDetailsSequence>[];
  v.forEach((v) {
  arr0.add(HomePageTopSectionResponseDetailsSequence.fromJson(v));
  });
    sequence = arr0;
    }
    sectionType = json['sectionType']?.toString();
    program = (json['program'] != null) ? HomePageTopSectionResponseDetailsProgram.fromJson(json['program']) : null;
  if (json['content'] != null) {
  final v = json['content'];
  final arr0 = <Content>[];
  v.forEach((v) {
  arr0.add(Content.fromJson(v));
  });
    content = arr0;
    }
    sleep = (json['sleep'] != null) ? HomePageTopSectionResponseDetailsSleep.fromJson(json['sleep']) : null;
    poseCorrection = (json['poseCorrection'] != null) ? HomePageTopSectionResponseDetailsPoseCorrection.fromJson(json['poseCorrection']) : null;
  if (json['banner'] != null) {
  final v = json['banner'];
  final arr0 = <HomePageTopSectionResponseDetailsBanner>[];
  v.forEach((v) {
  arr0.add(HomePageTopSectionResponseDetailsBanner.fromJson(v));
  });
    banner = arr0;
    }
  if (json['inApp'] != null) {
  final v = json['inApp'];
  final arr0 = <HomePageTopSectionResponseDetailsInApp>[];
  v.forEach((v) {
  arr0.add(HomePageTopSectionResponseDetailsInApp.fromJson(v));
  });
    inApp = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (sequence != null) {
      final v = sequence;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['sequence'] = arr0;
    }
    data['sectionType'] = sectionType;
    if (program != null) {
      data['program'] = program!.toJson();
    }
    if (content != null) {
      final v = content;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['content'] = arr0;
    }
    if (sleep != null) {
      data['sleep'] = sleep!.toJson();
    }
    if (poseCorrection != null) {
      data['poseCorrection'] = poseCorrection!.toJson();
    }
    if (banner != null) {
      final v = banner;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['banner'] = arr0;
    }
    if (inApp != null) {
      final v = inApp;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['inApp'] = arr0;
    }
    return data;
  }
}

class HomePageTopSectionResponse {
/*
{
  "details": {
    "sequence": [
      {
        "type": "poseCorrection",
        "sequenceId": "",
        "template": null
      }
    ],
    "sectionType": "Program",
    "program": {
      "diseaseId": "",
      "diseaseName": "",
      "diseaseImage": ""
    },
    "content": [
      {
        "contentId": "21dff4eb-50e6-40b9-b136-cd96588b1882",
        "contentName": "Yoga For The Skin",
        "contentImage": "https://stg-content.aayu.live/Yoga/Video/080422/YogaForTheSkin/YogaForTheSkin_1125x1620.jpg",
        "contentType": "Video",
        "contentPath": "https://stg-content.aayu.live/Yoga/Video/080422/YogaForTheSkin/YogaForTheSkin.mp4",
        "playBGImage": "https://stg-content.aayu.live",
        "isFavourite": false,
        "artist": {
          "artistId": "623c63-79af00707-3b0713b13",
          "artistName": "Aayu",
          "artistImage": "https://stg-content.aayu.live/Music/artistimages/images3x/AayuImage.png"
        },
        "metaData": {
          "duration": "15 min",
          "rating": 4.4,
          "views": "5k",
          "multiSeries": false,
          "tags": [
            {
              "displayTagId": "1",
              "displayTag": " Health"
            }
          ],
          "isPremium": false,
          "contentTag": "Pain Management"
        }
      }
    ],
    "sleep": {
      "countDownTimer": 25
    },
    "poseCorrection": {
      "headerText": "POSE CORRECTION",
      "bannerImage": "https://stg-content.aayu.live/aayu/app/posecorrection/compressedPoseCorrection.jpg",
      "description": "Improve your strength and stability with our new"
    },
    "banner": [
      {
        "bannerId": "1",
        "bannerImage": "https://stg-content.aayu.live/aayu/app/banners/yogaeventbanner.png",
        "ctaType": "",
        "bannerType": "Video",
        "url": "",
        "passUserId": false
      }
    ],
    "inApp": [
      {
        "type": "DOCTOR_CONSULTATION",
        "bannerId": "",
        "bannerImage": ""
      }
    ]
  }
} 
*/

  HomePageTopSectionResponseDetails? details;

  HomePageTopSectionResponse({
    this.details,
  });
  HomePageTopSectionResponse.fromJson(Map<String, dynamic> json) {
    details = (json['details'] != null) ? HomePageTopSectionResponseDetails.fromJson(json['details']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (details != null) {
      data['details'] = details!.toJson();
    }
    return data;
  }
}
