///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpdateProfileResponse {
/*
{
  "userId": "1234567890",
  "updatedAt": "2022-02-23T05:23:15.498Z"
} 
*/

  String? userId;
  String? updatedAt;

  UpdateProfileResponse({
    this.userId,
    this.updatedAt,
  });
  UpdateProfileResponse.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['updatedAt'] = updatedAt;
    return data;
  }
}
