///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubscriptionDetailsResponseSubscriptionDetailsEpochTimes {
/*
{
  "subscribeDate": 1670336787000,
  "expiryDate": 1672928787000,
  "startDate": 1670544000000
} 
*/

  int? subscribeDate;
  int? expiryDate;
  int? startDate;

  SubscriptionDetailsResponseSubscriptionDetailsEpochTimes({
    this.subscribeDate,
    this.expiryDate,
    this.startDate,
  });
  SubscriptionDetailsResponseSubscriptionDetailsEpochTimes.fromJson(
      Map<String, dynamic> json) {
    subscribeDate = json['subscribeDate']?.toInt();
    expiryDate = json['expiryDate']?.toInt();
    startDate = json['startDate']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['subscribeDate'] = subscribeDate;
    data['expiryDate'] = expiryDate;
    data['startDate'] = startDate;
    return data;
  }
}

class SubscriptionDetailsResponseSubscriptionDetailsSilverAppBarImage {
/*
{
  "imageUrl": "https://stg-content.aayu.live/healing/arthiritis.png",
  "height": 115,
  "width": 72
} 
*/

  String? imageUrl;
  int? height;
  int? width;

  SubscriptionDetailsResponseSubscriptionDetailsSilverAppBarImage({
    this.imageUrl,
    this.height,
    this.width,
  });
  SubscriptionDetailsResponseSubscriptionDetailsSilverAppBarImage.fromJson(
      Map<String, dynamic> json) {
    imageUrl = json['imageUrl']?.toString();
    height = json['height']?.toInt();
    width = json['width']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['imageUrl'] = imageUrl;
    data['height'] = height;
    data['width'] = width;
    return data;
  }
}

class SubscriptionDetailsResponseSubscriptionDetailsSilverAppBar {
/*
{
  "title": "Arthritis Care",
  "textColor": "#F26C6E",
  "backgroundImage": "https://stg-content.aayu.live/healing/arthritis/arthritiscare.jpg",
  "image": {
    "imageUrl": "https://stg-content.aayu.live/healing/arthiritis.png",
    "height": 115,
    "width": 72
  }
} 
*/

  String? title;
  String? textColor;
  String? backgroundImage;
  SubscriptionDetailsResponseSubscriptionDetailsSilverAppBarImage? image;

  SubscriptionDetailsResponseSubscriptionDetailsSilverAppBar({
    this.title,
    this.textColor,
    this.backgroundImage,
    this.image,
  });
  SubscriptionDetailsResponseSubscriptionDetailsSilverAppBar.fromJson(
      Map<String, dynamic> json) {
    title = json['title']?.toString();
    textColor = json['textColor']?.toString();
    backgroundImage = json['backgroundImage']?.toString();
    image = (json['image'] != null)
        ? SubscriptionDetailsResponseSubscriptionDetailsSilverAppBarImage
            .fromJson(json['image'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['textColor'] = textColor;
    data['backgroundImage'] = backgroundImage;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    return data;
  }
}

class SubscriptionDetailsResponseSubscriptionDetailsDisease {
/*
{
  "diseaseId": "479c4820-c21c-11ec-8195-fb3d9a5f7244",
  "diseaseName": "Arthritis"
} 
*/

  String? diseaseId;
  String? diseaseName;

  SubscriptionDetailsResponseSubscriptionDetailsDisease({
    this.diseaseId,
    this.diseaseName,
  });
  SubscriptionDetailsResponseSubscriptionDetailsDisease.fromJson(
      Map<String, dynamic> json) {
    diseaseId = json['diseaseId']?.toString();
    diseaseName = json['diseaseName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['diseaseId'] = diseaseId;
    data['diseaseName'] = diseaseName;
    return data;
  }
}

class SubscriptionDetailsResponseSubscriptionDetails {
/*
{
  "subscriptionId": "f87ae030-7571-11ed-ab68-515ee8254622",
  "allowUpgrade":false,
  "subscribeVia": "HEALING",
  "subscribeDate": "2022-12-06",
  "expiryDate": "2023-01-05",
  "packageType": "MONTHLY",
  "status": "ACTIVE",
  "programId": "38804810-659f-11ed-b99e-013706bc0580",
  "disease": [
    {
      "diseaseId": "479c4820-c21c-11ec-8195-fb3d9a5f7244",
      "diseaseName": "Arthritis"
    }
  ],
  "silverAppBar": {
    "title": "Arthritis Care",
    "textColor": "#F26C6E",
    "backgroundImage": "https://stg-content.aayu.live/healing/arthritis/arthritiscare.jpg",
    "image": {
      "imageUrl": "https://stg-content.aayu.live/healing/arthiritis.png",
      "height": 115,
      "width": 72
    }
  },
  "duration": "30 mins",
  "period": "90 days",
  "startDate": "2022-12-09",
  "canStartProgram": false,
  "yogaTherapist": 0,
  "doctorConsult": 0,
  "enableRenew": false,
  "switchCount": 1,
  "canSwitchProgram": false,
  "allowPersonalCare": false,
  "epochTimes": {
    "subscribeDate": 1670336787000,
    "expiryDate": 1672928787000,
    "startDate": 1670544000000
  }
} 
*/

  String? subscriptionId;
  String? subscribeVia;
  String? subscribeDate;
  String? expiryDate;
  String? packageType;
  String? status;
  String? programId;
  List<SubscriptionDetailsResponseSubscriptionDetailsDisease?>? disease;
  SubscriptionDetailsResponseSubscriptionDetailsSilverAppBar? silverAppBar;
  String? duration;
  String? period;
  String? startDate;
  bool? canStartProgram;
  int? yogaTherapist;
  int? doctorConsult;
  bool? enableRenew;
  int? switchCount;
  bool? canSwitchProgram;
  bool? allowPersonalCare;
  bool? allowUpgrade;
  SubscriptionDetailsResponseSubscriptionDetailsEpochTimes? epochTimes;

  SubscriptionDetailsResponseSubscriptionDetails({
    this.subscriptionId,
    this.subscribeVia,
    this.subscribeDate,
    this.expiryDate,
    this.packageType,
    this.status,
    this.programId,
    this.disease,
    this.silverAppBar,
    this.duration,
    this.period,
    this.startDate,
    this.canStartProgram,
    this.yogaTherapist,
    this.doctorConsult,
    this.enableRenew,
    this.switchCount,
    this.canSwitchProgram,
    this.allowPersonalCare,
    this.epochTimes,
    this.allowUpgrade,
  });
  SubscriptionDetailsResponseSubscriptionDetails.fromJson(
      Map<String, dynamic> json) {
    allowUpgrade = json['allowUpgrade'] ?? false;
    subscriptionId = json['subscriptionId']?.toString();
    subscribeVia = json['subscribeVia']?.toString();
    subscribeDate = json['subscribeDate']?.toString();
    expiryDate = json['expiryDate']?.toString();
    packageType = json['packageType']?.toString();
    status = json['status']?.toString();
    programId = json['programId']?.toString();
    if (json['disease'] != null) {
      final v = json['disease'];
      final arr0 = <SubscriptionDetailsResponseSubscriptionDetailsDisease>[];
      v.forEach((v) {
        arr0.add(
            SubscriptionDetailsResponseSubscriptionDetailsDisease.fromJson(v));
      });
      disease = arr0;
    }
    silverAppBar = (json['silverAppBar'] != null)
        ? SubscriptionDetailsResponseSubscriptionDetailsSilverAppBar.fromJson(
            json['silverAppBar'])
        : null;
    duration = json['duration']?.toString();
    period = json['period']?.toString();
    startDate = json['startDate']?.toString();
    canStartProgram = json['canStartProgram'];
    yogaTherapist = json['yogaTherapist']?.toInt();
    doctorConsult = json['doctorConsult']?.toInt();
    enableRenew = json['enableRenew'];
    switchCount = json['switchCount']?.toInt();
    canSwitchProgram = json['canSwitchProgram'];
    allowPersonalCare = json['allowPersonalCare'];
    epochTimes = (json['epochTimes'] != null)
        ? SubscriptionDetailsResponseSubscriptionDetailsEpochTimes.fromJson(
            json['epochTimes'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['allowUpgrade'] = allowUpgrade;
    data['subscriptionId'] = subscriptionId;
    data['subscribeVia'] = subscribeVia;
    data['subscribeDate'] = subscribeDate;
    data['expiryDate'] = expiryDate;
    data['packageType'] = packageType;
    data['status'] = status;
    data['programId'] = programId;
    if (disease != null) {
      final v = disease;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['disease'] = arr0;
    }
    if (silverAppBar != null) {
      data['silverAppBar'] = silverAppBar!.toJson();
    }
    data['duration'] = duration;
    data['period'] = period;
    data['startDate'] = startDate;
    data['canStartProgram'] = canStartProgram;
    data['yogaTherapist'] = yogaTherapist;
    data['doctorConsult'] = doctorConsult;
    data['enableRenew'] = enableRenew;
    data['switchCount'] = switchCount;
    data['canSwitchProgram'] = canSwitchProgram;
    data['allowPersonalCare'] = allowPersonalCare;
    if (epochTimes != null) {
      data['epochTimes'] = epochTimes!.toJson();
    }
    return data;
  }
}

class SubscriptionDetailsResponse {
/*
{
  "subscriptionDetails": {
    "allowUpgrade":false,
    "subscriptionId": "f87ae030-7571-11ed-ab68-515ee8254622",
    "subscribeVia": "HEALING",
    "subscribeDate": "2022-12-06",
    "expiryDate": "2023-01-05",
    "packageType": "MONTHLY",
    "status": "ACTIVE",
    "programId": "38804810-659f-11ed-b99e-013706bc0580",
    "disease": [
      {
        "diseaseId": "479c4820-c21c-11ec-8195-fb3d9a5f7244",
        "diseaseName": "Arthritis"
      }
    ],
    "silverAppBar": {
      "title": "Arthritis Care",
      "textColor": "#F26C6E",
      "backgroundImage": "https://stg-content.aayu.live/healing/arthritis/arthritiscare.jpg",
      "image": {
        "imageUrl": "https://stg-content.aayu.live/healing/arthiritis.png",
        "height": 115,
        "width": 72
      }
    },
    "duration": "30 mins",
    "period": "90 days",
    "startDate": "2022-12-09",
    "canStartProgram": false,
    "yogaTherapist": 0,
    "doctorConsult": 0,
    "enableRenew": false,
    "switchCount": 1,
    "canSwitchProgram": false,
    "allowPersonalCare": false,
    "epochTimes": {
      "subscribeDate": 1670336787000,
      "expiryDate": 1672928787000,
      "startDate": 1670544000000
    }
  }
} 
*/

  SubscriptionDetailsResponseSubscriptionDetails? subscriptionDetails;

  SubscriptionDetailsResponse({
    this.subscriptionDetails,
  });
  SubscriptionDetailsResponse.fromJson(Map<String, dynamic> json) {
    subscriptionDetails = (json['subscriptionDetails'] != null)
        ? SubscriptionDetailsResponseSubscriptionDetails.fromJson(
            json['subscriptionDetails'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (subscriptionDetails != null) {
      data['subscriptionDetails'] = subscriptionDetails!.toJson();
    }
    return data;
  }
}
