///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubscriptionCommunicationModelDetailsItems {
/*
{
  "item": "Healing",
  "desc": "Access to personalised health management program.",
  "image": "https://stg-content.aayu.live/aayu/app/subscription/icons/healing.png"
} 
*/

  String? item;
  String? desc;
  String? image;

  SubscriptionCommunicationModelDetailsItems({
    this.item,
    this.desc,
    this.image,
  });
  SubscriptionCommunicationModelDetailsItems.fromJson(
      Map<String, dynamic> json) {
    item = json['item']?.toString();
    desc = json['desc']?.toString();
    image = json['image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['item'] = item;
    data['desc'] = desc;
    data['image'] = image;
    return data;
  }
}

class SubscriptionCommunicationModelDetails {
/*
{
  "section": "HERE'S WHAT YOU GET",
  "subTitle": "",
  "items": [
    {
      "item": "Healing",
      "desc": "Access to personalised health management program.",
      "image": "https://stg-content.aayu.live/aayu/app/subscription/icons/healing.png"
    }
  ]
} 
*/

  String? section;
  String? subTitle;
  List<SubscriptionCommunicationModelDetailsItems?>? items;

  SubscriptionCommunicationModelDetails({
    this.section,
    this.subTitle,
    this.items,
  });
  SubscriptionCommunicationModelDetails.fromJson(Map<String, dynamic> json) {
    section = json['section']?.toString();
    subTitle = json['subTitle']?.toString();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <SubscriptionCommunicationModelDetailsItems>[];
      v.forEach((v) {
        arr0.add(SubscriptionCommunicationModelDetailsItems.fromJson(v));
      });
      items = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['section'] = section;
    data['subTitle'] = subTitle;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    return data;
  }
}

class SubscriptionCommunicationModel {
/*
{
  "details": [
    {
      "section": "HERE'S WHAT YOU GET",
      "subTitle": "",
      "items": [
        {
          "item": "Healing",
          "desc": "Access to personalised health management program.",
          "image": "https://stg-content.aayu.live/aayu/app/subscription/icons/healing.png"
        }
      ]
    }
  ]
} 
*/

  List<SubscriptionCommunicationModelDetails?>? details;

  SubscriptionCommunicationModel({
    this.details,
  });
  SubscriptionCommunicationModel.fromJson(Map<String, dynamic> json) {
    if (json['details'] != null) {
      final v = json['details'];
      final arr0 = <SubscriptionCommunicationModelDetails>[];
      v.forEach((v) {
        arr0.add(SubscriptionCommunicationModelDetails.fromJson(v));
      });
      details = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (details != null) {
      final v = details;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['details'] = arr0;
    }
    return data;
  }
}
