///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubscriptionCheckResponseSubscriptionDetailsEpochTimes {
/*
{
  "subscribeDate": 1670284800000,
  "expiryDate": 1672876800000,
  "startDate": 1672876800000
} 
*/

  int? subscribeDate;
  int? expiryDate;
  String? startDate;

  SubscriptionCheckResponseSubscriptionDetailsEpochTimes({
    this.subscribeDate,
    this.expiryDate,
    this.startDate,
  });
  SubscriptionCheckResponseSubscriptionDetailsEpochTimes.fromJson(Map<String, dynamic> json) {
    subscribeDate = json['subscribeDate']?.toInt();
    expiryDate = json['expiryDate']?.toInt();
    startDate = json['startDate']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['subscribeDate'] = subscribeDate;
    data['expiryDate'] = expiryDate;
    data['startDate'] = startDate;
    return data;
  }
}

class SubscriptionCheckResponseSubscriptionDetailsDisease {
/*
{
  "diseaseId": "a721f7a0-c20c-11ec-8195-fb3d9a5f7244",
  "diseaseName": "Heart Disease"
} 
*/

  String? diseaseId;
  String? diseaseName;

  SubscriptionCheckResponseSubscriptionDetailsDisease({
    this.diseaseId,
    this.diseaseName,
  });
  SubscriptionCheckResponseSubscriptionDetailsDisease.fromJson(Map<String, dynamic> json) {
    diseaseId = json['diseaseId']?.toString();
    diseaseName = json['diseaseName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['diseaseId'] = diseaseId;
    data['diseaseName'] = diseaseName;
    return data;
  }
}

class SubscriptionCheckResponseSubscriptionDetails {
/*
{
  "subscriptionId": "f87ae030-7571-11ed-ab68-515ee8254622",
  "subscribeVia": "HEALING",
  "userId": "3ae2cbc0-6c87-11ed-943c-5faea9fec6a5",
  "subscribeDate": "2022-12-06",
  "expiryDate": "2023-01-05",
  "packageType": "MONTHLY",
  "status": "ACTIVE",
  "programId": "",
  "duration": "",
  "period": "",
  "disease": [
    {
      "diseaseId": "a721f7a0-c20c-11ec-8195-fb3d9a5f7244",
      "diseaseName": "Heart Disease"
    }
  ],
  "startDate": "",
  "canStartProgram": false,
  "diseaseName": "",
  "programName": "",
  "switchCount": 0,
  "canSwitchProgram": false,
  "allowPersonalCare": true,
  "enableRenew": false,
  "epochTimes": {
    "subscribeDate": 1670284800000,
    "expiryDate": 1672876800000,
    "startDate": null
  }
} 
*/

  String? subscriptionId;
  String? subscribeVia;
  String? userId;
  String? subscribeDate;
  String? expiryDate;
  String? packageType;
  String? status;
  String? programId;
  String? duration;
  String? period;
  List<SubscriptionCheckResponseSubscriptionDetailsDisease?>? disease;
  String? startDate;
  bool? canStartProgram;
  String? diseaseName;
  String? programName;
  int? switchCount;
  bool? canSwitchProgram;
  bool? allowPersonalCare;
  bool? enableRenew;
  SubscriptionCheckResponseSubscriptionDetailsEpochTimes? epochTimes;

  SubscriptionCheckResponseSubscriptionDetails({
    this.subscriptionId,
    this.subscribeVia,
    this.userId,
    this.subscribeDate,
    this.expiryDate,
    this.packageType,
    this.status,
    this.programId,
    this.duration,
    this.period,
    this.disease,
    this.startDate,
    this.canStartProgram,
    this.diseaseName,
    this.programName,
    this.switchCount,
    this.canSwitchProgram,
    this.allowPersonalCare,
    this.enableRenew,
    this.epochTimes,
  });
  SubscriptionCheckResponseSubscriptionDetails.fromJson(Map<String, dynamic> json) {
    subscriptionId = json['subscriptionId']?.toString();
    subscribeVia = json['subscribeVia']?.toString();
    userId = json['userId']?.toString();
    subscribeDate = json['subscribeDate']?.toString();
    expiryDate = json['expiryDate']?.toString();
    packageType = json['packageType']?.toString();
    status = json['status']?.toString();
    programId = json['programId']?.toString();
    duration = json['duration']?.toString();
    period = json['period']?.toString();
  if (json['disease'] != null) {
  final v = json['disease'];
  final arr0 = <SubscriptionCheckResponseSubscriptionDetailsDisease>[];
  v.forEach((v) {
  arr0.add(SubscriptionCheckResponseSubscriptionDetailsDisease.fromJson(v));
  });
    disease = arr0;
    }
    startDate = json['startDate']?.toString();
    canStartProgram = json['canStartProgram'];
    diseaseName = json['diseaseName']?.toString();
    programName = json['programName']?.toString();
    switchCount = json['switchCount']?.toInt();
    canSwitchProgram = json['canSwitchProgram'];
    allowPersonalCare = json['allowPersonalCare'];
    enableRenew = json['enableRenew'];
    epochTimes = (json['epochTimes'] != null) ? SubscriptionCheckResponseSubscriptionDetailsEpochTimes.fromJson(json['epochTimes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['subscriptionId'] = subscriptionId;
    data['subscribeVia'] = subscribeVia;
    data['userId'] = userId;
    data['subscribeDate'] = subscribeDate;
    data['expiryDate'] = expiryDate;
    data['packageType'] = packageType;
    data['status'] = status;
    data['programId'] = programId;
    data['duration'] = duration;
    data['period'] = period;
    if (disease != null) {
      final v = disease;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['disease'] = arr0;
    }
    data['startDate'] = startDate;
    data['canStartProgram'] = canStartProgram;
    data['diseaseName'] = diseaseName;
    data['programName'] = programName;
    data['switchCount'] = switchCount;
    data['canSwitchProgram'] = canSwitchProgram;
    data['allowPersonalCare'] = allowPersonalCare;
    data['enableRenew'] = enableRenew;
    if (epochTimes != null) {
      data['epochTimes'] = epochTimes!.toJson();
    }
    return data;
  }
}

class SubscriptionCheckResponse {
/*
{
  "subscriptionDetails": {
    "subscriptionId": "f87ae030-7571-11ed-ab68-515ee8254622",
    "subscribeVia": "HEALING",
    "userId": "3ae2cbc0-6c87-11ed-943c-5faea9fec6a5",
    "subscribeDate": "2022-12-06",
    "expiryDate": "2023-01-05",
    "packageType": "MONTHLY",
    "status": "ACTIVE",
    "programId": "",
    "duration": "",
    "period": "",
    "disease": [
      {
        "diseaseId": "a721f7a0-c20c-11ec-8195-fb3d9a5f7244",
        "diseaseName": "Heart Disease"
      }
    ],
    "startDate": "",
    "canStartProgram": false,
    "diseaseName": "",
    "programName": "",
    "switchCount": 0,
    "canSwitchProgram": false,
    "allowPersonalCare": true,
    "enableRenew": false,
    "epochTimes": {
      "subscribeDate": 1670284800000,
      "expiryDate": 1672876800000,
      "startDate": null
    }
  }
} 
*/

  SubscriptionCheckResponseSubscriptionDetails? subscriptionDetails;

  SubscriptionCheckResponse({
    this.subscriptionDetails,
  });
  SubscriptionCheckResponse.fromJson(Map<String, dynamic> json) {
    subscriptionDetails = (json['subscriptionDetails'] != null) ? SubscriptionCheckResponseSubscriptionDetails.fromJson(json['subscriptionDetails']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (subscriptionDetails != null) {
      data['subscriptionDetails'] = subscriptionDetails!.toJson();
    }
    return data;
  }
}