///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubscriptionTestimonialModelDetailsTestimonials {
/*
{
  "testimonial": "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  "userId": "123456",
  "userName": "Mahesh Karande",
  "gender": "Male",
  "profileImage": "",
  "createdAt": "2022-10-01"
} 
*/

  String? testimonial;
  String? userId;
  String? userName;
  String? gender;
  String? profileImage;
  String? createdAt;

  SubscriptionTestimonialModelDetailsTestimonials({
    this.testimonial,
    this.userId,
    this.userName,
    this.gender,
    this.profileImage,
    this.createdAt,
  });
  SubscriptionTestimonialModelDetailsTestimonials.fromJson(
      Map<String, dynamic> json) {
    testimonial = json['testimonial']?.toString();
    userId = json['userId']?.toString();
    userName = json['userName']?.toString();
    gender = json['gender']?.toString();
    profileImage = json['profileImage']?.toString();
    createdAt = json['createdAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['testimonial'] = testimonial;
    data['userId'] = userId;
    data['userName'] = userName;
    data['gender'] = gender;
    data['profileImage'] = profileImage;
    data['createdAt'] = createdAt;
    return data;
  }
}

class SubscriptionTestimonialModelDetails {
/*
{
  "section": "WHAT OUR USERS SAY",
  "subTitle": "",
  "bottomText": "Start practicing with AAYU everyday to begin a betterlife with peace, love, health & happiness",
  "testimonials": [
    {
      "testimonial": "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      "userId": "123456",
      "userName": "Mahesh Karande",
      "gender": "Male",
      "profileImage": "",
      "createdAt": "2022-10-01"
    }
  ]
} 
*/

  String? section;
  String? subTitle;
  String? bottomText;
  List<SubscriptionTestimonialModelDetailsTestimonials?>? testimonials;

  SubscriptionTestimonialModelDetails({
    this.section,
    this.subTitle,
    this.bottomText,
    this.testimonials,
  });
  SubscriptionTestimonialModelDetails.fromJson(Map<String, dynamic> json) {
    section = json['section']?.toString();
    subTitle = json['subTitle']?.toString();
    bottomText = json['bottomText']?.toString();
    if (json['testimonials'] != null) {
      final v = json['testimonials'];
      final arr0 = <SubscriptionTestimonialModelDetailsTestimonials>[];
      v.forEach((v) {
        arr0.add(SubscriptionTestimonialModelDetailsTestimonials.fromJson(v));
      });
      testimonials = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['section'] = section;
    data['subTitle'] = subTitle;
    data['bottomText'] = bottomText;
    if (testimonials != null) {
      final v = testimonials;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['testimonials'] = arr0;
    }
    return data;
  }
}

class SubscriptionTestimonialModel {
/*
{
  "details": {
    "section": "WHAT OUR USERS SAY",
    "subTitle": "",
    "bottomText": "Start practicing with AAYU everyday to begin a betterlife with peace, love, health & happiness",
    "testimonials": [
      {
        "testimonial": "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        "userId": "123456",
        "userName": "Mahesh Karande",
        "gender": "Male",
        "profileImage": "",
        "createdAt": "2022-10-01"
      }
    ]
  }
} 
*/

  SubscriptionTestimonialModelDetails? details;

  SubscriptionTestimonialModel({
    this.details,
  });
  SubscriptionTestimonialModel.fromJson(Map<String, dynamic> json) {
    details = (json['details'] != null)
        ? SubscriptionTestimonialModelDetails.fromJson(json['details'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (details != null) {
      data['details'] = details!.toJson();
    }
    return data;
  }
}
