///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TodaysWaterIntakeDetailsModelDetailsReminder {
/*
{
  "isActive": false,
  "fromTime": 0,
  "toTime": 0,
  "interval": 0
} 
*/

  bool? isActive;
  int? fromTime;
  int? toTime;
  int? interval;

  TodaysWaterIntakeDetailsModelDetailsReminder({
    this.isActive,
    this.fromTime,
    this.toTime,
    this.interval,
  });
  TodaysWaterIntakeDetailsModelDetailsReminder.fromJson(Map<String, dynamic> json) {
    isActive = json['isActive'];
    fromTime = int.tryParse(json['fromTime']?.toString() ?? '');
    toTime = int.tryParse(json['toTime']?.toString() ?? '');
    interval = int.tryParse(json['interval']?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isActive'] = isActive;
    data['fromTime'] = fromTime;
    data['toTime'] = toTime;
    data['interval'] = interval;
    return data;
  }
}

class TodaysWaterIntakeDetailsModelDetailsDailyTarget {
/*
{
  "isActive": true,
  "maxLimit": 3
} 
*/

  bool? isActive;
  int? maxLimit;

  TodaysWaterIntakeDetailsModelDetailsDailyTarget({
    this.isActive,
    this.maxLimit,
  });
  TodaysWaterIntakeDetailsModelDetailsDailyTarget.fromJson(Map<String, dynamic> json) {
    isActive = json['isActive'];
    maxLimit = int.tryParse(json['maxLimit']?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isActive'] = isActive;
    data['maxLimit'] = maxLimit;
    return data;
  }
}

class TodaysWaterIntakeDetailsModelDetails {
/*
{
  "dailyTarget": {
    "isActive": true,
    "maxLimit": 3
  },
  "reminder": {
    "isActive": false,
    "fromTime": 0,
    "toTime": 0,
    "interval": 0
  },
  "todaysIntake": 0
} 
*/

  TodaysWaterIntakeDetailsModelDetailsDailyTarget? dailyTarget;
  TodaysWaterIntakeDetailsModelDetailsReminder? reminder;
  int? todaysDate;
  int? todaysIntake;

  TodaysWaterIntakeDetailsModelDetails({
    this.dailyTarget,
    this.reminder,
    this.todaysIntake,
  });
  TodaysWaterIntakeDetailsModelDetails.fromJson(Map<String, dynamic> json) {
    dailyTarget = (json['dailyTarget'] != null && (json['dailyTarget'] is Map)) ? TodaysWaterIntakeDetailsModelDetailsDailyTarget.fromJson(json['dailyTarget']) : null;
    reminder = (json['reminder'] != null && (json['reminder'] is Map)) ? TodaysWaterIntakeDetailsModelDetailsReminder.fromJson(json['reminder']) : null;
    todaysDate = int.tryParse(json['todaysDate']?.toString() ?? '');
    todaysIntake = int.tryParse(json['todaysIntake']?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (dailyTarget != null) {
      data['dailyTarget'] = dailyTarget!.toJson();
    }
    if (reminder != null) {
      data['reminder'] = reminder!.toJson();
    }
    data['todaysDate'] = todaysDate;
    data['todaysIntake'] = todaysIntake;
    return data;
  }
}

class TodaysWaterIntakeDetailsModel {
/*
{
  "details": {
    "dailyTarget": {
      "isActive": true,
      "maxLimit": 3
    },
    "reminder": {
      "isActive": false,
      "fromTime": 0,
      "toTime": 0,
      "interval": 0
    },
    "todaysIntake": 0
  }
} 
*/

  TodaysWaterIntakeDetailsModelDetails? details;

  TodaysWaterIntakeDetailsModel({
    this.details,
  });
  TodaysWaterIntakeDetailsModel.fromJson(Map<String, dynamic> json) {
    details = (json['details'] != null && (json['details'] is Map)) ? TodaysWaterIntakeDetailsModelDetails.fromJson(json['details']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (details != null) {
      data['details'] = details!.toJson();
    }
    return data;
  }
}
