///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WaterIntakeSummaryModelSummary {
/*
{
  "intakeDate": "04",
  "total": 6000
} 
*/

  String? intakeDate;
  int? total;

  WaterIntakeSummaryModelSummary({
    this.intakeDate,
    this.total,
  });
  WaterIntakeSummaryModelSummary.fromJson(Map<String, dynamic> json) {
    intakeDate = json['intakeDate']?.toString();
    total = int.tryParse(json['total']?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['intakeDate'] = intakeDate;
    data['total'] = total;
    return data;
  }
}

class WaterIntakeSummaryModel {
/*
{
  "fromDate": 1672511400000,
  "toDate": 1703961000000,
  "summary": [
    {
      "intakeDate": "04",
      "total": 6000
    }
  ]
} 
*/

  int? fromDate;
  int? toDate;
  List<WaterIntakeSummaryModelSummary?>? summary;

  WaterIntakeSummaryModel({
    this.fromDate,
    this.toDate,
    this.summary,
  });
  WaterIntakeSummaryModel.fromJson(Map<String, dynamic> json) {
    fromDate = int.tryParse(json['fromDate']?.toString() ?? '');
    toDate = int.tryParse(json['toDate']?.toString() ?? '');
  if (json['summary'] != null && (json['summary'] is List)) {
  final v = json['summary'];
  final arr0 = <WaterIntakeSummaryModelSummary>[];
  v.forEach((v) {
  arr0.add(WaterIntakeSummaryModelSummary.fromJson(v));
  });
    summary = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['fromDate'] = fromDate;
    data['toDate'] = toDate;
    if (summary != null) {
      final v = summary;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['summary'] = arr0;
    }
    return data;
  }
}
